## This file is a general .xdc for the Basys3 rev B board
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

 Clock signal
set_property PACKAGE_PIN W5 [get_ports CLK]							
	set_property IOSTANDARD LVCMOS33 [get_ports CLK]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports CLK]
 
 Switches
set_property PACKAGE_PIN V17 [get_ports SW0]					
	set_property IOSTANDARD LVCMOS33 [get_ports SW0]
set_property PACKAGE_PIN V16 [get_ports SW1]					
	set_property IOSTANDARD LVCMOS33 [get_ports SW1]
set_property PACKAGE_PIN W16 [get_ports SW2]					
	set_property IOSTANDARD LVCMOS33 [get_ports SW2]
set_property PACKAGE_PIN W17 [get_ports SW3]					
	set_property IOSTANDARD LVCMOS33 [get_ports SW3]
set_property PACKAGE_PIN W15 [get_ports SW4]					
	set_property IOSTANDARD LVCMOS33 [get_ports SW4]
set_property PACKAGE_PIN V15 [get_ports SW5]					
	set_property IOSTANDARD LVCMOS33 [get_ports SW5]
set_property PACKAGE_PIN W14 [get_ports SW6]					
	set_property IOSTANDARD LVCMOS33 [get_ports SW6]
set_property PACKAGE_PIN W13 [get_ports SW7]					
	set_property IOSTANDARD LVCMOS33 [get_ports SW7]
set_property PACKAGE_PIN V2 [get_ports SW8]					
	set_property IOSTANDARD LVCMOS33 [get_ports SW8]
set_property PACKAGE_PIN T3 [get_ports SW9]					
	set_property IOSTANDARD LVCMOS33 [get_ports SW9]
set_property PACKAGE_PIN T2 [get_ports SW10]					
	set_property IOSTANDARD LVCMOS33 [get_ports SW10]
set_property PACKAGE_PIN R3 [get_ports SW11]					
	set_property IOSTANDARD LVCMOS33 [get_ports SW11]
#set_property PACKAGE_PIN W2 [get_ports SW12]					
	#set_property IOSTANDARD LVCMOS33 [get_ports SW12]
#set_property PACKAGE_PIN U1 [get_ports SW13]					
	#set_property IOSTANDARD LVCMOS33 [get_ports SW13]
#set_property PACKAGE_PIN T1 [get_ports SW14]					
	#set_property IOSTANDARD LVCMOS33 [get_ports SW14]
#set_property PACKAGE_PIN R2 [get_ports SW15]					
	#set_property IOSTANDARD LVCMOS33 [get_ports SW15]
 

 LEDs
set_property PACKAGE_PIN U16 [get_ports LED0]					
	set_property IOSTANDARD LVCMOS33 [get_ports LED0]
set_property PACKAGE_PIN E19 [get_ports LED1]					
	set_property IOSTANDARD LVCMOS33 [get_ports LED1]
set_property PACKAGE_PIN U19 [get_ports LED2]					
	set_property IOSTANDARD LVCMOS33 [get_ports LED2]
set_property PACKAGE_PIN V19 [get_ports LED3]					
	set_property IOSTANDARD LVCMOS33 [get_ports LED3]
set_property PACKAGE_PIN W18 [get_ports LED4]					
	set_property IOSTANDARD LVCMOS33 [get_ports LED4]
set_property PACKAGE_PIN U15 [get_ports LED5]					
	set_property IOSTANDARD LVCMOS33 [get_ports LED5]
set_property PACKAGE_PIN U14 [get_ports LED6]					
	set_property IOSTANDARD LVCMOS33 [get_ports LED6]
set_property PACKAGE_PIN V14 [get_ports LED7]					
	set_property IOSTANDARD LVCMOS33 [get_ports LED7]
set_property PACKAGE_PIN V13 [get_ports LED8]					
	set_property IOSTANDARD LVCMOS33 [get_ports LED8]
#set_property PACKAGE_PIN V3 [get_ports LED9]					
	#set_property IOSTANDARD LVCMOS33 [get_ports LED9]
#set_property PACKAGE_PIN W3 [get_ports LED10]					
	#set_property IOSTANDARD LVCMOS33 [get_ports LED10]
#set_property PACKAGE_PIN U3 [get_ports LED11]					
	#set_property IOSTANDARD LVCMOS33 [get_ports LED11]
#set_property PACKAGE_PIN P3 [get_ports LED12]					
	#set_property IOSTANDARD LVCMOS33 [get_ports LED12]
#set_property PACKAGE_PIN N3 [get_ports LED13]					
	#set_property IOSTANDARD LVCMOS33 [get_ports LED13]
#set_property PACKAGE_PIN P1 [get_ports LED14]					
	#set_property IOSTANDARD LVCMOS33 [get_ports LED14]
#set_property PACKAGE_PIN L1 [get_ports LED15]					
	#set_property IOSTANDARD LVCMOS33 [get_ports LED15]
	
	
7 segment display
set_property PACKAGE_PIN W7 [get_ports CA]					
	set_property IOSTANDARD LVCMOS33 [get_ports CA]
set_property PACKAGE_PIN W6 [get_ports CB]					
	set_property IOSTANDARD LVCMOS33 [get_ports CB]
set_property PACKAGE_PIN U8 [get_ports CC]					
	set_property IOSTANDARD LVCMOS33 [get_ports CC]
set_property PACKAGE_PIN V8 [get_ports CD]					
	set_property IOSTANDARD LVCMOS33 [get_ports CD]
set_property PACKAGE_PIN U5 [get_ports CE]					
	set_property IOSTANDARD LVCMOS33 [get_ports CE]
set_property PACKAGE_PIN V5 [get_ports CF]					
	set_property IOSTANDARD LVCMOS33 [get_ports CF]
set_property PACKAGE_PIN U7 [get_ports CG]					
	set_property IOSTANDARD LVCMOS33 [get_ports CG]

set_property PACKAGE_PIN V7 [get_ports dp]							
	set_property IOSTANDARD LVCMOS33 [get_ports dp]

set_property PACKAGE_PIN U2 [get_ports AN0]					
	set_property IOSTANDARD LVCMOS33 [get_ports AN0]
set_property PACKAGE_PIN U4 [get_ports AN1]					
	set_property IOSTANDARD LVCMOS33 [get_ports AN1]
set_property PACKAGE_PIN V4 [get_ports AN2]					
	set_property IOSTANDARD LVCMOS33 [get_ports AN2]
set_property PACKAGE_PIN W4 [get_ports AN3]					
	set_property IOSTANDARD LVCMOS33 [get_ports AN3]


Buttons
set_property PACKAGE_PIN U18 [get_ports btnC]						
	set_property IOSTANDARD LVCMOS33 [get_ports btnC]
set_property PACKAGE_PIN T18 [get_ports btnU]						
	set_property IOSTANDARD LVCMOS33 [get_ports btnU]
set_property PACKAGE_PIN W19 [get_ports btnL]						
	set_property IOSTANDARD LVCMOS33 [get_ports btnL]
set_property PACKAGE_PIN T17 [get_ports btnR]						
	set_property IOSTANDARD LVCMOS33 [get_ports btnR]
set_property PACKAGE_PIN U17 [get_ports btnD]						
	set_property IOSTANDARD LVCMOS33 [get_ports btnD] 

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets btnC]	
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets btnR]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets btnL]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets btnU]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets btnD]


##VGA Connector
VGA Connector
set_property PACKAGE_PIN G19 [get_ports R0]				
	set_property IOSTANDARD LVCMOS33 [get_ports R0]
set_property PACKAGE_PIN H19 [get_ports R1]				
	set_property IOSTANDARD LVCMOS33 [get_ports R1]
set_property PACKAGE_PIN J19 [get_ports R2]				
	set_property IOSTANDARD LVCMOS33 [get_ports R2]
set_property PACKAGE_PIN N19 [get_ports R3]				
	set_property IOSTANDARD LVCMOS33 [get_ports R3]
set_property PACKAGE_PIN N18 [get_ports B0]				
	set_property IOSTANDARD LVCMOS33 [get_ports B0]
set_property PACKAGE_PIN L18 [get_ports B1]				
	set_property IOSTANDARD LVCMOS33 [get_ports B1]
set_property PACKAGE_PIN K18 [get_ports B2]				
	set_property IOSTANDARD LVCMOS33 [get_ports B2]
set_property PACKAGE_PIN J18 [get_ports B3]				
	set_property IOSTANDARD LVCMOS33 [get_ports B3]
set_property PACKAGE_PIN J17 [get_ports G0]				
	set_property IOSTANDARD LVCMOS33 [get_ports G0]
set_property PACKAGE_PIN H17 [get_ports G1]				
	set_property IOSTANDARD LVCMOS33 [get_ports G1]
set_property PACKAGE_PIN G17 [get_ports G2]				
	set_property IOSTANDARD LVCMOS33 [get_ports G2]
set_property PACKAGE_PIN D17 [get_ports G3]				
	set_property IOSTANDARD LVCMOS33 [get_ports G3]
set_property PACKAGE_PIN P19 [get_ports Hsync]						
	set_property IOSTANDARD LVCMOS33 [get_ports Hsync]
set_property PACKAGE_PIN R19 [get_ports Vsync]						
	set_property IOSTANDARD LVCMOS33 [get_ports Vsync]
	
	
##Pmod Header JB -- useful to output signals on Basys 3 pins that can be measured with oscilloscope
#set_property PACKAGE_PIN A14 [get_ports JB0];#Sch name = JB1
	#set_property IOSTANDARD LVCMOS33 [get_ports JB0]
#set_property PACKAGE_PIN A16 [get_ports JB1];#Sch name = JB2
	#set_property IOSTANDARD LVCMOS33 [get_ports JB1]
#set_property PACKAGE_PIN B15 [get_ports JB2];#Sch name = JB3
	#set_property IOSTANDARD LVCMOS33 [get_ports JB2]
#set_property PACKAGE_PIN B16 [get_ports JB3];#Sch name = JB4
	#set_property IOSTANDARD LVCMOS33 [get_ports JB3]