---------------------------------------------------
-- Sheet: Stage3_VGA_rectangle_blink
-- RefDes: 
-- Part Number: XC7A35T
-- Generated By: Multisim
--
-- Author: 35172
-- Date: Saturday, April 19 11:52:55, 2025
---------------------------------------------------

---------------------------------------------------
-- Use: This file defines the top-level of the design
-- Use with the exported package file
---------------------------------------------------
library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;

library work;
use work.Stage3_stable_edition_pkg.ALL;


entity Stage3_VGA_rectangle_blink is
	port (

		B0 : out std_logic;
		B1 : out std_logic;
		B2 : out std_logic;
		B3 : out std_logic;
		G0 : out std_logic;
		G1 : out std_logic;
		G2 : out std_logic;
		G3 : out std_logic;
		R0 : out std_logic;
		R1 : out std_logic;
		R2 : out std_logic;
		R3 : out std_logic;
		btnC : in std_logic;
		btnD : in std_logic;
		btnL : in std_logic;
		btnR : in std_logic;
		btnU : in std_logic;
		SW0 : in std_logic;
		SW1 : in std_logic;
		SW2 : in std_logic;
		SW3 : in std_logic;
		SW4 : in std_logic;
		SW5 : in std_logic;
		SW6 : in std_logic;
		SW7 : in std_logic;
		SW8 : in std_logic;
		SW9 : in std_logic;
		SW10 : in std_logic;
		SW11 : in std_logic;
		Hsync : out std_logic;
		Vsync : out std_logic;
		CLK : in std_logic;
		CA : out std_logic;
		CB : out std_logic;
		CC : out std_logic;
		CD : out std_logic;
		CE : out std_logic;
		CF : out std_logic;
		CG : out std_logic;
		AN0 : out std_logic;
		AN1 : out std_logic;
		AN2 : out std_logic;
		AN3 : out std_logic;
		LED0 : out std_logic;
		LED1 : out std_logic;
		LED2 : out std_logic;
		LED3 : out std_logic;
		LED4 : out std_logic;
		LED5 : out std_logic;
		LED6 : out std_logic;
		LED7 : out std_logic;
		LED8 : out std_logic;
		dp : out std_logic
	);
end Stage3_VGA_rectangle_blink;


architecture behavioral of Stage3_VGA_rectangle_blink is


	component AND2_NI
		port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component AND3_NI
		port (
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component AND4_NI
		port (
    D : in STD_LOGIC := 'X';
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component AND5_NI
		port (
    E : in STD_LOGIC := 'X';
    D : in STD_LOGIC := 'X';
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component AND6_NI
		port (
    F : in STD_LOGIC := 'X';
    E : in STD_LOGIC := 'X';
    D : in STD_LOGIC := 'X';
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component AND7_NI
		port (
    G : in STD_LOGIC := 'X';
    F : in STD_LOGIC := 'X';
    E : in STD_LOGIC := 'X';
    D : in STD_LOGIC := 'X';
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component AND8_NI
		port (
    H : in STD_LOGIC := 'X';
    G : in STD_LOGIC := 'X';
    F : in STD_LOGIC := 'X';
    E : in STD_LOGIC := 'X';
    D : in STD_LOGIC := 'X';
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component AUTO_IBUF
		port(
		I : in std_logic;
		O : out std_logic
	);
	end component;

	component AUTO_OBUF
		port(
		I : in std_logic;
		O : out std_logic
	);
	end component;

	component BUF_INV_NI
		port (
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component CNTR_4BIN_ASCLR_NI
		port( 
  LOAD: in std_logic;
  CLR: in std_logic;
  ENP: in std_logic; 
  ENT: in std_logic;
  CLK: in std_logic;
  A:in STD_LOGIC;
  B:in STD_LOGIC;
  C:in STD_LOGIC;
  D:in STD_LOGIC;
  RCO: out STD_LOGIC;
  QA: out STD_LOGIC;
  QB: out STD_LOGIC;
  QC: out STD_LOGIC;
  QD: out STD_LOGIC
 );
	end component;

	component CNTR_4BIN_S_NI
		port( 
  LOAD: in STD_LOGIC;
  CLR: in STD_LOGIC;
  ENP: in STD_LOGIC; 
  ENT: in STD_LOGIC;
  CLK: in STD_LOGIC;
  A :in STD_LOGIC;
  B :in STD_LOGIC;
  C :in STD_LOGIC;
  D :in STD_LOGIC;
  RCO : out STD_LOGIC;
  QA : out STD_LOGIC;
  QB : out STD_LOGIC;
  QC : out STD_LOGIC;
  QD : out STD_LOGIC
 );
	end component;

	component CNTR_4BIN_SU_D_NI
		port( 
  LOAD: in STD_LOGIC;
  UD: in STD_LOGIC;
  CTEN: in STD_LOGIC; 
  CLK: in STD_LOGIC;
  A:in STD_LOGIC;
  B:in STD_LOGIC;
  C:in STD_LOGIC;
  D:in STD_LOGIC;
  RCO: out STD_LOGIC;
  MAXMIN: out STD_LOGIC;
  QA: out STD_LOGIC;
  QB: out STD_LOGIC;
  QC: out STD_LOGIC;
  QD: out STD_LOGIC
 );
	end component;

	component CNTR_BCD_S_NI
		port( 
  LOAD: in std_logic;
  CLR: in std_logic;
  ENP: in std_logic; 
  ENT: in std_logic;
  CLK: in std_logic;
  A:in STD_LOGIC;
  B:in STD_LOGIC;
  C:in STD_LOGIC;
  D:in STD_LOGIC;
  RCO: out STD_LOGIC;
  QA: out STD_LOGIC;
  QB: out STD_LOGIC;
  QC: out STD_LOGIC;
  QD: out STD_LOGIC
 );
	end component;

	component COMP_4_NI
		port (
   B3 : in STD_LOGIC := 'X';
   B2 : in STD_LOGIC := 'X';
   B1 : in STD_LOGIC := 'X';
   B0 : in STD_LOGIC := 'X';
   A3 : in STD_LOGIC := 'X';
   A2 : in STD_LOGIC := 'X';
   A1 : in STD_LOGIC := 'X';
   A0 : in STD_LOGIC := 'X';
   AGTB : in STD_LOGIC := 'X';
   AEQB : in STD_LOGIC := 'X';
   ALTB : in STD_LOGIC := 'X';
   OAGTB : out STD_LOGIC := 'U';
   OAEQB : out STD_LOGIC := 'U';
   OALTB : out STD_LOGIC := 'U'
    );
	end component;

	component DEC2_4_NI
		port (
 A : in STD_LOGIC;
 B : in STD_LOGIC;
 Y0 : out STD_LOGIC;
 Y1 : out STD_LOGIC;
 Y2 : out STD_LOGIC;
 Y3 : out STD_LOGIC;
 EN: in  STD_LOGIC
 );
	end component;

	component DEC_BCD_7_NI
		port (
  A : in STD_LOGIC;
  B : in STD_LOGIC;
  C : in STD_LOGIC;
  D : in STD_LOGIC;
  LT : in STD_LOGIC;
  RBI : in STD_LOGIC;
  BI : in STD_LOGIC;
  Y0 : out STD_LOGIC;
  Y1 : out STD_LOGIC;
  Y2 : out STD_LOGIC;
  Y3 : out STD_LOGIC;
  Y4 : out STD_LOGIC;
  Y5 : out STD_LOGIC;
  Y6 : out STD_LOGIC
 );
	end component;

	component DIGITAL_HIGH_NI
		Port ( 
  Y : out  STD_LOGIC:='1'
 );
	end component;

	component DIGITAL_LOW_NI
		Port ( 
  Y : out  STD_LOGIC:='0'
 );
	end component;

	component ENC10_4_NI
		port (
  A : out STD_LOGIC;
  B : out STD_LOGIC;
  C : out STD_LOGIC;
  D : out STD_LOGIC;
  I1 : in STD_LOGIC;
  I2 : in STD_LOGIC;
  I3 : in STD_LOGIC;
  I4 : in STD_LOGIC;
  I5 : in STD_LOGIC;
  I6 : in STD_LOGIC;
  I7 : in STD_LOGIC;
  I8 : in STD_LOGIC;
  I9 : in STD_LOGIC
 );
	end component;

	component ENC8_3_NI
		port (
  A0 : out STD_LOGIC;
  A1 : out STD_LOGIC;
  A2 : out STD_LOGIC;
  GS : out STD_LOGIC;
  EO : out STD_LOGIC;
  I0 : in STD_LOGIC;
  I1 : in STD_LOGIC;
  I2 : in STD_LOGIC;
  I3 : in STD_LOGIC;
  I4 : in STD_LOGIC;
  I5 : in STD_LOGIC;
  I6 : in STD_LOGIC;
  I7 : in STD_LOGIC;
  EI : in STD_LOGIC
 );
	end component;

	component FF_D_CO_NI
		Port ( D : in  STD_LOGIC;
           CLK : in  STD_LOGIC;
           Q : out  STD_LOGIC;
           Qneg : out  STD_LOGIC);
	end component;

	component FF_JK_PSCLR_CO_NI
		port (
   J: in STD_LOGIC;
   K: in STD_LOGIC;
   CLK : in STD_LOGIC;  
   PR: in STD_LOGIC;
   CLR: in STD_LOGIC;
   Q : out STD_LOGIC;
   Qneg : out STD_LOGIC
);
	end component;

	component FF_T_CLR_CO_NI
		port (
    T: in STD_LOGIC;
    CLK : in STD_LOGIC;
    CLR : in STD_LOGIC;
     Q : out STD_LOGIC;
     Qneg : out STD_LOGIC
 );
	end component;

	component INV_NI
		port (
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component MUX2_1_NI
		port (
   Y : out STD_LOGIC;
   A : in STD_LOGIC;
   B : in STD_LOGIC;
   S : in STD_LOGIC;
   G : in STD_LOGIC
  );
	end component;

	component MUX4_1_NI
		port (
  Y : out STD_LOGIC;
  I0 : in STD_LOGIC;
  I1 : in STD_LOGIC;
  I2 : in STD_LOGIC;
  I3 : in STD_LOGIC;
  S0 : in STD_LOGIC;
  S1 : in STD_LOGIC;
  EN : in STD_LOGIC
 );
	end component;

	component MUX8_1_NI
		port (
   Y : out STD_LOGIC;
   D0 : in STD_LOGIC;
   D1 : in STD_LOGIC;
   D2 : in STD_LOGIC;
   D3 : in STD_LOGIC;
   D4 : in STD_LOGIC;
   D5 : in STD_LOGIC;
   D6 : in STD_LOGIC;
   D7 : in STD_LOGIC;
    A : in STD_LOGIC;
    B : in STD_LOGIC;
    C : in STD_LOGIC;
    G : in STD_LOGIC
  );
	end component;

	component NAND2_NI
		port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component NAND4_NI
		port (
    D : in STD_LOGIC := 'X';
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component NAND5_NI
		port (
    E : in STD_LOGIC := 'X';
    D : in STD_LOGIC := 'X';
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component NOR2_NI
		port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component NOR3_NI
		port (
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component NOR4_NI
		port (
    D : in STD_LOGIC := 'X';
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component NOR5_NI
		port (
    E : in STD_LOGIC := 'X';
    D : in STD_LOGIC := 'X';
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component NOR6_NI
		port (
    F : in STD_LOGIC := 'X';
    E : in STD_LOGIC := 'X';
    D : in STD_LOGIC := 'X';
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component NOR8_NI
		port (
    H : in STD_LOGIC := 'X';
    G : in STD_LOGIC := 'X';
    F : in STD_LOGIC := 'X';
    E : in STD_LOGIC := 'X';
    D : in STD_LOGIC := 'X';
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component OR2_NI
		port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component OR4_NI
		port (
    D : in STD_LOGIC := 'X';
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component OR5_NI
		port (
    E : in STD_LOGIC := 'X';
    D : in STD_LOGIC := 'X';
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component SR_4BIDI_NI
		port (
   A : in STD_LOGIC;
   B : in STD_LOGIC;
   C : in STD_LOGIC;
   D : in STD_LOGIC;
   S0 : in STD_LOGIC;
   S1 : in STD_LOGIC;
   CLR : in STD_LOGIC;
   CLK : in STD_LOGIC;
   SR : in STD_LOGIC;
   SL : in STD_LOGIC;
   QA : out STD_LOGIC;
   QB : out STD_LOGIC;
   QC : out STD_LOGIC;
   QD : out STD_LOGIC 
  );
	end component;

	component XOR2_NI
		port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;
	signal \1\ : std_logic;
	signal \PLD37/Write_row_bit1\ : std_logic;
	signal \PLD14/LED3\ : std_logic;
	signal \PLD16/Q9\ : std_logic;
	signal \PLD37/Read11\ : std_logic;
	signal \PLD21/VBLANK\ : std_logic;
	signal \PLD33/CF\ : std_logic;
	signal \PLD16/Q5\ : std_logic;
	signal \PLD37/Read3\ : std_logic;
	signal \PLD16/Q2\ : std_logic;
	signal \PLD16/Q8\ : std_logic;
	signal \PLD37/W_4\ : std_logic;
	signal \PLD14/LED0\ : std_logic;
	signal \PLD37/W_5\ : std_logic;
	signal \PLD1/CLOCK_A_25MHz\ : std_logic;
	signal \PLD16/Q6\ : std_logic;
	signal \PLD16/Q12\ : std_logic;
	signal \PLD1/clk_100MHz\ : std_logic;
	signal \PLD16/Flashing\ : std_logic;
	signal \PLD25/Right\ : std_logic;
	signal \PLD37/CLK_FF_500Hz\ : std_logic;
	signal \PLD33/AN1\ : std_logic;
	signal \PLD21/HBLANK\ : std_logic;
	signal \PLD33/CA\ : std_logic;
	signal \PLD16/Q7\ : std_logic;
	signal \PLD16/Q3\ : std_logic;
	signal \PLD37/Read1\ : std_logic;
	signal \PLD1/CLOCK_C_05Hz\ : std_logic;
	signal \PLD37/W_8\ : std_logic;
	signal \PLD25/CLK_FF\ : std_logic;
	signal \PLD14/Row_bit_2\ : std_logic;
	signal \PLD37/Row_bit_1\ : std_logic;
	signal \PLD14/LED6\ : std_logic;
	signal \PLD37/CLOCK_1Hz\ : std_logic;
	signal \PLD37/W_7\ : std_logic;
	signal \PLD37/Column_bit_1\ : std_logic;
	signal \PLD16/Q10\ : std_logic;
	signal \PLD37/W_2\ : std_logic;
	signal \PLD37/Read8\ : std_logic;
	signal \PLD13/Hsync\ : std_logic;
	signal \PLD37/Read6\ : std_logic;
	signal \PLD16/Q4\ : std_logic;
	signal \PLD37/W_1\ : std_logic;
	signal \PLD37/Read12\ : std_logic;
	signal \PLD14/LED4\ : std_logic;
	signal \PLD33/Column_bit_1\ : std_logic;
	signal \PLD33/AN3\ : std_logic;
	signal \PLD33/CD\ : std_logic;
	signal \PLD33/CB\ : std_logic;
	signal \PLD14/LED8\ : std_logic;
	signal \PLD33/Column_bit_2\ : std_logic;
	signal \PLD25/Up\ : std_logic;
	signal \PLD37/W_10\ : std_logic;
	signal \PLD25/Down\ : std_logic;
	signal \PLD33/dp\ : std_logic;
	signal \PLD33/AN0\ : std_logic;
	signal \PLD37/Read4\ : std_logic;
	signal \PLD16/Q11\ : std_logic;
	signal \PLD25/Left\ : std_logic;
	signal \PLD37/Read5\ : std_logic;
	signal \PLD33/AN2\ : std_logic;
	signal \PLD37/W_6\ : std_logic;
	signal \PLD37/Read9\ : std_logic;
	signal \PLD37/W_9\ : std_logic;
	signal \PLD37/Read_EN\ : std_logic;
	signal \PLD37/Read2\ : std_logic;
	signal \PLD37/Write_Read_Equal\ : std_logic;
	signal \PLD37/Read7\ : std_logic;
	signal \PLD37/W_11\ : std_logic;
	signal \PLD37/Read_row_bit2\ : std_logic;
	signal \PLD37/W_12\ : std_logic;
	signal \PLD33/CC\ : std_logic;
	signal \PLD37/WRITE_CLOCK\ : std_logic;
	signal \PLD33/CG\ : std_logic;
	signal \PLD37/Column_bit_2\ : std_logic;
	signal \PLD37/Read10\ : std_logic;
	signal \PLD16/Q1\ : std_logic;
	signal \PLD33/CE\ : std_logic;
	signal \PLD37/W_3\ : std_logic;
	signal \PLD14/LED5\ : std_logic;
	signal \PLD18/CLR\ : std_logic;
	signal \PLD17/CLR\ : std_logic;
	signal \162\ : std_logic;
	signal \165\ : std_logic;
	signal \PLD19/Q3\ : std_logic;
	signal \PLD19/CLR\ : std_logic;
	signal \PLD19/Q10\ : std_logic;
	signal \163\ : std_logic;
	signal \164\ : std_logic;
	signal \PLD19/Q7\ : std_logic;
	signal \PLD19/Q8\ : std_logic;
	signal \PLD19/Q1\ : std_logic;
	signal \PLD19/Q2\ : std_logic;
	signal \PLD19/Q6\ : std_logic;
	signal \PLD19/Q5\ : std_logic;
	signal \PLD19/Q4\ : std_logic;
	signal \PLD19/Q9\ : std_logic;
	signal \PLD20/Q8\ : std_logic;
	signal \168\ : std_logic;
	signal \PLD20/Q3\ : std_logic;
	signal \PLD20/Q7\ : std_logic;
	signal \PLD20/Q2\ : std_logic;
	signal \PLD20/Q1\ : std_logic;
	signal \PLD20/Q6\ : std_logic;
	signal \PLD20/Q5\ : std_logic;
	signal \PLD20/Q10\ : std_logic;
	signal \167\ : std_logic;
	signal \PLD20/CLR\ : std_logic;
	signal \PLD20/Q9\ : std_logic;
	signal \59\ : std_logic;
	signal \169\ : std_logic;
	signal \PLD20/Q4\ : std_logic;
	signal \171\ : std_logic;
	signal \174\ : std_logic;
	signal \173\ : std_logic;
	signal \172\ : std_logic;
	signal \170\ : std_logic;
	signal \176\ : std_logic;
	signal \179\ : std_logic;
	signal \178\ : std_logic;
	signal \177\ : std_logic;
	signal \175\ : std_logic;
	signal \192\ : std_logic;
	signal \247\ : std_logic;
	signal \187\ : std_logic;
	signal \199\ : std_logic;
	signal \198\ : std_logic;
	signal \245\ : std_logic;
	signal \183\ : std_logic;
	signal \211\ : std_logic;
	signal \204\ : std_logic;
	signal \288\ : std_logic;
	signal \5\ : std_logic;
	signal \312\ : std_logic;
	signal \181\ : std_logic;
	signal \185\ : std_logic;
	signal \250\ : std_logic;
	signal \180\ : std_logic;
	signal \197\ : std_logic;
	signal \315\ : std_logic;
	signal \193\ : std_logic;
	signal \189\ : std_logic;
	signal \244\ : std_logic;
	signal \182\ : std_logic;
	signal \246\ : std_logic;
	signal \314\ : std_logic;
	signal \337\ : std_logic;
	signal \190\ : std_logic;
	signal \258\ : std_logic;
	signal \287\ : std_logic;
	signal \3\ : std_logic;
	signal \6\ : std_logic;
	signal \200\ : std_logic;
	signal \188\ : std_logic;
	signal \2\ : std_logic;
	signal \205\ : std_logic;
	signal \194\ : std_logic;
	signal \214\ : std_logic;
	signal \219\ : std_logic;
	signal \213\ : std_logic;
	signal \221\ : std_logic;
	signal \217\ : std_logic;
	signal \215\ : std_logic;
	signal \220\ : std_logic;
	signal \222\ : std_logic;
	signal \4\ : std_logic;
	signal \216\ : std_logic;
	signal \218\ : std_logic;
	signal \229\ : std_logic;
	signal \230\ : std_logic;
	signal \284\ : std_logic;
	signal \PLD32/bit3_1\ : std_logic;
	signal \PLD32/OUT2\ : std_logic;
	signal \298\ : std_logic;
	signal \243\ : std_logic;
	signal \292\ : std_logic;
	signal \PLD32/bit4_8\ : std_logic;
	signal \PLD32/bit1_1\ : std_logic;
	signal \274\ : std_logic;
	signal \PLD32/bit2_4\ : std_logic;
	signal \273\ : std_logic;
	signal \PLD32/bit4_4\ : std_logic;
	signal \201\ : std_logic;
	signal \291\ : std_logic;
	signal \289\ : std_logic;
	signal \299\ : std_logic;
	signal \PLD32/bit1_2\ : std_logic;
	signal \PLD32/OUT3\ : std_logic;
	signal \285\ : std_logic;
	signal \191\ : std_logic;
	signal \PLD32/IN2\ : std_logic;
	signal \184\ : std_logic;
	signal \293\ : std_logic;
	signal \PLD32/bit2_2\ : std_logic;
	signal \PLD32/bit3_4\ : std_logic;
	signal \290\ : std_logic;
	signal \286\ : std_logic;
	signal \PLD32/IN1\ : std_logic;
	signal \PLD32/bit3_2\ : std_logic;
	signal \PLD32/bit2_1\ : std_logic;
	signal \268\ : std_logic;
	signal \PLD32/OUT4\ : std_logic;
	signal \259\ : std_logic;
	signal \PLD32/bit3_8\ : std_logic;
	signal \186\ : std_logic;
	signal \248\ : std_logic;
	signal \PLD32/bit4_1\ : std_logic;
	signal \297\ : std_logic;
	signal \PLD32/bit2_8\ : std_logic;
	signal \249\ : std_logic;
	signal \PLD32/bit1_8\ : std_logic;
	signal \PLD32/OUT1\ : std_logic;
	signal \PLD32/bit4_2\ : std_logic;
	signal \282\ : std_logic;
	signal \280\ : std_logic;
	signal \PLD32/bit1_4\ : std_logic;
	signal \253\ : std_logic;
	signal \195\ : std_logic;
	signal \263\ : std_logic;
	signal \256\ : std_logic;
	signal \296\ : std_logic;
	signal \252\ : std_logic;
	signal \251\ : std_logic;
	signal \196\ : std_logic;
	signal \261\ : std_logic;
	signal \262\ : std_logic;
	signal \260\ : std_logic;
	signal \203\ : std_logic;
	signal \202\ : std_logic;
	signal \161\ : std_logic;
	signal \239\ : std_logic;
	signal \PLD24/Write_EN_Col\ : std_logic;
	signal \PLD37/R_r2c2_9\ : std_logic;
	signal \PLD37/R_r2c2_6\ : std_logic;
	signal \PLD37/R_r2c2_1\ : std_logic;
	signal \PLD37/reset_en\ : std_logic;
	signal \PLD37/R_r2c3_1\ : std_logic;
	signal \PLD37/R_r1c3_3\ : std_logic;
	signal \269\ : std_logic;
	signal \PLD37/R_r2c1_1\ : std_logic;
	signal \PLD37/R_r2c1_9\ : std_logic;
	signal \PLD27/Write_EN_Col\ : std_logic;
	signal \PLD37/R_r2c3_6\ : std_logic;
	signal \PLD37/R_r1c1_4\ : std_logic;
	signal \PLD37/R_r1c3_6\ : std_logic;
	signal \PLD37/R_r2c2_4\ : std_logic;
	signal \PLD37/R_r1c1_6\ : std_logic;
	signal \PLD37/R_r2c1_2\ : std_logic;
	signal \PLD37/R_r2c3_5\ : std_logic;
	signal \PLD37/R_r1c2_2\ : std_logic;
	signal \PLD37/R_r1c1_10\ : std_logic;
	signal \PLD37/R_r1c3_1\ : std_logic;
	signal \PLD37/R_r1c2_10\ : std_logic;
	signal \PLD24/Read_EN_Row\ : std_logic;
	signal \PLD37/R_r1c1_7\ : std_logic;
	signal \PLD37/R_r1c2_12\ : std_logic;
	signal \PLD15/Write_EN_Row\ : std_logic;
	signal \PLD37/R_r1c2_8\ : std_logic;
	signal \PLD37/R_r1c1_12\ : std_logic;
	signal \PLD37/R_r1c2_5\ : std_logic;
	signal \242\ : std_logic;
	signal \PLD37/R_r1c2_9\ : std_logic;
	signal \PLD37/R_r2c2_7\ : std_logic;
	signal \PLD37/R_r2c2_11\ : std_logic;
	signal \PLD37/R_r1c2_1\ : std_logic;
	signal \PLD37/R_r2c2_5\ : std_logic;
	signal \PLD37/R_r1c2_4\ : std_logic;
	signal \PLD37/R_r2c1_5\ : std_logic;
	signal \PLD37/R_r1c1_11\ : std_logic;
	signal \PLD37/R_r1c1_1\ : std_logic;
	signal \225\ : std_logic;
	signal \238\ : std_logic;
	signal \212\ : std_logic;
	signal \PLD37/R_r1c3_9\ : std_logic;
	signal \PLD37/R_r2c1_4\ : std_logic;
	signal \PLD37/R_r1c3_5\ : std_logic;
	signal \PLD37/R_r2c3_11\ : std_logic;
	signal \PLD37/R_r2c1_3\ : std_logic;
	signal \PLD37/R_r2c3_10\ : std_logic;
	signal \PLD37/R_r1c3_4\ : std_logic;
	signal \PLD37/R_r2c3_8\ : std_logic;
	signal \PLD37/R_r2c2_3\ : std_logic;
	signal \PLD37/R_r1c1_2\ : std_logic;
	signal \PLD37/R_r2c1_12\ : std_logic;
	signal \224\ : std_logic;
	signal \270\ : std_logic;
	signal \PLD37/R_r2c2_12\ : std_logic;
	signal \PLD37/R_r2c3_7\ : std_logic;
	signal \PLD37/R_r1c1_5\ : std_logic;
	signal \PLD37/R_r2c3_9\ : std_logic;
	signal \PLD37/R_r1c3_11\ : std_logic;
	signal \PLD37/R_r2c3_3\ : std_logic;
	signal \PLD24/Write_EN_Row\ : std_logic;
	signal \PLD37/R_r1c3_2\ : std_logic;
	signal \255\ : std_logic;
	signal \PLD37/R_r2c2_8\ : std_logic;
	signal \240\ : std_logic;
	signal \PLD15/Read_EN_Row\ : std_logic;
	signal \PLD37/R_r2c1_10\ : std_logic;
	signal \PLD37/R_r1c1_3\ : std_logic;
	signal \257\ : std_logic;
	signal \267\ : std_logic;
	signal \PLD26/Write_EN_Col\ : std_logic;
	signal \264\ : std_logic;
	signal \PLD37/R_r1c3_7\ : std_logic;
	signal \PLD37/R_r2c1_6\ : std_logic;
	signal \PLD22/Read_EN_Col\ : std_logic;
	signal \PLD37/R_r1c2_7\ : std_logic;
	signal \241\ : std_logic;
	signal \PLD37/R_r2c3_2\ : std_logic;
	signal \PLD37/R_r2c1_11\ : std_logic;
	signal \PLD37/R_r1c3_10\ : std_logic;
	signal \PLD37/R_r2c3_4\ : std_logic;
	signal \PLD37/R_r2c1_7\ : std_logic;
	signal \PLD37/R_r1c2_3\ : std_logic;
	signal \PLD37/R_r1c1_9\ : std_logic;
	signal \PLD37/R_r2c2_2\ : std_logic;
	signal \266\ : std_logic;
	signal \254\ : std_logic;
	signal \PLD15/Read_EN_Col\ : std_logic;
	signal \231\ : std_logic;
	signal \PLD23/Read_EN_Col\ : std_logic;
	signal \235\ : std_logic;
	signal \PLD37/R_r1c2_11\ : std_logic;
	signal \PLD37/R_r2c3_12\ : std_logic;
	signal \232\ : std_logic;
	signal \PLD37/R_r1c3_12\ : std_logic;
	signal \PLD37/R_r1c2_6\ : std_logic;
	signal \PLD37/R_r2c2_10\ : std_logic;
	signal \PLD37/R_r1c3_8\ : std_logic;
	signal \223\ : std_logic;
	signal \236\ : std_logic;
	signal \237\ : std_logic;
	signal \PLD37/R_r2c1_8\ : std_logic;
	signal \226\ : std_logic;
	signal \PLD37/R_r1c1_8\ : std_logic;
	signal \228\ : std_logic;
	signal \233\ : std_logic;
	signal \234\ : std_logic;
	signal \227\ : std_logic;
	signal \14\ : std_logic;
	signal \380\ : std_logic;
	signal \373\ : std_logic;
	signal \381\ : std_logic;
	signal \349\ : std_logic;
	signal \369\ : std_logic;
	signal \382\ : std_logic;
	signal \345\ : std_logic;
	signal \338\ : std_logic;
	signal \362\ : std_logic;
	signal \352\ : std_logic;
	signal \366\ : std_logic;
	signal \351\ : std_logic;
	signal \357\ : std_logic;
	signal \374\ : std_logic;
	signal \342\ : std_logic;
	signal \343\ : std_logic;
	signal \367\ : std_logic;
	signal \339\ : std_logic;
	signal \365\ : std_logic;
	signal \358\ : std_logic;
	signal \378\ : std_logic;
	signal \359\ : std_logic;
	signal \341\ : std_logic;
	signal \364\ : std_logic;
	signal \363\ : std_logic;
	signal \20\ : std_logic;
	signal \8\ : std_logic;
	signal \353\ : std_logic;
	signal \355\ : std_logic;
	signal \348\ : std_logic;
	signal \370\ : std_logic;
	signal \371\ : std_logic;
	signal \26\ : std_logic;
	signal \346\ : std_logic;
	signal \376\ : std_logic;
	signal \350\ : std_logic;
	signal \356\ : std_logic;
	signal \360\ : std_logic;
	signal \372\ : std_logic;
	signal \354\ : std_logic;
	signal \347\ : std_logic;
	signal \379\ : std_logic;
	signal \377\ : std_logic;
	signal \340\ : std_logic;
	signal \32\ : std_logic;
	signal \368\ : std_logic;
	signal \344\ : std_logic;
	signal \361\ : std_logic;
	signal \375\ : std_logic;
	signal \15\ : std_logic;
	signal \461\ : std_logic;
	signal \423\ : std_logic;
	signal \462\ : std_logic;
	signal \394\ : std_logic;
	signal \419\ : std_logic;
	signal \463\ : std_logic;
	signal \390\ : std_logic;
	signal \383\ : std_logic;
	signal \407\ : std_logic;
	signal \397\ : std_logic;
	signal \411\ : std_logic;
	signal \396\ : std_logic;
	signal \402\ : std_logic;
	signal \424\ : std_logic;
	signal \387\ : std_logic;
	signal \388\ : std_logic;
	signal \417\ : std_logic;
	signal \384\ : std_logic;
	signal \410\ : std_logic;
	signal \403\ : std_logic;
	signal \459\ : std_logic;
	signal \404\ : std_logic;
	signal \386\ : std_logic;
	signal \409\ : std_logic;
	signal \408\ : std_logic;
	signal \21\ : std_logic;
	signal \9\ : std_logic;
	signal \398\ : std_logic;
	signal \400\ : std_logic;
	signal \393\ : std_logic;
	signal \420\ : std_logic;
	signal \421\ : std_logic;
	signal \27\ : std_logic;
	signal \391\ : std_logic;
	signal \426\ : std_logic;
	signal \395\ : std_logic;
	signal \401\ : std_logic;
	signal \405\ : std_logic;
	signal \422\ : std_logic;
	signal \399\ : std_logic;
	signal \392\ : std_logic;
	signal \460\ : std_logic;
	signal \458\ : std_logic;
	signal \385\ : std_logic;
	signal \33\ : std_logic;
	signal \418\ : std_logic;
	signal \389\ : std_logic;
	signal \406\ : std_logic;
	signal \425\ : std_logic;
	signal \13\ : std_logic;
	signal \334\ : std_logic;
	signal \327\ : std_logic;
	signal \335\ : std_logic;
	signal \300\ : std_logic;
	signal \323\ : std_logic;
	signal \336\ : std_logic;
	signal \281\ : std_logic;
	signal \271\ : std_logic;
	signal \316\ : std_logic;
	signal \303\ : std_logic;
	signal \320\ : std_logic;
	signal \302\ : std_logic;
	signal \308\ : std_logic;
	signal \328\ : std_logic;
	signal \277\ : std_logic;
	signal \278\ : std_logic;
	signal \321\ : std_logic;
	signal \272\ : std_logic;
	signal \319\ : std_logic;
	signal \309\ : std_logic;
	signal \332\ : std_logic;
	signal \310\ : std_logic;
	signal \276\ : std_logic;
	signal \318\ : std_logic;
	signal \317\ : std_logic;
	signal \19\ : std_logic;
	signal \7\ : std_logic;
	signal \304\ : std_logic;
	signal \306\ : std_logic;
	signal \295\ : std_logic;
	signal \324\ : std_logic;
	signal \325\ : std_logic;
	signal \25\ : std_logic;
	signal \283\ : std_logic;
	signal \330\ : std_logic;
	signal \301\ : std_logic;
	signal \307\ : std_logic;
	signal \311\ : std_logic;
	signal \326\ : std_logic;
	signal \305\ : std_logic;
	signal \294\ : std_logic;
	signal \333\ : std_logic;
	signal \331\ : std_logic;
	signal \275\ : std_logic;
	signal \31\ : std_logic;
	signal \322\ : std_logic;
	signal \279\ : std_logic;
	signal \313\ : std_logic;
	signal \329\ : std_logic;
	signal \17\ : std_logic;
	signal \551\ : std_logic;
	signal \544\ : std_logic;
	signal \552\ : std_logic;
	signal \520\ : std_logic;
	signal \540\ : std_logic;
	signal \553\ : std_logic;
	signal \516\ : std_logic;
	signal \509\ : std_logic;
	signal \533\ : std_logic;
	signal \523\ : std_logic;
	signal \537\ : std_logic;
	signal \522\ : std_logic;
	signal \528\ : std_logic;
	signal \545\ : std_logic;
	signal \513\ : std_logic;
	signal \514\ : std_logic;
	signal \538\ : std_logic;
	signal \510\ : std_logic;
	signal \536\ : std_logic;
	signal \529\ : std_logic;
	signal \549\ : std_logic;
	signal \530\ : std_logic;
	signal \512\ : std_logic;
	signal \535\ : std_logic;
	signal \534\ : std_logic;
	signal \23\ : std_logic;
	signal \11\ : std_logic;
	signal \524\ : std_logic;
	signal \526\ : std_logic;
	signal \519\ : std_logic;
	signal \541\ : std_logic;
	signal \542\ : std_logic;
	signal \29\ : std_logic;
	signal \517\ : std_logic;
	signal \547\ : std_logic;
	signal \521\ : std_logic;
	signal \527\ : std_logic;
	signal \531\ : std_logic;
	signal \543\ : std_logic;
	signal \525\ : std_logic;
	signal \518\ : std_logic;
	signal \550\ : std_logic;
	signal \548\ : std_logic;
	signal \511\ : std_logic;
	signal \35\ : std_logic;
	signal \539\ : std_logic;
	signal \515\ : std_logic;
	signal \532\ : std_logic;
	signal \546\ : std_logic;
	signal \16\ : std_logic;
	signal \506\ : std_logic;
	signal \499\ : std_logic;
	signal \507\ : std_logic;
	signal \475\ : std_logic;
	signal \495\ : std_logic;
	signal \508\ : std_logic;
	signal \471\ : std_logic;
	signal \464\ : std_logic;
	signal \488\ : std_logic;
	signal \478\ : std_logic;
	signal \492\ : std_logic;
	signal \477\ : std_logic;
	signal \483\ : std_logic;
	signal \500\ : std_logic;
	signal \468\ : std_logic;
	signal \469\ : std_logic;
	signal \493\ : std_logic;
	signal \465\ : std_logic;
	signal \491\ : std_logic;
	signal \484\ : std_logic;
	signal \504\ : std_logic;
	signal \485\ : std_logic;
	signal \467\ : std_logic;
	signal \490\ : std_logic;
	signal \489\ : std_logic;
	signal \22\ : std_logic;
	signal \10\ : std_logic;
	signal \479\ : std_logic;
	signal \481\ : std_logic;
	signal \474\ : std_logic;
	signal \496\ : std_logic;
	signal \497\ : std_logic;
	signal \28\ : std_logic;
	signal \472\ : std_logic;
	signal \502\ : std_logic;
	signal \476\ : std_logic;
	signal \482\ : std_logic;
	signal \486\ : std_logic;
	signal \498\ : std_logic;
	signal \480\ : std_logic;
	signal \473\ : std_logic;
	signal \505\ : std_logic;
	signal \503\ : std_logic;
	signal \466\ : std_logic;
	signal \34\ : std_logic;
	signal \494\ : std_logic;
	signal \470\ : std_logic;
	signal \487\ : std_logic;
	signal \501\ : std_logic;
	signal \18\ : std_logic;
	signal \596\ : std_logic;
	signal \589\ : std_logic;
	signal \597\ : std_logic;
	signal \565\ : std_logic;
	signal \585\ : std_logic;
	signal \598\ : std_logic;
	signal \561\ : std_logic;
	signal \554\ : std_logic;
	signal \578\ : std_logic;
	signal \568\ : std_logic;
	signal \582\ : std_logic;
	signal \567\ : std_logic;
	signal \573\ : std_logic;
	signal \590\ : std_logic;
	signal \558\ : std_logic;
	signal \559\ : std_logic;
	signal \583\ : std_logic;
	signal \555\ : std_logic;
	signal \581\ : std_logic;
	signal \574\ : std_logic;
	signal \594\ : std_logic;
	signal \575\ : std_logic;
	signal \557\ : std_logic;
	signal \580\ : std_logic;
	signal \579\ : std_logic;
	signal \24\ : std_logic;
	signal \12\ : std_logic;
	signal \569\ : std_logic;
	signal \571\ : std_logic;
	signal \564\ : std_logic;
	signal \586\ : std_logic;
	signal \587\ : std_logic;
	signal \30\ : std_logic;
	signal \562\ : std_logic;
	signal \592\ : std_logic;
	signal \566\ : std_logic;
	signal \572\ : std_logic;
	signal \576\ : std_logic;
	signal \588\ : std_logic;
	signal \570\ : std_logic;
	signal \563\ : std_logic;
	signal \595\ : std_logic;
	signal \593\ : std_logic;
	signal \556\ : std_logic;
	signal \36\ : std_logic;
	signal \584\ : std_logic;
	signal \560\ : std_logic;
	signal \577\ : std_logic;
	signal \591\ : std_logic;
	signal \PLD4/I9\ : std_logic;
	signal \PLD4/I8\ : std_logic;
	signal \PLD4/I5\ : std_logic;
	signal \PLD4/I7\ : std_logic;
	signal \PLD4/I6\ : std_logic;
	signal \PLD3/O1\ : std_logic;
	signal \PLD4/I2\ : std_logic;
	signal \46\ : std_logic;
	signal \PLD4/I4\ : std_logic;
	signal \PLD2/CLR\ : std_logic;
	signal \PLD4/I3\ : std_logic;
	signal \PLD4/I0\ : std_logic;
	signal \PLD4/I1\ : std_logic;
	signal \PLD6/O1\ : std_logic;
	signal \PLD5/O1\ : std_logic;
	signal \PLD4/O1\ : std_logic;
	signal \68\ : std_logic;
	signal \69\ : std_logic;
	signal \71\ : std_logic;
	signal \70\ : std_logic;
	signal \92\ : std_logic;
	signal \91\ : std_logic;
	signal \38\ : std_logic;
	signal \41\ : std_logic;
	signal \40\ : std_logic;
	signal \39\ : std_logic;
	signal \37\ : std_logic;
	signal \PLD9/I5\ : std_logic;
	signal \PLD9/I9\ : std_logic;
	signal \PLD9/I8\ : std_logic;
	signal \PLD9/I2\ : std_logic;
	signal \PLD9/I7\ : std_logic;
	signal \PLD9/I1\ : std_logic;
	signal \PLD9/O1\ : std_logic;
	signal \PLD9/I3\ : std_logic;
	signal \PLD9/I4\ : std_logic;
	signal \PLD9/I0\ : std_logic;
	signal \PLD9/I6\ : std_logic;
	signal \42\ : std_logic;
	signal \PLD8/CLR\ : std_logic;
	signal \PLD12/O1\ : std_logic;
	signal \PLD10/O1\ : std_logic;
	signal \PLD11/O1\ : std_logic;
	signal \47\ : std_logic;
	signal \44\ : std_logic;
	signal \43\ : std_logic;
	signal \45\ : std_logic;
	signal \48\ : std_logic;
	signal \49\ : std_logic;
	signal \51\ : std_logic;
	signal \50\ : std_logic;
	signal \52\ : std_logic;
	signal \53\ : std_logic;
	signal \55\ : std_logic;
	signal \58\ : std_logic;
	signal \57\ : std_logic;
	signal \56\ : std_logic;
	signal \54\ : std_logic;
	signal \60\ : std_logic;
	signal \61\ : std_logic;
	signal \PLD13/Vsync\ : std_logic;
begin
	B0_AUTOBUF : AUTO_OBUF
		port map( I => \PLD16/Q9\, O => B0 );
	B1_AUTOBUF : AUTO_OBUF
		port map( I => \PLD16/Q10\, O => B1 );
	B2_AUTOBUF : AUTO_OBUF
		port map( I => \PLD16/Q11\, O => B2 );
	B3_AUTOBUF : AUTO_OBUF
		port map( I => \PLD16/Q12\, O => B3 );
	G0_AUTOBUF : AUTO_OBUF
		port map( I => \PLD16/Q5\, O => G0 );
	G1_AUTOBUF : AUTO_OBUF
		port map( I => \PLD16/Q6\, O => G1 );
	G2_AUTOBUF : AUTO_OBUF
		port map( I => \PLD16/Q7\, O => G2 );
	G3_AUTOBUF : AUTO_OBUF
		port map( I => \PLD16/Q8\, O => G3 );
	R0_AUTOBUF : AUTO_OBUF
		port map( I => \PLD16/Q1\, O => R0 );
	R1_AUTOBUF : AUTO_OBUF
		port map( I => \PLD16/Q2\, O => R1 );
	R2_AUTOBUF : AUTO_OBUF
		port map( I => \PLD16/Q3\, O => R2 );
	R3_AUTOBUF : AUTO_OBUF
		port map( I => \PLD16/Q4\, O => R3 );
	btnC_AUTOBUF : AUTO_IBUF
		port map( I => btnC, O => \PLD37/WRITE_CLOCK\ );
	btnD_AUTOBUF : AUTO_IBUF
		port map( I => btnD, O => \PLD25/Down\ );
	btnL_AUTOBUF : AUTO_IBUF
		port map( I => btnL, O => \PLD25/Left\ );
	btnR_AUTOBUF : AUTO_IBUF
		port map( I => btnR, O => \PLD25/Right\ );
	btnU_AUTOBUF : AUTO_IBUF
		port map( I => btnU, O => \PLD25/Up\ );
	SW0_AUTOBUF : AUTO_IBUF
		port map( I => SW0, O => \PLD37/W_1\ );
	SW1_AUTOBUF : AUTO_IBUF
		port map( I => SW1, O => \PLD37/W_2\ );
	SW2_AUTOBUF : AUTO_IBUF
		port map( I => SW2, O => \PLD37/W_3\ );
	SW3_AUTOBUF : AUTO_IBUF
		port map( I => SW3, O => \PLD37/W_4\ );
	SW4_AUTOBUF : AUTO_IBUF
		port map( I => SW4, O => \PLD37/W_5\ );
	SW5_AUTOBUF : AUTO_IBUF
		port map( I => SW5, O => \PLD37/W_6\ );
	SW6_AUTOBUF : AUTO_IBUF
		port map( I => SW6, O => \PLD37/W_7\ );
	SW7_AUTOBUF : AUTO_IBUF
		port map( I => SW7, O => \PLD37/W_8\ );
	SW8_AUTOBUF : AUTO_IBUF
		port map( I => SW8, O => \PLD37/W_9\ );
	SW9_AUTOBUF : AUTO_IBUF
		port map( I => SW9, O => \PLD37/W_10\ );
	SW10_AUTOBUF : AUTO_IBUF
		port map( I => SW10, O => \PLD37/W_11\ );
	SW11_AUTOBUF : AUTO_IBUF
		port map( I => SW11, O => \PLD37/W_12\ );
	Hsync_AUTOBUF : AUTO_OBUF
		port map( I => \PLD13/Hsync\, O => Hsync );
	Vsync_AUTOBUF : AUTO_OBUF
		port map( I => \PLD13/Vsync\, O => Vsync );
	CLK_AUTOBUF : AUTO_IBUF
		port map( I => CLK, O => \PLD1/clk_100MHz\ );
	CA_AUTOBUF : AUTO_OBUF
		port map( I => \PLD33/CA\, O => CA );
	CB_AUTOBUF : AUTO_OBUF
		port map( I => \PLD33/CB\, O => CB );
	CC_AUTOBUF : AUTO_OBUF
		port map( I => \PLD33/CC\, O => CC );
	CD_AUTOBUF : AUTO_OBUF
		port map( I => \PLD33/CD\, O => CD );
	CE_AUTOBUF : AUTO_OBUF
		port map( I => \PLD33/CE\, O => CE );
	CF_AUTOBUF : AUTO_OBUF
		port map( I => \PLD33/CF\, O => CF );
	CG_AUTOBUF : AUTO_OBUF
		port map( I => \PLD33/CG\, O => CG );
	AN0_AUTOBUF : AUTO_OBUF
		port map( I => \PLD33/AN0\, O => AN0 );
	AN1_AUTOBUF : AUTO_OBUF
		port map( I => \PLD33/AN1\, O => AN1 );
	AN2_AUTOBUF : AUTO_OBUF
		port map( I => \PLD33/AN2\, O => AN2 );
	AN3_AUTOBUF : AUTO_OBUF
		port map( I => \PLD33/AN3\, O => AN3 );
	LED0_AUTOBUF : AUTO_OBUF
		port map( I => \PLD14/LED0\, O => LED0 );
	LED1_AUTOBUF : AUTO_OBUF
		port map( I => \PLD14/LED0\, O => LED1 );
	LED2_AUTOBUF : AUTO_OBUF
		port map( I => \PLD14/LED0\, O => LED2 );
	LED3_AUTOBUF : AUTO_OBUF
		port map( I => \PLD14/LED3\, O => LED3 );
	LED4_AUTOBUF : AUTO_OBUF
		port map( I => \PLD14/LED4\, O => LED4 );
	LED5_AUTOBUF : AUTO_OBUF
		port map( I => \PLD14/LED5\, O => LED5 );
	LED6_AUTOBUF : AUTO_OBUF
		port map( I => \PLD14/LED6\, O => LED6 );
	LED7_AUTOBUF : AUTO_OBUF
		port map( I => \PLD14/LED0\, O => LED7 );
	LED8_AUTOBUF : AUTO_OBUF
		port map( I => \PLD14/LED8\, O => LED8 );
	dp_AUTOBUF : AUTO_OBUF
		port map( I => \PLD33/dp\, O => dp );
	U287 : AND2_NI
		port map( A => \PLD21/VBLANK\, B => \PLD21/HBLANK\, Y => \PLD37/Read_EN\ );
	U288 : NAND2_NI
		port map( A => \PLD37/Write_Read_Equal\, B => \PLD1/CLOCK_C_05Hz\, Y => \PLD16/Flashing\ );
	U127 : INV_NI
		port map( Y => \PLD18/CLR\, A => \PLD21/HBLANK\ );
	U128 : INV_NI
		port map( Y => \PLD17/CLR\, A => \PLD21/VBLANK\ );
	U267 : CNTR_4BIN_SU_D_NI
		port map( A => \180\, B => \181\, C => \182\, D => \183\, UD => \PLD25/Left\, QA => \PLD33/Column_bit_1\, QB => \PLD33/Column_bit_2\, QC => \287\, QD => \288\, CTEN => \183\, LOAD => \185\, RCO => open, MAXMIN => \205\, CLK => \5\ );
	U268 : CNTR_4BIN_SU_D_NI
		port map( A => \187\, B => \188\, C => \189\, D => \183\, UD => \PLD25/Up\, QA => \PLD37/Write_row_bit1\, QB => \PLD14/Row_bit_2\, QC => \245\, QD => \258\, CTEN => \183\, LOAD => \190\, RCO => open, MAXMIN => \3\, CLK => \6\ );
	U269 : OR2_NI
		port map( A => \PLD25/Left\, B => \PLD25/Right\, Y => \2\ );
	U270 : ENC8_3_NI
		port map( A0 => \192\, A1 => \193\, A2 => \194\, GS => open, I3 => \197\, I4 => \197\, I5 => \197\, I2 => \244\, I1 => \197\, I0 => \312\, I7 => \197\, I6 => \197\, EI => \183\, EO => open );
	U271 : INV_NI
		port map( Y => \180\, A => \192\ );
	U272 : INV_NI
		port map( Y => \181\, A => \193\ );
	U273 : INV_NI
		port map( Y => \182\, A => \194\ );
	U274 : OR2_NI
		port map( A => \PLD25/Up\, B => \PLD25/Down\, Y => \247\ );
	U275 : ENC8_3_NI
		port map( A0 => \198\, A1 => \199\, A2 => \200\, GS => open, I3 => \197\, I4 => \197\, I5 => \197\, I2 => \197\, I1 => \337\, I0 => \250\, I7 => \197\, I6 => \197\, EI => \183\, EO => open );
	U276 : INV_NI
		port map( Y => \187\, A => \198\ );
	U277 : INV_NI
		port map( Y => \188\, A => \199\ );
	U278 : INV_NI
		port map( Y => \189\, A => \200\ );
	U279 : DIGITAL_LOW_NI
		port map( Y => \183\ );
	U280 : AND2_NI
		port map( A => \244\, B => \312\, Y => \185\ );
	U281 : AND2_NI
		port map( A => \250\, B => \337\, Y => \190\ );
	U286 : DIGITAL_HIGH_NI
		port map( Y => \197\ );
	U434 : NAND4_NI
		port map( A => \PLD33/Column_bit_1\, B => \PLD33/Column_bit_2\, C => \314\, D => \315\, Y => \312\ );
	U437 : INV_NI
		port map( Y => \314\, A => \287\ );
	U438 : INV_NI
		port map( Y => \315\, A => \288\ );
	U443 : OR4_NI
		port map( A => \PLD37/Write_row_bit1\, B => \246\, Y => \337\, C => \245\, D => \258\ );
	U89 : INV_NI
		port map( Y => \246\, A => \PLD14/Row_bit_2\ );
	U90 : NAND5_NI
		port map( A => \211\, B => \258\, C => \245\, D => \PLD14/Row_bit_2\, Y => \250\, E => \PLD37/Write_row_bit1\ );
	U91 : OR5_NI
		port map( A => \288\, B => \287\, Y => \244\, C => \PLD33/Column_bit_2\, D => \PLD33/Column_bit_1\, E => \204\ );
	U92 : INV_NI
		port map( Y => \204\, A => \205\ );
	U150 : INV_NI
		port map( Y => \211\, A => \3\ );
	U125 : FF_D_CO_NI
		port map( D => \247\, Q => \6\, CLK => \PLD25/CLK_FF\, Qneg => open );
	U124 : FF_D_CO_NI
		port map( D => \2\, Q => \5\, CLK => \PLD25/CLK_FF\, Qneg => open );
	\4div\ : CNTR_4BIN_S_NI
		port map( QA => open, QB => \PLD1/CLOCK_A_25MHz\, QC => open, QD => open, RCO => open, A => \213\, B => \213\, C => \213\, D => \213\, ENP => \214\, ENT => \214\, LOAD => \214\, CLR => \214\, CLK => \PLD1/clk_100MHz\ );
	\10div_1\ : CNTR_BCD_S_NI
		port map( QA => open, QB => open, QC => open, QD => open, RCO => \215\, A => \213\, B => \213\, C => \213\, D => \213\, ENP => \214\, ENT => \214\, LOAD => \214\, CLR => \214\, CLK => \PLD1/clk_100MHz\ );
	\10div_2\ : CNTR_BCD_S_NI
		port map( QA => open, QB => open, QC => open, QD => open, RCO => \216\, A => \213\, B => \213\, C => \213\, D => \213\, ENP => \214\, ENT => \214\, LOAD => \214\, CLR => \214\, CLK => \215\ );
	\10div_3\ : CNTR_BCD_S_NI
		port map( QA => open, QB => open, QC => open, QD => open, RCO => \217\, A => \213\, B => \213\, C => \213\, D => \213\, ENP => \214\, ENT => \214\, LOAD => \214\, CLR => \214\, CLK => \216\ );
	\10div_4\ : CNTR_BCD_S_NI
		port map( QA => open, QB => open, QC => open, QD => open, RCO => \218\, A => \213\, B => \213\, C => \213\, D => \213\, ENP => \214\, ENT => \214\, LOAD => \214\, CLR => \214\, CLK => \217\ );
	\10div_5\ : CNTR_BCD_S_NI
		port map( QA => open, QB => open, QC => open, QD => open, RCO => \219\, A => \213\, B => \213\, C => \213\, D => \213\, ENP => \214\, ENT => \214\, LOAD => \214\, CLR => \214\, CLK => \218\ );
	\10div_6\ : CNTR_BCD_S_NI
		port map( QA => open, QB => open, QC => open, QD => open, RCO => \220\, A => \213\, B => \213\, C => \213\, D => \213\, ENP => \214\, ENT => \214\, LOAD => \214\, CLR => \214\, CLK => \219\ );
	\10div_8\ : CNTR_BCD_S_NI
		port map( QA => open, QB => open, QC => open, QD => open, RCO => \221\, A => \213\, B => \213\, C => \213\, D => \213\, ENP => \214\, ENT => \214\, LOAD => \214\, CLR => \214\, CLK => \222\ );
	U1 : DIGITAL_HIGH_NI
		port map( Y => \214\ );
	\2div_1\ : FF_T_CLR_CO_NI
		port map( T => \214\, Q => \PLD37/CLK_FF_500Hz\, Qneg => open, CLR => \214\, CLK => \219\ );
	U2 : DIGITAL_LOW_NI
		port map( Y => \213\ );
	\2div_2\ : FF_T_CLR_CO_NI
		port map( T => \214\, Q => \PLD1/CLOCK_C_05Hz\, Qneg => open, CLR => \214\, CLK => \221\ );
	U3 : CNTR_BCD_S_NI
		port map( QA => open, QB => open, QC => open, QD => open, RCO => \222\, A => \213\, B => \213\, C => \213\, D => \213\, ENP => \214\, ENT => \214\, LOAD => \214\, CLR => \214\, CLK => \220\ );
	U121 : FF_D_CO_NI
		port map( D => \1\, Q => \4\, CLK => \PLD1/CLOCK_C_05Hz\, Qneg => \1\ );
	U123 : XOR2_NI
		port map( A => \4\, B => \PLD1/CLOCK_C_05Hz\, Y => \PLD37/CLOCK_1Hz\ );
	U168 : FF_T_CLR_CO_NI
		port map( T => \214\, Q => \PLD25/CLK_FF\, Qneg => open, CLR => \214\, CLK => \220\ );
	U27 : DEC2_4_NI
		port map( Y0 => \229\, Y1 => \230\, Y2 => open, Y3 => open, A => \PLD37/Write_row_bit1\, B => \PLD14/Row_bit_2\, EN => \284\ );
	U28 : INV_NI
		port map( Y => \PLD14/LED4\, A => \229\ );
	U29 : INV_NI
		port map( Y => \PLD14/LED8\, A => \230\ );
	U30 : OR2_NI
		port map( A => \PLD14/LED4\, B => \PLD14/LED8\, Y => \PLD14/LED3\ );
	U31 : OR2_NI
		port map( A => \PLD14/LED4\, B => \PLD14/LED8\, Y => \PLD14/LED5\ );
	U32 : OR2_NI
		port map( A => \PLD14/LED4\, B => \PLD14/LED8\, Y => \PLD14/LED6\ );
	U33 : DIGITAL_LOW_NI
		port map( Y => \PLD14/LED0\ );
	U34 : DIGITAL_LOW_NI
		port map( Y => \284\ );
	U35 : CNTR_BCD_S_NI
		port map( QA => \PLD32/IN1\, QB => \PLD32/IN2\, QC => open, QD => open, RCO => open, A => \285\, B => \285\, C => \285\, D => \285\, ENP => \286\, ENT => \286\, LOAD => \286\, CLR => \286\, CLK => \PLD37/CLK_FF_500Hz\ );
	U36 : DEC2_4_NI
		port map( Y0 => \PLD33/AN0\, Y1 => \PLD33/AN1\, Y2 => \PLD33/AN2\, Y3 => \PLD33/AN3\, A => \PLD32/IN1\, B => \PLD32/IN2\, EN => \285\ );
	U37 : DIGITAL_HIGH_NI
		port map( Y => \273\ );
	U38 : DIGITAL_HIGH_NI
		port map( Y => \286\ );
	U39 : DIGITAL_LOW_NI
		port map( Y => \285\ );
	U40 : DEC_BCD_7_NI
		port map( A => \PLD32/OUT1\, B => \PLD32/OUT2\, C => \PLD32/OUT3\, D => \PLD32/OUT4\, Y0 => \PLD33/CA\, Y3 => \PLD33/CD\, Y4 => \PLD33/CE\, Y5 => \PLD33/CF\, Y2 => \PLD33/CC\, Y1 => \PLD33/CB\, Y6 => \PLD33/CG\, LT => \273\, RBI => \273\, BI => \273\ );
	U41 : DEC2_4_NI
		port map( Y0 => \274\, Y1 => \289\, Y2 => \290\, Y3 => open, A => \PLD33/Column_bit_1\, B => \PLD33/Column_bit_2\, EN => \259\ );
	U42 : ENC10_4_NI
		port map( A => \260\, B => \261\, C => \262\, D => \263\, I3 => \243\, I4 => \243\, I5 => \268\, I2 => \243\, I1 => \243\, I8 => \243\, I7 => \243\, I6 => \243\, I9 => \243\ );
	U43 : ENC10_4_NI
		port map( A => \282\, B => \253\, C => \280\, D => \252\, I3 => \243\, I4 => \243\, I5 => \243\, I2 => \248\, I1 => \243\, I8 => \243\, I7 => \243\, I6 => \249\, I9 => \256\ );
	U44 : ENC10_4_NI
		port map( A => \251\, B => \296\, C => \297\, D => \298\, I3 => \299\, I4 => \243\, I5 => \291\, I2 => \243\, I1 => \292\, I8 => \243\, I7 => \243\, I6 => \243\, I9 => \243\ );
	U45 : ENC10_4_NI
		port map( A => \293\, B => \184\, C => \186\, D => \191\, I3 => \195\, I4 => \243\, I5 => \243\, I2 => \243\, I1 => \196\, I8 => \243\, I7 => \243\, I6 => \243\, I9 => \243\ );
	U46 : INV_NI
		port map( Y => \PLD32/bit1_1\, A => \260\ );
	U47 : INV_NI
		port map( Y => \PLD32/bit1_2\, A => \261\ );
	U48 : INV_NI
		port map( Y => \PLD32/bit1_4\, A => \262\ );
	U49 : INV_NI
		port map( Y => \PLD32/bit1_8\, A => \263\ );
	U50 : INV_NI
		port map( Y => \PLD32/bit2_1\, A => \282\ );
	U51 : INV_NI
		port map( Y => \PLD32/bit2_2\, A => \253\ );
	U93 : INV_NI
		port map( Y => \PLD32/bit2_4\, A => \280\ );
	U94 : INV_NI
		port map( Y => \PLD32/bit2_8\, A => \252\ );
	U95 : INV_NI
		port map( Y => \PLD32/bit3_1\, A => \293\ );
	U96 : INV_NI
		port map( Y => \PLD32/bit3_2\, A => \184\ );
	U97 : INV_NI
		port map( Y => \PLD32/bit3_4\, A => \186\ );
	U98 : INV_NI
		port map( Y => \PLD32/bit3_8\, A => \191\ );
	U99 : INV_NI
		port map( Y => \PLD32/bit4_1\, A => \251\ );
	U100 : INV_NI
		port map( Y => \PLD32/bit4_2\, A => \296\ );
	U101 : INV_NI
		port map( Y => \PLD32/bit4_4\, A => \297\ );
	U102 : INV_NI
		port map( Y => \PLD32/bit4_8\, A => \298\ );
	U103 : DIGITAL_HIGH_NI
		port map( Y => \243\ );
	U104 : AND3_NI
		port map( A => \274\, B => \289\, C => \290\, Y => \201\ );
	U105 : AND2_NI
		port map( A => \243\, B => \201\, Y => \268\ );
	U106 : AND2_NI
		port map( A => \243\, B => \274\, Y => \249\ );
	U107 : AND2_NI
		port map( A => \243\, B => \274\, Y => \292\ );
	U108 : AND2_NI
		port map( A => \243\, B => \289\, Y => \256\ );
	U109 : AND2_NI
		port map( A => \243\, B => \289\, Y => \196\ );
	U110 : AND2_NI
		port map( A => \243\, B => \289\, Y => \299\ );
	U111 : AND2_NI
		port map( A => \243\, B => \290\, Y => \248\ );
	U112 : AND2_NI
		port map( A => \243\, B => \290\, Y => \195\ );
	U113 : AND2_NI
		port map( A => \243\, B => \290\, Y => \291\ );
	U114 : DIGITAL_LOW_NI
		port map( Y => \259\ );
	U122 : NAND2_NI
		port map( A => \PLD32/IN1\, B => \203\, Y => \PLD33/dp\ );
	U69 : INV_NI
		port map( Y => \203\, A => \PLD32/IN2\ );
	U71 : AND2_NI
		port map( A => \PLD37/Read_EN\, B => \PLD16/Flashing\, Y => \161\ );
	U72 : AND2_NI
		port map( A => \PLD37/Read12\, B => \161\, Y => \PLD16/Q12\ );
	U73 : AND2_NI
		port map( A => \PLD37/Read11\, B => \161\, Y => \PLD16/Q11\ );
	U74 : AND2_NI
		port map( A => \PLD37/Read10\, B => \161\, Y => \PLD16/Q10\ );
	U75 : AND2_NI
		port map( A => \PLD37/Read9\, B => \161\, Y => \PLD16/Q9\ );
	U76 : AND2_NI
		port map( A => \PLD37/Read8\, B => \161\, Y => \PLD16/Q8\ );
	U77 : AND2_NI
		port map( A => \PLD37/Read7\, B => \161\, Y => \PLD16/Q7\ );
	U78 : AND2_NI
		port map( A => \PLD37/Read6\, B => \161\, Y => \PLD16/Q6\ );
	U79 : AND2_NI
		port map( A => \PLD37/Read5\, B => \161\, Y => \PLD16/Q5\ );
	U80 : AND2_NI
		port map( A => \PLD37/Read4\, B => \161\, Y => \PLD16/Q4\ );
	U81 : AND2_NI
		port map( A => \PLD37/Read3\, B => \161\, Y => \PLD16/Q3\ );
	U85 : AND2_NI
		port map( A => \PLD37/Read2\, B => \161\, Y => \PLD16/Q2\ );
	U120 : AND2_NI
		port map( A => \PLD37/Read1\, B => \161\, Y => \PLD16/Q1\ );
	U151 : DEC2_4_NI
		port map( Y0 => \212\, Y1 => \223\, Y2 => \224\, Y3 => open, A => \PLD33/Column_bit_1\, B => \PLD33/Column_bit_2\, EN => \225\ );
	U284 : DEC2_4_NI
		port map( Y0 => \226\, Y1 => \227\, Y2 => \228\, Y3 => open, A => \PLD37/Column_bit_1\, B => \PLD37/Column_bit_2\, EN => \225\ );
	U285 : DIGITAL_LOW_NI
		port map( Y => \225\ );
	U289 : INV_NI
		port map( Y => \PLD26/Write_EN_Col\, A => \223\ );
	U290 : INV_NI
		port map( Y => \PLD24/Write_EN_Col\, A => \212\ );
	U291 : INV_NI
		port map( Y => \PLD15/Read_EN_Col\, A => \226\ );
	U292 : INV_NI
		port map( Y => \PLD22/Read_EN_Col\, A => \227\ );
	U293 : DEC2_4_NI
		port map( Y0 => \231\, Y1 => \232\, Y2 => open, Y3 => open, A => \PLD37/Write_row_bit1\, B => \PLD14/Row_bit_2\, EN => \225\ );
	U294 : DEC2_4_NI
		port map( Y0 => \233\, Y1 => \234\, Y2 => open, Y3 => open, A => \PLD37/Row_bit_1\, B => \PLD37/Read_row_bit2\, EN => \225\ );
	U295 : INV_NI
		port map( Y => \PLD27/Write_EN_Col\, A => \224\ );
	U296 : INV_NI
		port map( Y => \PLD23/Read_EN_Col\, A => \228\ );
	U297 : INV_NI
		port map( Y => \PLD24/Write_EN_Row\, A => \232\ );
	U298 : INV_NI
		port map( Y => \PLD15/Write_EN_Row\, A => \231\ );
	U299 : INV_NI
		port map( Y => \PLD15/Read_EN_Row\, A => \233\ );
	U300 : INV_NI
		port map( Y => \PLD24/Read_EN_Row\, A => \234\ );
	U415 : COMP_4_NI
		port map( A2 => \PLD33/Column_bit_2\, B2 => \PLD37/Column_bit_2\, A1 => \PLD37/Write_row_bit1\, B1 => \PLD37/Row_bit_1\, OAGTB => open, A0 => \PLD14/Row_bit_2\, B0 => \PLD37/Read_row_bit2\, A3 => \PLD33/Column_bit_1\, B3 => \PLD37/Column_bit_1\, OAEQB => \PLD37/Write_Read_Equal\, OALTB => open, AEQB => \235\, ALTB => \225\, AGTB => \225\ );
	U416 : DIGITAL_HIGH_NI
		port map( Y => \235\ );
	U417 : CNTR_4BIN_ASCLR_NI
		port map( QA => \236\, QB => open, QC => open, QD => \237\, RCO => open, A => \238\, B => \238\, C => \238\, D => \238\, ENP => \PLD37/WRITE_CLOCK\, ENT => \PLD37/WRITE_CLOCK\, LOAD => \PLD37/WRITE_CLOCK\, CLR => \PLD37/WRITE_CLOCK\, CLK => \PLD37/CLOCK_1Hz\ );
	U418 : AND2_NI
		port map( A => \236\, B => \237\, Y => \PLD37/reset_en\ );
	U419 : DIGITAL_LOW_NI
		port map( Y => \238\ );
	U420 : MUX8_1_NI
		port map( D0 => \PLD37/R_r1c1_1\, D1 => \PLD37/R_r1c2_1\, D2 => \PLD37/R_r1c3_1\, D3 => \239\, D4 => \PLD37/R_r2c1_1\, D5 => \PLD37/R_r2c2_1\, D6 => \PLD37/R_r2c3_1\, D7 => \239\, A => \PLD37/Column_bit_1\, C => \PLD37/Row_bit_1\, B => \PLD37/Column_bit_2\, Y => \PLD37/Read1\, G => \239\ );
	U421 : DIGITAL_LOW_NI
		port map( Y => \239\ );
	U422 : MUX8_1_NI
		port map( D0 => \PLD37/R_r1c1_2\, D1 => \PLD37/R_r1c2_2\, D2 => \PLD37/R_r1c3_2\, D3 => \240\, D4 => \PLD37/R_r2c1_2\, D5 => \PLD37/R_r2c2_2\, D6 => \PLD37/R_r2c3_2\, D7 => \240\, A => \PLD37/Column_bit_1\, C => \PLD37/Row_bit_1\, B => \PLD37/Column_bit_2\, Y => \PLD37/Read2\, G => \240\ );
	U423 : DIGITAL_LOW_NI
		port map( Y => \240\ );
	U424 : MUX8_1_NI
		port map( D0 => \PLD37/R_r1c1_3\, D1 => \PLD37/R_r1c2_3\, D2 => \PLD37/R_r1c3_3\, D3 => \241\, D4 => \PLD37/R_r2c1_3\, D5 => \PLD37/R_r2c2_3\, D6 => \PLD37/R_r2c3_3\, D7 => \241\, A => \PLD37/Column_bit_1\, C => \PLD37/Row_bit_1\, B => \PLD37/Column_bit_2\, Y => \PLD37/Read3\, G => \241\ );
	U425 : DIGITAL_LOW_NI
		port map( Y => \241\ );
	U426 : MUX8_1_NI
		port map( D0 => \PLD37/R_r1c1_4\, D1 => \PLD37/R_r1c2_4\, D2 => \PLD37/R_r1c3_4\, D3 => \242\, D4 => \PLD37/R_r2c1_4\, D5 => \PLD37/R_r2c2_4\, D6 => \PLD37/R_r2c3_4\, D7 => \242\, A => \PLD37/Column_bit_1\, C => \PLD37/Row_bit_1\, B => \PLD37/Column_bit_2\, Y => \PLD37/Read4\, G => \242\ );
	U427 : DIGITAL_LOW_NI
		port map( Y => \242\ );
	U428 : MUX8_1_NI
		port map( D0 => \PLD37/R_r1c1_5\, D1 => \PLD37/R_r1c2_5\, D2 => \PLD37/R_r1c3_5\, D3 => \254\, D4 => \PLD37/R_r2c1_5\, D5 => \PLD37/R_r2c2_5\, D6 => \PLD37/R_r2c3_5\, D7 => \254\, A => \PLD37/Column_bit_1\, C => \PLD37/Row_bit_1\, B => \PLD37/Column_bit_2\, Y => \PLD37/Read5\, G => \254\ );
	U429 : DIGITAL_LOW_NI
		port map( Y => \254\ );
	U430 : MUX8_1_NI
		port map( D0 => \PLD37/R_r1c1_6\, D1 => \PLD37/R_r1c2_6\, D2 => \PLD37/R_r1c3_6\, D3 => \255\, D4 => \PLD37/R_r2c1_6\, D5 => \PLD37/R_r2c2_6\, D6 => \PLD37/R_r2c3_6\, D7 => \255\, A => \PLD37/Column_bit_1\, C => \PLD37/Row_bit_1\, B => \PLD37/Column_bit_2\, Y => \PLD37/Read6\, G => \255\ );
	U431 : DIGITAL_LOW_NI
		port map( Y => \255\ );
	U432 : MUX8_1_NI
		port map( D0 => \PLD37/R_r1c1_7\, D1 => \PLD37/R_r1c2_7\, D2 => \PLD37/R_r1c3_7\, D3 => \257\, D4 => \PLD37/R_r2c1_7\, D5 => \PLD37/R_r2c2_7\, D6 => \PLD37/R_r2c3_7\, D7 => \257\, A => \PLD37/Column_bit_1\, C => \PLD37/Row_bit_1\, B => \PLD37/Column_bit_2\, Y => \PLD37/Read7\, G => \257\ );
	U433 : DIGITAL_LOW_NI
		port map( Y => \257\ );
	U435 : MUX8_1_NI
		port map( D0 => \PLD37/R_r1c1_8\, D1 => \PLD37/R_r1c2_8\, D2 => \PLD37/R_r1c3_8\, D3 => \264\, D4 => \PLD37/R_r2c1_8\, D5 => \PLD37/R_r2c2_8\, D6 => \PLD37/R_r2c3_8\, D7 => \264\, A => \PLD37/Column_bit_1\, C => \PLD37/Row_bit_1\, B => \PLD37/Column_bit_2\, Y => \PLD37/Read8\, G => \264\ );
	U436 : DIGITAL_LOW_NI
		port map( Y => \264\ );
	U439 : MUX8_1_NI
		port map( D0 => \PLD37/R_r1c1_9\, D1 => \PLD37/R_r1c2_9\, D2 => \PLD37/R_r1c3_9\, D3 => \266\, D4 => \PLD37/R_r2c1_9\, D5 => \PLD37/R_r2c2_9\, D6 => \PLD37/R_r2c3_9\, D7 => \266\, A => \PLD37/Column_bit_1\, C => \PLD37/Row_bit_1\, B => \PLD37/Column_bit_2\, Y => \PLD37/Read9\, G => \266\ );
	U440 : DIGITAL_LOW_NI
		port map( Y => \266\ );
	U441 : MUX8_1_NI
		port map( D0 => \PLD37/R_r1c1_10\, D1 => \PLD37/R_r1c2_10\, D2 => \PLD37/R_r1c3_10\, D3 => \267\, D4 => \PLD37/R_r2c1_10\, D5 => \PLD37/R_r2c2_10\, D6 => \PLD37/R_r2c3_10\, D7 => \267\, A => \PLD37/Column_bit_1\, C => \PLD37/Row_bit_1\, B => \PLD37/Column_bit_2\, Y => \PLD37/Read10\, G => \267\ );
	U442 : DIGITAL_LOW_NI
		port map( Y => \267\ );
	U444 : MUX8_1_NI
		port map( D0 => \PLD37/R_r1c1_11\, D1 => \PLD37/R_r1c2_11\, D2 => \PLD37/R_r1c3_11\, D3 => \269\, D4 => \PLD37/R_r2c1_11\, D5 => \PLD37/R_r2c2_11\, D6 => \PLD37/R_r2c3_11\, D7 => \269\, A => \PLD37/Column_bit_1\, C => \PLD37/Row_bit_1\, B => \PLD37/Column_bit_2\, Y => \PLD37/Read11\, G => \269\ );
	U445 : DIGITAL_LOW_NI
		port map( Y => \269\ );
	U446 : MUX8_1_NI
		port map( D0 => \PLD37/R_r1c1_12\, D1 => \PLD37/R_r1c2_12\, D2 => \PLD37/R_r1c3_12\, D3 => \270\, D4 => \PLD37/R_r2c1_12\, D5 => \PLD37/R_r2c2_12\, D6 => \PLD37/R_r2c3_12\, D7 => \270\, A => \PLD37/Column_bit_1\, C => \PLD37/Row_bit_1\, B => \PLD37/Column_bit_2\, Y => \PLD37/Read12\, G => \270\ );
	U447 : DIGITAL_LOW_NI
		port map( Y => \270\ );
	U21 : FF_JK_PSCLR_CO_NI
		port map( J => \PLD4/O1\, Q => \PLD13/Hsync\, Qneg => open, K => \PLD5/O1\, CLR => \46\, CLK => \PLD1/CLOCK_A_25MHz\, PR => \46\ );
	U22 : FF_JK_PSCLR_CO_NI
		port map( J => \PLD3/O1\, Q => \PLD21/HBLANK\, Qneg => open, K => \PLD6/O1\, CLR => \46\, CLK => \PLD1/CLOCK_A_25MHz\, PR => \46\ );
	U23 : DIGITAL_HIGH_NI
		port map( Y => \46\ );
	U10 : AND3_NI
		port map( A => \PLD4/I9\, B => \PLD4/I8\, C => \PLD4/I5\, Y => \PLD2/CLR\ );
	U52 : FF_JK_PSCLR_CO_NI
		port map( J => \PLD9/O1\, Q => \PLD13/Vsync\, Qneg => open, K => \PLD12/O1\, CLR => \42\, CLK => \PLD13/Hsync\, PR => \42\ );
	U53 : FF_JK_PSCLR_CO_NI
		port map( J => \PLD10/O1\, Q => \PLD21/VBLANK\, Qneg => open, K => \PLD11/O1\, CLR => \42\, CLK => \PLD13/Hsync\, PR => \42\ );
	U54 : DIGITAL_HIGH_NI
		port map( Y => \42\ );
	U24 : AND3_NI
		port map( A => \PLD9/I9\, B => \PLD9/I3\, C => \PLD9/I0\, Y => \PLD8/CLR\ );
	U129 : CNTR_4BIN_ASCLR_NI
		port map( QA => \PLD37/Row_bit_1\, QB => \PLD37/Read_row_bit2\, QC => open, QD => open, RCO => open, A => \162\, B => \162\, C => \162\, D => \162\, ENP => \162\, ENT => \162\, LOAD => \162\, CLR => \163\, CLK => \164\ );
	U131 : OR2_NI
		port map( A => \165\, B => \PLD17/CLR\, Y => \PLD19/CLR\ );
	U132 : INV_NI
		port map( Y => \163\, A => \PLD17/CLR\ );
	U133 : DIGITAL_HIGH_NI
		port map( Y => \162\ );
	U130 : AND4_NI
		port map( A => \PLD19/Q5\, B => \PLD19/Q6\, C => \PLD19/Q7\, D => \PLD19/Q8\, Y => \164\ );
	U134 : AND5_NI
		port map( A => \PLD19/Q1\, B => \PLD19/Q5\, C => \PLD19/Q6\, D => \PLD19/Q7\, Y => \165\, E => \PLD19/Q8\ );
	U135 : OR2_NI
		port map( A => \169\, B => \PLD18/CLR\, Y => \PLD20/CLR\ );
	U136 : INV_NI
		port map( Y => \167\, A => \PLD18/CLR\ );
	U137 : DIGITAL_HIGH_NI
		port map( Y => \168\ );
	U138 : CNTR_4BIN_ASCLR_NI
		port map( QA => \PLD37/Column_bit_1\, QB => \PLD37/Column_bit_2\, QC => open, QD => open, RCO => open, A => \168\, B => \168\, C => \168\, D => \168\, ENP => \168\, ENT => \168\, LOAD => \168\, CLR => \167\, CLK => \59\ );
	U61 : AND5_NI
		port map( A => \PLD20/Q2\, B => \PLD20/Q3\, C => \PLD20/Q5\, D => \PLD20/Q7\, Y => \169\, E => \PLD20/Q8\ );
	U139 : AND5_NI
		port map( A => \PLD20/Q1\, B => \PLD20/Q3\, C => \PLD20/Q5\, D => \PLD20/Q7\, Y => \59\, E => \PLD20/Q8\ );
	U115 : MUX4_1_NI
		port map( S0 => \PLD32/IN1\, S1 => \PLD32/IN2\, EN => \202\, Y => \PLD32/OUT1\, I0 => \PLD32/bit1_1\, I1 => \PLD32/bit2_1\, I2 => \PLD32/bit3_1\, I3 => \PLD32/bit4_1\ );
	U116 : MUX4_1_NI
		port map( S0 => \PLD32/IN1\, S1 => \PLD32/IN2\, EN => \202\, Y => \PLD32/OUT2\, I0 => \PLD32/bit1_2\, I1 => \PLD32/bit2_2\, I2 => \PLD32/bit3_2\, I3 => \PLD32/bit4_2\ );
	U117 : MUX4_1_NI
		port map( S0 => \PLD32/IN1\, S1 => \PLD32/IN2\, EN => \202\, Y => \PLD32/OUT3\, I0 => \PLD32/bit1_4\, I1 => \PLD32/bit2_4\, I2 => \PLD32/bit3_4\, I3 => \PLD32/bit4_4\ );
	U118 : MUX4_1_NI
		port map( S0 => \PLD32/IN1\, S1 => \PLD32/IN2\, EN => \202\, Y => \PLD32/OUT4\, I0 => \PLD32/bit1_8\, I1 => \PLD32/bit2_8\, I2 => \PLD32/bit3_8\, I3 => \PLD32/bit4_8\ );
	U119 : DIGITAL_LOW_NI
		port map( Y => \202\ );
	U448 : SR_4BIDI_NI
		port map( A => \271\, B => \272\, C => \275\, D => \276\, SL => \277\, QA => \278\, QB => \279\, QC => \281\, QD => \283\, SR => \277\, CLR => \277\, S0 => \277\, S1 => \277\, CLK => \294\ );
	U449 : SR_4BIDI_NI
		port map( A => \295\, B => \300\, C => \301\, D => \302\, SL => \303\, QA => \304\, QB => \305\, QC => \306\, QD => \307\, SR => \303\, CLR => \303\, S0 => \303\, S1 => \303\, CLK => \308\ );
	U450 : SR_4BIDI_NI
		port map( A => \309\, B => \310\, C => \311\, D => \313\, SL => \316\, QA => \317\, QB => \318\, QC => \319\, QD => \320\, SR => \316\, CLR => \316\, S0 => \316\, S1 => \316\, CLK => \321\ );
	U451 : MUX2_1_NI
		port map( Y => \271\, A => \PLD37/W_1\, B => \322\, S => \PLD37/reset_en\, G => \323\ );
	U452 : MUX2_1_NI
		port map( Y => \272\, A => \PLD37/W_2\, B => \324\, S => \PLD37/reset_en\, G => \323\ );
	U453 : MUX2_1_NI
		port map( Y => \275\, A => \PLD37/W_3\, B => \325\, S => \PLD37/reset_en\, G => \323\ );
	U454 : MUX2_1_NI
		port map( Y => \276\, A => \PLD37/W_4\, B => \326\, S => \PLD37/reset_en\, G => \323\ );
	U455 : MUX2_1_NI
		port map( Y => \295\, A => \PLD37/W_5\, B => \327\, S => \PLD37/reset_en\, G => \323\ );
	U456 : MUX2_1_NI
		port map( Y => \300\, A => \PLD37/W_6\, B => \328\, S => \PLD37/reset_en\, G => \323\ );
	U457 : MUX2_1_NI
		port map( Y => \301\, A => \PLD37/W_7\, B => \329\, S => \PLD37/reset_en\, G => \323\ );
	U458 : MUX2_1_NI
		port map( Y => \302\, A => \PLD37/W_8\, B => \330\, S => \PLD37/reset_en\, G => \323\ );
	U459 : MUX2_1_NI
		port map( Y => \309\, A => \PLD37/W_9\, B => \331\, S => \PLD37/reset_en\, G => \323\ );
	U460 : MUX2_1_NI
		port map( Y => \310\, A => \PLD37/W_10\, B => \332\, S => \PLD37/reset_en\, G => \323\ );
	U461 : MUX2_1_NI
		port map( Y => \311\, A => \PLD37/W_11\, B => \333\, S => \PLD37/reset_en\, G => \323\ );
	U462 : MUX2_1_NI
		port map( Y => \313\, A => \PLD37/W_12\, B => \334\, S => \PLD37/reset_en\, G => \323\ );
	U463 : AND2_NI
		port map( A => \278\, B => \335\, Y => \PLD37/R_r1c1_1\ );
	U464 : AND2_NI
		port map( A => \279\, B => \335\, Y => \PLD37/R_r1c1_2\ );
	U465 : AND2_NI
		port map( A => \281\, B => \335\, Y => \PLD37/R_r1c1_3\ );
	U466 : AND2_NI
		port map( A => \283\, B => \335\, Y => \PLD37/R_r1c1_4\ );
	U467 : AND2_NI
		port map( A => \304\, B => \335\, Y => \PLD37/R_r1c1_5\ );
	U468 : AND2_NI
		port map( A => \305\, B => \335\, Y => \PLD37/R_r1c1_6\ );
	U469 : AND2_NI
		port map( A => \306\, B => \335\, Y => \PLD37/R_r1c1_7\ );
	U470 : AND2_NI
		port map( A => \307\, B => \335\, Y => \PLD37/R_r1c1_8\ );
	U471 : AND2_NI
		port map( A => \317\, B => \335\, Y => \PLD37/R_r1c1_9\ );
	U472 : AND2_NI
		port map( A => \318\, B => \335\, Y => \PLD37/R_r1c1_10\ );
	U473 : AND2_NI
		port map( A => \319\, B => \335\, Y => \PLD37/R_r1c1_11\ );
	U474 : AND2_NI
		port map( A => \320\, B => \335\, Y => \PLD37/R_r1c1_12\ );
	U475 : AND3_NI
		port map( A => \PLD37/Read_EN\, B => \PLD15/Read_EN_Col\, C => \PLD15/Read_EN_Row\, Y => \335\ );
	U476 : DIGITAL_HIGH_NI
		port map( Y => \277\ );
	U477 : DIGITAL_HIGH_NI
		port map( Y => \303\ );
	U478 : DIGITAL_HIGH_NI
		port map( Y => \316\ );
	U479 : AND3_NI
		port map( A => \31\, B => \PLD24/Write_EN_Col\, C => \PLD15/Write_EN_Row\, Y => \336\ );
	U480 : DIGITAL_HIGH_NI
		port map( Y => \326\ );
	U481 : DIGITAL_HIGH_NI
		port map( Y => \325\ );
	U482 : DIGITAL_LOW_NI
		port map( Y => \324\ );
	U483 : DIGITAL_LOW_NI
		port map( Y => \322\ );
	U484 : DIGITAL_HIGH_NI
		port map( Y => \330\ );
	U485 : DIGITAL_HIGH_NI
		port map( Y => \328\ );
	U486 : DIGITAL_LOW_NI
		port map( Y => \329\ );
	U487 : DIGITAL_LOW_NI
		port map( Y => \327\ );
	U488 : DIGITAL_HIGH_NI
		port map( Y => \334\ );
	U489 : DIGITAL_LOW_NI
		port map( Y => \333\ );
	U490 : DIGITAL_LOW_NI
		port map( Y => \332\ );
	U491 : DIGITAL_LOW_NI
		port map( Y => \331\ );
	U492 : DIGITAL_LOW_NI
		port map( Y => \323\ );
	U493 : OR2_NI
		port map( A => \336\, B => \7\, Y => \294\ );
	U494 : OR2_NI
		port map( A => \336\, B => \13\, Y => \308\ );
	U495 : OR2_NI
		port map( A => \336\, B => \19\, Y => \321\ );
	U126 : FF_D_CO_NI
		port map( D => \PLD37/reset_en\, Q => \7\, CLK => \PLD37/CLK_FF_500Hz\, Qneg => open );
	U156 : FF_D_CO_NI
		port map( D => \PLD37/reset_en\, Q => \13\, CLK => \PLD37/CLK_FF_500Hz\, Qneg => open );
	U162 : FF_D_CO_NI
		port map( D => \PLD37/reset_en\, Q => \19\, CLK => \PLD37/CLK_FF_500Hz\, Qneg => open );
	U169 : NOR2_NI
		port map( A => \25\, B => \PLD37/reset_en\, Y => \31\ );
	U175 : INV_NI
		port map( Y => \25\, A => \PLD37/WRITE_CLOCK\ );
	U496 : SR_4BIDI_NI
		port map( A => \338\, B => \339\, C => \340\, D => \341\, SL => \342\, QA => \343\, QB => \344\, QC => \345\, QD => \346\, SR => \342\, CLR => \342\, S0 => \342\, S1 => \342\, CLK => \347\ );
	U497 : SR_4BIDI_NI
		port map( A => \348\, B => \349\, C => \350\, D => \351\, SL => \352\, QA => \353\, QB => \354\, QC => \355\, QD => \356\, SR => \352\, CLR => \352\, S0 => \352\, S1 => \352\, CLK => \357\ );
	U498 : SR_4BIDI_NI
		port map( A => \358\, B => \359\, C => \360\, D => \361\, SL => \362\, QA => \363\, QB => \364\, QC => \365\, QD => \366\, SR => \362\, CLR => \362\, S0 => \362\, S1 => \362\, CLK => \367\ );
	U499 : MUX2_1_NI
		port map( Y => \338\, A => \PLD37/W_1\, B => \368\, S => \PLD37/reset_en\, G => \369\ );
	U500 : MUX2_1_NI
		port map( Y => \339\, A => \PLD37/W_2\, B => \370\, S => \PLD37/reset_en\, G => \369\ );
	U501 : MUX2_1_NI
		port map( Y => \340\, A => \PLD37/W_3\, B => \371\, S => \PLD37/reset_en\, G => \369\ );
	U502 : MUX2_1_NI
		port map( Y => \341\, A => \PLD37/W_4\, B => \372\, S => \PLD37/reset_en\, G => \369\ );
	U503 : MUX2_1_NI
		port map( Y => \348\, A => \PLD37/W_5\, B => \373\, S => \PLD37/reset_en\, G => \369\ );
	U504 : MUX2_1_NI
		port map( Y => \349\, A => \PLD37/W_6\, B => \374\, S => \PLD37/reset_en\, G => \369\ );
	U505 : MUX2_1_NI
		port map( Y => \350\, A => \PLD37/W_7\, B => \375\, S => \PLD37/reset_en\, G => \369\ );
	U506 : MUX2_1_NI
		port map( Y => \351\, A => \PLD37/W_8\, B => \376\, S => \PLD37/reset_en\, G => \369\ );
	U507 : MUX2_1_NI
		port map( Y => \358\, A => \PLD37/W_9\, B => \377\, S => \PLD37/reset_en\, G => \369\ );
	U508 : MUX2_1_NI
		port map( Y => \359\, A => \PLD37/W_10\, B => \378\, S => \PLD37/reset_en\, G => \369\ );
	U509 : MUX2_1_NI
		port map( Y => \360\, A => \PLD37/W_11\, B => \379\, S => \PLD37/reset_en\, G => \369\ );
	U510 : MUX2_1_NI
		port map( Y => \361\, A => \PLD37/W_12\, B => \380\, S => \PLD37/reset_en\, G => \369\ );
	U511 : AND2_NI
		port map( A => \343\, B => \381\, Y => \PLD37/R_r1c2_1\ );
	U512 : AND2_NI
		port map( A => \344\, B => \381\, Y => \PLD37/R_r1c2_2\ );
	U513 : AND2_NI
		port map( A => \345\, B => \381\, Y => \PLD37/R_r1c2_3\ );
	U514 : AND2_NI
		port map( A => \346\, B => \381\, Y => \PLD37/R_r1c2_4\ );
	U515 : AND2_NI
		port map( A => \353\, B => \381\, Y => \PLD37/R_r1c2_5\ );
	U516 : AND2_NI
		port map( A => \354\, B => \381\, Y => \PLD37/R_r1c2_6\ );
	U517 : AND2_NI
		port map( A => \355\, B => \381\, Y => \PLD37/R_r1c2_7\ );
	U518 : AND2_NI
		port map( A => \356\, B => \381\, Y => \PLD37/R_r1c2_8\ );
	U519 : AND2_NI
		port map( A => \363\, B => \381\, Y => \PLD37/R_r1c2_9\ );
	U520 : AND2_NI
		port map( A => \364\, B => \381\, Y => \PLD37/R_r1c2_10\ );
	U521 : AND2_NI
		port map( A => \365\, B => \381\, Y => \PLD37/R_r1c2_11\ );
	U522 : AND2_NI
		port map( A => \366\, B => \381\, Y => \PLD37/R_r1c2_12\ );
	U523 : AND3_NI
		port map( A => \PLD37/Read_EN\, B => \PLD22/Read_EN_Col\, C => \PLD15/Read_EN_Row\, Y => \381\ );
	U524 : DIGITAL_HIGH_NI
		port map( Y => \342\ );
	U525 : DIGITAL_HIGH_NI
		port map( Y => \352\ );
	U526 : DIGITAL_HIGH_NI
		port map( Y => \362\ );
	U527 : AND3_NI
		port map( A => \32\, B => \PLD26/Write_EN_Col\, C => \PLD15/Write_EN_Row\, Y => \382\ );
	U528 : DIGITAL_HIGH_NI
		port map( Y => \372\ );
	U529 : DIGITAL_HIGH_NI
		port map( Y => \371\ );
	U530 : DIGITAL_LOW_NI
		port map( Y => \370\ );
	U531 : DIGITAL_LOW_NI
		port map( Y => \368\ );
	U532 : DIGITAL_HIGH_NI
		port map( Y => \376\ );
	U533 : DIGITAL_HIGH_NI
		port map( Y => \374\ );
	U534 : DIGITAL_LOW_NI
		port map( Y => \375\ );
	U535 : DIGITAL_LOW_NI
		port map( Y => \373\ );
	U536 : DIGITAL_HIGH_NI
		port map( Y => \380\ );
	U537 : DIGITAL_LOW_NI
		port map( Y => \379\ );
	U538 : DIGITAL_LOW_NI
		port map( Y => \378\ );
	U539 : DIGITAL_LOW_NI
		port map( Y => \377\ );
	U540 : DIGITAL_LOW_NI
		port map( Y => \369\ );
	U541 : OR2_NI
		port map( A => \382\, B => \8\, Y => \347\ );
	U542 : OR2_NI
		port map( A => \382\, B => \14\, Y => \357\ );
	U543 : OR2_NI
		port map( A => \382\, B => \20\, Y => \367\ );
	U149 : FF_D_CO_NI
		port map( D => \PLD37/reset_en\, Q => \8\, CLK => \PLD37/CLK_FF_500Hz\, Qneg => open );
	U157 : FF_D_CO_NI
		port map( D => \PLD37/reset_en\, Q => \14\, CLK => \PLD37/CLK_FF_500Hz\, Qneg => open );
	U163 : FF_D_CO_NI
		port map( D => \PLD37/reset_en\, Q => \20\, CLK => \PLD37/CLK_FF_500Hz\, Qneg => open );
	U170 : NOR2_NI
		port map( A => \26\, B => \PLD37/reset_en\, Y => \32\ );
	U176 : INV_NI
		port map( Y => \26\, A => \PLD37/WRITE_CLOCK\ );
	U544 : SR_4BIDI_NI
		port map( A => \383\, B => \384\, C => \385\, D => \386\, SL => \387\, QA => \388\, QB => \389\, QC => \390\, QD => \391\, SR => \387\, CLR => \387\, S0 => \387\, S1 => \387\, CLK => \392\ );
	U545 : SR_4BIDI_NI
		port map( A => \393\, B => \394\, C => \395\, D => \396\, SL => \397\, QA => \398\, QB => \399\, QC => \400\, QD => \401\, SR => \397\, CLR => \397\, S0 => \397\, S1 => \397\, CLK => \402\ );
	U546 : SR_4BIDI_NI
		port map( A => \403\, B => \404\, C => \405\, D => \406\, SL => \407\, QA => \408\, QB => \409\, QC => \410\, QD => \411\, SR => \407\, CLR => \407\, S0 => \407\, S1 => \407\, CLK => \417\ );
	U547 : MUX2_1_NI
		port map( Y => \383\, A => \PLD37/W_1\, B => \418\, S => \PLD37/reset_en\, G => \419\ );
	U548 : MUX2_1_NI
		port map( Y => \384\, A => \PLD37/W_2\, B => \420\, S => \PLD37/reset_en\, G => \419\ );
	U549 : MUX2_1_NI
		port map( Y => \385\, A => \PLD37/W_3\, B => \421\, S => \PLD37/reset_en\, G => \419\ );
	U550 : MUX2_1_NI
		port map( Y => \386\, A => \PLD37/W_4\, B => \422\, S => \PLD37/reset_en\, G => \419\ );
	U551 : MUX2_1_NI
		port map( Y => \393\, A => \PLD37/W_5\, B => \423\, S => \PLD37/reset_en\, G => \419\ );
	U552 : MUX2_1_NI
		port map( Y => \394\, A => \PLD37/W_6\, B => \424\, S => \PLD37/reset_en\, G => \419\ );
	U553 : MUX2_1_NI
		port map( Y => \395\, A => \PLD37/W_7\, B => \425\, S => \PLD37/reset_en\, G => \419\ );
	U554 : MUX2_1_NI
		port map( Y => \396\, A => \PLD37/W_8\, B => \426\, S => \PLD37/reset_en\, G => \419\ );
	U555 : MUX2_1_NI
		port map( Y => \403\, A => \PLD37/W_9\, B => \458\, S => \PLD37/reset_en\, G => \419\ );
	U556 : MUX2_1_NI
		port map( Y => \404\, A => \PLD37/W_10\, B => \459\, S => \PLD37/reset_en\, G => \419\ );
	U557 : MUX2_1_NI
		port map( Y => \405\, A => \PLD37/W_11\, B => \460\, S => \PLD37/reset_en\, G => \419\ );
	U558 : MUX2_1_NI
		port map( Y => \406\, A => \PLD37/W_12\, B => \461\, S => \PLD37/reset_en\, G => \419\ );
	U559 : AND2_NI
		port map( A => \388\, B => \462\, Y => \PLD37/R_r1c3_1\ );
	U560 : AND2_NI
		port map( A => \389\, B => \462\, Y => \PLD37/R_r1c3_2\ );
	U561 : AND2_NI
		port map( A => \390\, B => \462\, Y => \PLD37/R_r1c3_3\ );
	U562 : AND2_NI
		port map( A => \391\, B => \462\, Y => \PLD37/R_r1c3_4\ );
	U563 : AND2_NI
		port map( A => \398\, B => \462\, Y => \PLD37/R_r1c3_5\ );
	U564 : AND2_NI
		port map( A => \399\, B => \462\, Y => \PLD37/R_r1c3_6\ );
	U565 : AND2_NI
		port map( A => \400\, B => \462\, Y => \PLD37/R_r1c3_7\ );
	U566 : AND2_NI
		port map( A => \401\, B => \462\, Y => \PLD37/R_r1c3_8\ );
	U567 : AND2_NI
		port map( A => \408\, B => \462\, Y => \PLD37/R_r1c3_9\ );
	U568 : AND2_NI
		port map( A => \409\, B => \462\, Y => \PLD37/R_r1c3_10\ );
	U569 : AND2_NI
		port map( A => \410\, B => \462\, Y => \PLD37/R_r1c3_11\ );
	U570 : AND2_NI
		port map( A => \411\, B => \462\, Y => \PLD37/R_r1c3_12\ );
	U571 : AND3_NI
		port map( A => \PLD37/Read_EN\, B => \PLD23/Read_EN_Col\, C => \PLD15/Read_EN_Row\, Y => \462\ );
	U572 : DIGITAL_HIGH_NI
		port map( Y => \387\ );
	U573 : DIGITAL_HIGH_NI
		port map( Y => \397\ );
	U574 : DIGITAL_HIGH_NI
		port map( Y => \407\ );
	U575 : AND3_NI
		port map( A => \33\, B => \PLD27/Write_EN_Col\, C => \PLD15/Write_EN_Row\, Y => \463\ );
	U576 : DIGITAL_HIGH_NI
		port map( Y => \422\ );
	U577 : DIGITAL_HIGH_NI
		port map( Y => \421\ );
	U578 : DIGITAL_LOW_NI
		port map( Y => \420\ );
	U579 : DIGITAL_LOW_NI
		port map( Y => \418\ );
	U580 : DIGITAL_HIGH_NI
		port map( Y => \426\ );
	U581 : DIGITAL_HIGH_NI
		port map( Y => \424\ );
	U582 : DIGITAL_LOW_NI
		port map( Y => \425\ );
	U583 : DIGITAL_LOW_NI
		port map( Y => \423\ );
	U584 : DIGITAL_HIGH_NI
		port map( Y => \461\ );
	U585 : DIGITAL_LOW_NI
		port map( Y => \460\ );
	U586 : DIGITAL_LOW_NI
		port map( Y => \459\ );
	U587 : DIGITAL_LOW_NI
		port map( Y => \458\ );
	U588 : DIGITAL_LOW_NI
		port map( Y => \419\ );
	U589 : OR2_NI
		port map( A => \463\, B => \9\, Y => \392\ );
	U590 : OR2_NI
		port map( A => \463\, B => \15\, Y => \402\ );
	U591 : OR2_NI
		port map( A => \463\, B => \21\, Y => \417\ );
	U152 : FF_D_CO_NI
		port map( D => \PLD37/reset_en\, Q => \9\, CLK => \PLD37/CLK_FF_500Hz\, Qneg => open );
	U158 : FF_D_CO_NI
		port map( D => \PLD37/reset_en\, Q => \15\, CLK => \PLD37/CLK_FF_500Hz\, Qneg => open );
	U164 : FF_D_CO_NI
		port map( D => \PLD37/reset_en\, Q => \21\, CLK => \PLD37/CLK_FF_500Hz\, Qneg => open );
	U171 : NOR2_NI
		port map( A => \27\, B => \PLD37/reset_en\, Y => \33\ );
	U177 : INV_NI
		port map( Y => \27\, A => \PLD37/WRITE_CLOCK\ );
	U592 : SR_4BIDI_NI
		port map( A => \464\, B => \465\, C => \466\, D => \467\, SL => \468\, QA => \469\, QB => \470\, QC => \471\, QD => \472\, SR => \468\, CLR => \468\, S0 => \468\, S1 => \468\, CLK => \473\ );
	U593 : SR_4BIDI_NI
		port map( A => \474\, B => \475\, C => \476\, D => \477\, SL => \478\, QA => \479\, QB => \480\, QC => \481\, QD => \482\, SR => \478\, CLR => \478\, S0 => \478\, S1 => \478\, CLK => \483\ );
	U594 : SR_4BIDI_NI
		port map( A => \484\, B => \485\, C => \486\, D => \487\, SL => \488\, QA => \489\, QB => \490\, QC => \491\, QD => \492\, SR => \488\, CLR => \488\, S0 => \488\, S1 => \488\, CLK => \493\ );
	U595 : MUX2_1_NI
		port map( Y => \464\, A => \PLD37/W_1\, B => \494\, S => \PLD37/reset_en\, G => \495\ );
	U596 : MUX2_1_NI
		port map( Y => \465\, A => \PLD37/W_2\, B => \496\, S => \PLD37/reset_en\, G => \495\ );
	U597 : MUX2_1_NI
		port map( Y => \466\, A => \PLD37/W_3\, B => \497\, S => \PLD37/reset_en\, G => \495\ );
	U598 : MUX2_1_NI
		port map( Y => \467\, A => \PLD37/W_4\, B => \498\, S => \PLD37/reset_en\, G => \495\ );
	U599 : MUX2_1_NI
		port map( Y => \474\, A => \PLD37/W_5\, B => \499\, S => \PLD37/reset_en\, G => \495\ );
	U600 : MUX2_1_NI
		port map( Y => \475\, A => \PLD37/W_6\, B => \500\, S => \PLD37/reset_en\, G => \495\ );
	U601 : MUX2_1_NI
		port map( Y => \476\, A => \PLD37/W_7\, B => \501\, S => \PLD37/reset_en\, G => \495\ );
	U602 : MUX2_1_NI
		port map( Y => \477\, A => \PLD37/W_8\, B => \502\, S => \PLD37/reset_en\, G => \495\ );
	U603 : MUX2_1_NI
		port map( Y => \484\, A => \PLD37/W_9\, B => \503\, S => \PLD37/reset_en\, G => \495\ );
	U604 : MUX2_1_NI
		port map( Y => \485\, A => \PLD37/W_10\, B => \504\, S => \PLD37/reset_en\, G => \495\ );
	U605 : MUX2_1_NI
		port map( Y => \486\, A => \PLD37/W_11\, B => \505\, S => \PLD37/reset_en\, G => \495\ );
	U618 : MUX2_1_NI
		port map( Y => \487\, A => \PLD37/W_12\, B => \506\, S => \PLD37/reset_en\, G => \495\ );
	U619 : AND2_NI
		port map( A => \469\, B => \507\, Y => \PLD37/R_r2c1_1\ );
	U624 : AND2_NI
		port map( A => \470\, B => \507\, Y => \PLD37/R_r2c1_2\ );
	U625 : AND2_NI
		port map( A => \471\, B => \507\, Y => \PLD37/R_r2c1_3\ );
	U631 : AND2_NI
		port map( A => \472\, B => \507\, Y => \PLD37/R_r2c1_4\ );
	U632 : AND2_NI
		port map( A => \479\, B => \507\, Y => \PLD37/R_r2c1_5\ );
	U633 : AND2_NI
		port map( A => \480\, B => \507\, Y => \PLD37/R_r2c1_6\ );
	U634 : AND2_NI
		port map( A => \481\, B => \507\, Y => \PLD37/R_r2c1_7\ );
	U635 : AND2_NI
		port map( A => \482\, B => \507\, Y => \PLD37/R_r2c1_8\ );
	U636 : AND2_NI
		port map( A => \489\, B => \507\, Y => \PLD37/R_r2c1_9\ );
	U637 : AND2_NI
		port map( A => \490\, B => \507\, Y => \PLD37/R_r2c1_10\ );
	U638 : AND2_NI
		port map( A => \491\, B => \507\, Y => \PLD37/R_r2c1_11\ );
	U639 : AND2_NI
		port map( A => \492\, B => \507\, Y => \PLD37/R_r2c1_12\ );
	U640 : AND3_NI
		port map( A => \PLD37/Read_EN\, B => \PLD15/Read_EN_Col\, C => \PLD24/Read_EN_Row\, Y => \507\ );
	U641 : DIGITAL_HIGH_NI
		port map( Y => \468\ );
	U642 : DIGITAL_HIGH_NI
		port map( Y => \478\ );
	U643 : DIGITAL_HIGH_NI
		port map( Y => \488\ );
	U644 : AND3_NI
		port map( A => \34\, B => \PLD24/Write_EN_Col\, C => \PLD24/Write_EN_Row\, Y => \508\ );
	U645 : DIGITAL_HIGH_NI
		port map( Y => \498\ );
	U646 : DIGITAL_HIGH_NI
		port map( Y => \497\ );
	U647 : DIGITAL_LOW_NI
		port map( Y => \496\ );
	U648 : DIGITAL_LOW_NI
		port map( Y => \494\ );
	U649 : DIGITAL_HIGH_NI
		port map( Y => \502\ );
	U650 : DIGITAL_HIGH_NI
		port map( Y => \500\ );
	U651 : DIGITAL_LOW_NI
		port map( Y => \501\ );
	U652 : DIGITAL_LOW_NI
		port map( Y => \499\ );
	U653 : DIGITAL_HIGH_NI
		port map( Y => \506\ );
	U654 : DIGITAL_LOW_NI
		port map( Y => \505\ );
	U655 : DIGITAL_LOW_NI
		port map( Y => \504\ );
	U656 : DIGITAL_LOW_NI
		port map( Y => \503\ );
	U657 : DIGITAL_LOW_NI
		port map( Y => \495\ );
	U658 : OR2_NI
		port map( A => \508\, B => \10\, Y => \473\ );
	U659 : OR2_NI
		port map( A => \508\, B => \16\, Y => \483\ );
	U660 : OR2_NI
		port map( A => \508\, B => \22\, Y => \493\ );
	U153 : FF_D_CO_NI
		port map( D => \PLD37/reset_en\, Q => \10\, CLK => \PLD37/CLK_FF_500Hz\, Qneg => open );
	U159 : FF_D_CO_NI
		port map( D => \PLD37/reset_en\, Q => \16\, CLK => \PLD37/CLK_FF_500Hz\, Qneg => open );
	U165 : FF_D_CO_NI
		port map( D => \PLD37/reset_en\, Q => \22\, CLK => \PLD37/CLK_FF_500Hz\, Qneg => open );
	U172 : NOR2_NI
		port map( A => \28\, B => \PLD37/reset_en\, Y => \34\ );
	U178 : INV_NI
		port map( Y => \28\, A => \PLD37/WRITE_CLOCK\ );
	U661 : SR_4BIDI_NI
		port map( A => \509\, B => \510\, C => \511\, D => \512\, SL => \513\, QA => \514\, QB => \515\, QC => \516\, QD => \517\, SR => \513\, CLR => \513\, S0 => \513\, S1 => \513\, CLK => \518\ );
	U662 : SR_4BIDI_NI
		port map( A => \519\, B => \520\, C => \521\, D => \522\, SL => \523\, QA => \524\, QB => \525\, QC => \526\, QD => \527\, SR => \523\, CLR => \523\, S0 => \523\, S1 => \523\, CLK => \528\ );
	U663 : SR_4BIDI_NI
		port map( A => \529\, B => \530\, C => \531\, D => \532\, SL => \533\, QA => \534\, QB => \535\, QC => \536\, QD => \537\, SR => \533\, CLR => \533\, S0 => \533\, S1 => \533\, CLK => \538\ );
	U664 : MUX2_1_NI
		port map( Y => \509\, A => \PLD37/W_1\, B => \539\, S => \PLD37/reset_en\, G => \540\ );
	U665 : MUX2_1_NI
		port map( Y => \510\, A => \PLD37/W_2\, B => \541\, S => \PLD37/reset_en\, G => \540\ );
	U666 : MUX2_1_NI
		port map( Y => \511\, A => \PLD37/W_3\, B => \542\, S => \PLD37/reset_en\, G => \540\ );
	U667 : MUX2_1_NI
		port map( Y => \512\, A => \PLD37/W_4\, B => \543\, S => \PLD37/reset_en\, G => \540\ );
	U668 : MUX2_1_NI
		port map( Y => \519\, A => \PLD37/W_5\, B => \544\, S => \PLD37/reset_en\, G => \540\ );
	U669 : MUX2_1_NI
		port map( Y => \520\, A => \PLD37/W_6\, B => \545\, S => \PLD37/reset_en\, G => \540\ );
	U670 : MUX2_1_NI
		port map( Y => \521\, A => \PLD37/W_7\, B => \546\, S => \PLD37/reset_en\, G => \540\ );
	U671 : MUX2_1_NI
		port map( Y => \522\, A => \PLD37/W_8\, B => \547\, S => \PLD37/reset_en\, G => \540\ );
	U672 : MUX2_1_NI
		port map( Y => \529\, A => \PLD37/W_9\, B => \548\, S => \PLD37/reset_en\, G => \540\ );
	U673 : MUX2_1_NI
		port map( Y => \530\, A => \PLD37/W_10\, B => \549\, S => \PLD37/reset_en\, G => \540\ );
	U678 : MUX2_1_NI
		port map( Y => \531\, A => \PLD37/W_11\, B => \550\, S => \PLD37/reset_en\, G => \540\ );
	U679 : MUX2_1_NI
		port map( Y => \532\, A => \PLD37/W_12\, B => \551\, S => \PLD37/reset_en\, G => \540\ );
	U680 : AND2_NI
		port map( A => \514\, B => \552\, Y => \PLD37/R_r2c2_1\ );
	U681 : AND2_NI
		port map( A => \515\, B => \552\, Y => \PLD37/R_r2c2_2\ );
	U682 : AND2_NI
		port map( A => \516\, B => \552\, Y => \PLD37/R_r2c2_3\ );
	U683 : AND2_NI
		port map( A => \517\, B => \552\, Y => \PLD37/R_r2c2_4\ );
	U684 : AND2_NI
		port map( A => \524\, B => \552\, Y => \PLD37/R_r2c2_5\ );
	U685 : AND2_NI
		port map( A => \525\, B => \552\, Y => \PLD37/R_r2c2_6\ );
	U686 : AND2_NI
		port map( A => \526\, B => \552\, Y => \PLD37/R_r2c2_7\ );
	U687 : AND2_NI
		port map( A => \527\, B => \552\, Y => \PLD37/R_r2c2_8\ );
	U688 : AND2_NI
		port map( A => \534\, B => \552\, Y => \PLD37/R_r2c2_9\ );
	U689 : AND2_NI
		port map( A => \535\, B => \552\, Y => \PLD37/R_r2c2_10\ );
	U690 : AND2_NI
		port map( A => \536\, B => \552\, Y => \PLD37/R_r2c2_11\ );
	U691 : AND2_NI
		port map( A => \537\, B => \552\, Y => \PLD37/R_r2c2_12\ );
	U692 : AND3_NI
		port map( A => \PLD37/Read_EN\, B => \PLD22/Read_EN_Col\, C => \PLD24/Read_EN_Row\, Y => \552\ );
	U693 : DIGITAL_HIGH_NI
		port map( Y => \513\ );
	U694 : DIGITAL_HIGH_NI
		port map( Y => \523\ );
	U695 : DIGITAL_HIGH_NI
		port map( Y => \533\ );
	U696 : AND3_NI
		port map( A => \35\, B => \PLD26/Write_EN_Col\, C => \PLD24/Write_EN_Row\, Y => \553\ );
	U697 : DIGITAL_HIGH_NI
		port map( Y => \543\ );
	U698 : DIGITAL_HIGH_NI
		port map( Y => \542\ );
	U699 : DIGITAL_LOW_NI
		port map( Y => \541\ );
	U700 : DIGITAL_LOW_NI
		port map( Y => \539\ );
	U701 : DIGITAL_HIGH_NI
		port map( Y => \547\ );
	U702 : DIGITAL_HIGH_NI
		port map( Y => \545\ );
	U703 : DIGITAL_LOW_NI
		port map( Y => \546\ );
	U704 : DIGITAL_LOW_NI
		port map( Y => \544\ );
	U705 : DIGITAL_HIGH_NI
		port map( Y => \551\ );
	U706 : DIGITAL_LOW_NI
		port map( Y => \550\ );
	U707 : DIGITAL_LOW_NI
		port map( Y => \549\ );
	U708 : DIGITAL_LOW_NI
		port map( Y => \548\ );
	U709 : DIGITAL_LOW_NI
		port map( Y => \540\ );
	U710 : OR2_NI
		port map( A => \553\, B => \11\, Y => \518\ );
	U711 : OR2_NI
		port map( A => \553\, B => \17\, Y => \528\ );
	U712 : OR2_NI
		port map( A => \553\, B => \23\, Y => \538\ );
	U154 : FF_D_CO_NI
		port map( D => \PLD37/reset_en\, Q => \11\, CLK => \PLD37/CLK_FF_500Hz\, Qneg => open );
	U160 : FF_D_CO_NI
		port map( D => \PLD37/reset_en\, Q => \17\, CLK => \PLD37/CLK_FF_500Hz\, Qneg => open );
	U166 : FF_D_CO_NI
		port map( D => \PLD37/reset_en\, Q => \23\, CLK => \PLD37/CLK_FF_500Hz\, Qneg => open );
	U173 : NOR2_NI
		port map( A => \29\, B => \PLD37/reset_en\, Y => \35\ );
	U179 : INV_NI
		port map( Y => \29\, A => \PLD37/WRITE_CLOCK\ );
	U713 : SR_4BIDI_NI
		port map( A => \554\, B => \555\, C => \556\, D => \557\, SL => \558\, QA => \559\, QB => \560\, QC => \561\, QD => \562\, SR => \558\, CLR => \558\, S0 => \558\, S1 => \558\, CLK => \563\ );
	U714 : SR_4BIDI_NI
		port map( A => \564\, B => \565\, C => \566\, D => \567\, SL => \568\, QA => \569\, QB => \570\, QC => \571\, QD => \572\, SR => \568\, CLR => \568\, S0 => \568\, S1 => \568\, CLK => \573\ );
	U715 : SR_4BIDI_NI
		port map( A => \574\, B => \575\, C => \576\, D => \577\, SL => \578\, QA => \579\, QB => \580\, QC => \581\, QD => \582\, SR => \578\, CLR => \578\, S0 => \578\, S1 => \578\, CLK => \583\ );
	U716 : MUX2_1_NI
		port map( Y => \554\, A => \PLD37/W_1\, B => \584\, S => \PLD37/reset_en\, G => \585\ );
	U717 : MUX2_1_NI
		port map( Y => \555\, A => \PLD37/W_2\, B => \586\, S => \PLD37/reset_en\, G => \585\ );
	U718 : MUX2_1_NI
		port map( Y => \556\, A => \PLD37/W_3\, B => \587\, S => \PLD37/reset_en\, G => \585\ );
	U719 : MUX2_1_NI
		port map( Y => \557\, A => \PLD37/W_4\, B => \588\, S => \PLD37/reset_en\, G => \585\ );
	U720 : MUX2_1_NI
		port map( Y => \564\, A => \PLD37/W_5\, B => \589\, S => \PLD37/reset_en\, G => \585\ );
	U721 : MUX2_1_NI
		port map( Y => \565\, A => \PLD37/W_6\, B => \590\, S => \PLD37/reset_en\, G => \585\ );
	U722 : MUX2_1_NI
		port map( Y => \566\, A => \PLD37/W_7\, B => \591\, S => \PLD37/reset_en\, G => \585\ );
	U723 : MUX2_1_NI
		port map( Y => \567\, A => \PLD37/W_8\, B => \592\, S => \PLD37/reset_en\, G => \585\ );
	U724 : MUX2_1_NI
		port map( Y => \574\, A => \PLD37/W_9\, B => \593\, S => \PLD37/reset_en\, G => \585\ );
	U725 : MUX2_1_NI
		port map( Y => \575\, A => \PLD37/W_10\, B => \594\, S => \PLD37/reset_en\, G => \585\ );
	U726 : MUX2_1_NI
		port map( Y => \576\, A => \PLD37/W_11\, B => \595\, S => \PLD37/reset_en\, G => \585\ );
	U727 : MUX2_1_NI
		port map( Y => \577\, A => \PLD37/W_12\, B => \596\, S => \PLD37/reset_en\, G => \585\ );
	U728 : AND2_NI
		port map( A => \559\, B => \597\, Y => \PLD37/R_r2c3_1\ );
	U729 : AND2_NI
		port map( A => \560\, B => \597\, Y => \PLD37/R_r2c3_2\ );
	U730 : AND2_NI
		port map( A => \561\, B => \597\, Y => \PLD37/R_r2c3_3\ );
	U731 : AND2_NI
		port map( A => \562\, B => \597\, Y => \PLD37/R_r2c3_4\ );
	U732 : AND2_NI
		port map( A => \569\, B => \597\, Y => \PLD37/R_r2c3_5\ );
	U733 : AND2_NI
		port map( A => \570\, B => \597\, Y => \PLD37/R_r2c3_6\ );
	U734 : AND2_NI
		port map( A => \571\, B => \597\, Y => \PLD37/R_r2c3_7\ );
	U735 : AND2_NI
		port map( A => \572\, B => \597\, Y => \PLD37/R_r2c3_8\ );
	U736 : AND2_NI
		port map( A => \579\, B => \597\, Y => \PLD37/R_r2c3_9\ );
	U737 : AND2_NI
		port map( A => \580\, B => \597\, Y => \PLD37/R_r2c3_10\ );
	U738 : AND2_NI
		port map( A => \581\, B => \597\, Y => \PLD37/R_r2c3_11\ );
	U739 : AND2_NI
		port map( A => \582\, B => \597\, Y => \PLD37/R_r2c3_12\ );
	U740 : AND3_NI
		port map( A => \PLD37/Read_EN\, B => \PLD23/Read_EN_Col\, C => \PLD24/Read_EN_Row\, Y => \597\ );
	U741 : DIGITAL_HIGH_NI
		port map( Y => \558\ );
	U742 : DIGITAL_HIGH_NI
		port map( Y => \568\ );
	U743 : DIGITAL_HIGH_NI
		port map( Y => \578\ );
	U744 : AND3_NI
		port map( A => \36\, B => \PLD27/Write_EN_Col\, C => \PLD24/Write_EN_Row\, Y => \598\ );
	U745 : DIGITAL_HIGH_NI
		port map( Y => \588\ );
	U746 : DIGITAL_HIGH_NI
		port map( Y => \587\ );
	U747 : DIGITAL_LOW_NI
		port map( Y => \586\ );
	U748 : DIGITAL_LOW_NI
		port map( Y => \584\ );
	U749 : DIGITAL_HIGH_NI
		port map( Y => \592\ );
	U750 : DIGITAL_HIGH_NI
		port map( Y => \590\ );
	U751 : DIGITAL_LOW_NI
		port map( Y => \591\ );
	U752 : DIGITAL_LOW_NI
		port map( Y => \589\ );
	U753 : DIGITAL_HIGH_NI
		port map( Y => \596\ );
	U754 : DIGITAL_LOW_NI
		port map( Y => \595\ );
	U755 : DIGITAL_LOW_NI
		port map( Y => \594\ );
	U756 : DIGITAL_LOW_NI
		port map( Y => \593\ );
	U757 : DIGITAL_LOW_NI
		port map( Y => \585\ );
	U758 : OR2_NI
		port map( A => \598\, B => \12\, Y => \563\ );
	U759 : OR2_NI
		port map( A => \598\, B => \18\, Y => \573\ );
	U760 : OR2_NI
		port map( A => \598\, B => \24\, Y => \583\ );
	U155 : FF_D_CO_NI
		port map( D => \PLD37/reset_en\, Q => \12\, CLK => \PLD37/CLK_FF_500Hz\, Qneg => open );
	U161 : FF_D_CO_NI
		port map( D => \PLD37/reset_en\, Q => \18\, CLK => \PLD37/CLK_FF_500Hz\, Qneg => open );
	U167 : FF_D_CO_NI
		port map( D => \PLD37/reset_en\, Q => \24\, CLK => \PLD37/CLK_FF_500Hz\, Qneg => open );
	U174 : NOR2_NI
		port map( A => \30\, B => \PLD37/reset_en\, Y => \36\ );
	U180 : INV_NI
		port map( Y => \30\, A => \PLD37/WRITE_CLOCK\ );
	U11 : AND6_NI
		port map( A => \PLD4/I0\, B => \PLD4/I1\, C => \PLD4/I2\, D => \PLD4/I3\, Y => \68\, E => \PLD4/I4\, F => \PLD4/I6\ );
	U12 : AND2_NI
		port map( A => \68\, B => \69\, Y => \PLD4/O1\ );
	U13 : NOR4_NI
		port map( A => \PLD4/I5\, B => \PLD4/I7\, Y => \69\, C => \PLD4/I8\, D => \PLD4/I9\ );
	U14 : AND5_NI
		port map( A => \PLD4/I0\, B => \PLD4/I1\, C => \PLD4/I2\, D => \PLD4/I3\, Y => \70\, E => \PLD4/I7\ );
	U15 : NOR5_NI
		port map( A => \PLD4/I4\, B => \PLD4/I5\, Y => \71\, C => \PLD4/I6\, D => \PLD4/I8\, E => \PLD4/I9\ );
	U16 : AND2_NI
		port map( A => \70\, B => \71\, Y => \PLD3/O1\ );
	U18 : AND7_NI
		port map( A => \PLD4/I0\, B => \PLD4/I1\, C => \PLD4/I2\, D => \PLD4/I3\, Y => \91\, E => \PLD4/I4\, F => \PLD4/I8\, G => \PLD4/I9\ );
	U19 : NOR3_NI
		port map( A => \PLD4/I5\, B => \PLD4/I6\, Y => \92\, C => \PLD4/I7\ );
	U20 : AND2_NI
		port map( A => \91\, B => \92\, Y => \PLD5/O1\ );
	U4 : CNTR_4BIN_S_NI
		port map( QA => \PLD4/I0\, QB => \PLD4/I1\, QC => \PLD4/I2\, QD => \PLD4/I3\, RCO => \37\, A => \38\, B => \38\, C => \38\, D => \38\, ENP => \38\, ENT => \38\, LOAD => \38\, CLR => \39\, CLK => \PLD1/CLOCK_A_25MHz\ );
	U5 : CNTR_4BIN_S_NI
		port map( QA => \PLD4/I4\, QB => \PLD4/I5\, QC => \PLD4/I6\, QD => \PLD4/I7\, RCO => \40\, A => \38\, B => \38\, C => \38\, D => \38\, ENP => \38\, ENT => \37\, LOAD => \38\, CLR => \39\, CLK => \PLD1/CLOCK_A_25MHz\ );
	U6 : CNTR_4BIN_S_NI
		port map( QA => \PLD4/I8\, QB => \PLD4/I9\, QC => open, QD => open, RCO => open, A => \38\, B => \38\, C => \38\, D => \38\, ENP => \38\, ENT => \41\, LOAD => \38\, CLR => \39\, CLK => \PLD1/CLOCK_A_25MHz\ );
	U7 : DIGITAL_HIGH_NI
		port map( Y => \38\ );
	U8 : BUF_INV_NI
		port map( Y => \39\, A => \PLD2/CLR\ );
	U9 : AND2_NI
		port map( A => \37\, B => \40\, Y => \41\ );
	U17 : AND5_NI
		port map( A => \PLD4/I1\, B => \PLD4/I2\, C => \PLD4/I3\, D => \PLD4/I8\, Y => \60\, E => \PLD4/I9\ );
	U25 : NOR5_NI
		port map( A => \PLD4/I0\, B => \PLD4/I4\, Y => \61\, C => \PLD4/I5\, D => \PLD4/I6\, E => \PLD4/I7\ );
	U26 : AND2_NI
		port map( A => \60\, B => \61\, Y => \PLD6/O1\ );
	U62 : AND2_NI
		port map( A => \PLD9/I0\, B => \43\, Y => \PLD9/O1\ );
	U63 : NOR3_NI
		port map( A => \PLD9/I1\, B => \PLD9/I2\, Y => \44\, C => \PLD9/I3\ );
	U64 : NOR3_NI
		port map( A => \PLD9/I4\, B => \PLD9/I5\, Y => \45\, C => \PLD9/I6\ );
	U65 : NOR3_NI
		port map( A => \PLD9/I7\, B => \PLD9/I8\, Y => \47\, C => \PLD9/I9\ );
	U66 : AND3_NI
		port map( A => \44\, B => \45\, C => \47\, Y => \43\ );
	U67 : AND4_NI
		port map( A => \PLD9/I1\, B => \PLD9/I2\, C => \PLD9/I3\, D => \PLD9/I4\, Y => \48\ );
	U68 : NOR6_NI
		port map( A => \PLD9/I0\, B => \PLD9/I5\, Y => \49\, C => \PLD9/I6\, D => \PLD9/I7\, E => \PLD9/I8\, F => \PLD9/I9\ );
	U70 : AND2_NI
		port map( A => \48\, B => \49\, Y => \PLD10/O1\ );
	U86 : AND2_NI
		port map( A => \52\, B => \53\, Y => \PLD12/O1\ );
	U87 : AND2_NI
		port map( A => \PLD9/I3\, B => \PLD9/I9\, Y => \53\ );
	U88 : NOR8_NI
		port map( A => \PLD9/I0\, B => \PLD9/I1\, Y => \52\, C => \PLD9/I2\, D => \PLD9/I4\, E => \PLD9/I5\, F => \PLD9/I6\, G => \PLD9/I7\, H => \PLD9/I8\ );
	U55 : CNTR_4BIN_S_NI
		port map( QA => \PLD9/I0\, QB => \PLD9/I1\, QC => \PLD9/I2\, QD => \PLD9/I3\, RCO => \54\, A => \55\, B => \55\, C => \55\, D => \55\, ENP => \55\, ENT => \55\, LOAD => \55\, CLR => \56\, CLK => \PLD13/Hsync\ );
	U56 : CNTR_4BIN_S_NI
		port map( QA => \PLD9/I4\, QB => \PLD9/I5\, QC => \PLD9/I6\, QD => \PLD9/I7\, RCO => \57\, A => \55\, B => \55\, C => \55\, D => \55\, ENP => \55\, ENT => \54\, LOAD => \55\, CLR => \56\, CLK => \PLD13/Hsync\ );
	U57 : CNTR_4BIN_S_NI
		port map( QA => \PLD9/I8\, QB => \PLD9/I9\, QC => open, QD => open, RCO => open, A => \55\, B => \55\, C => \55\, D => \55\, ENP => \55\, ENT => \58\, LOAD => \55\, CLR => \56\, CLK => \PLD13/Hsync\ );
	U58 : DIGITAL_HIGH_NI
		port map( Y => \55\ );
	U59 : BUF_INV_NI
		port map( Y => \56\, A => \PLD8/CLR\ );
	U60 : AND2_NI
		port map( A => \54\, B => \57\, Y => \58\ );
	U82 : AND8_NI
		port map( A => \PLD9/I1\, B => \PLD9/I2\, C => \PLD9/I3\, D => \PLD9/I4\, Y => \50\, E => \PLD9/I5\, F => \PLD9/I6\, G => \PLD9/I7\, H => \PLD9/I8\ );
	U83 : AND2_NI
		port map( A => \51\, B => \50\, Y => \PLD11/O1\ );
	U84 : NOR2_NI
		port map( A => \PLD9/I0\, B => \PLD9/I9\, Y => \51\ );
	U141 : CNTR_4BIN_S_NI
		port map( QA => \PLD19/Q1\, QB => \PLD19/Q2\, QC => \PLD19/Q3\, QD => \PLD19/Q4\, RCO => \170\, A => \171\, B => \171\, C => \171\, D => \171\, ENP => \171\, ENT => \171\, LOAD => \171\, CLR => \172\, CLK => \PLD13/Hsync\ );
	U142 : CNTR_4BIN_S_NI
		port map( QA => \PLD19/Q5\, QB => \PLD19/Q6\, QC => \PLD19/Q7\, QD => \PLD19/Q8\, RCO => \173\, A => \171\, B => \171\, C => \171\, D => \171\, ENP => \171\, ENT => \170\, LOAD => \171\, CLR => \172\, CLK => \PLD13/Hsync\ );
	U143 : CNTR_4BIN_S_NI
		port map( QA => \PLD19/Q9\, QB => \PLD19/Q10\, QC => open, QD => open, RCO => open, A => \171\, B => \171\, C => \171\, D => \171\, ENP => \171\, ENT => \174\, LOAD => \171\, CLR => \172\, CLK => \PLD13/Hsync\ );
	U144 : DIGITAL_HIGH_NI
		port map( Y => \171\ );
	U145 : BUF_INV_NI
		port map( Y => \172\, A => \PLD19/CLR\ );
	U146 : AND2_NI
		port map( A => \170\, B => \173\, Y => \174\ );
	U147 : CNTR_4BIN_S_NI
		port map( QA => \PLD20/Q1\, QB => \PLD20/Q2\, QC => \PLD20/Q3\, QD => \PLD20/Q4\, RCO => \175\, A => \176\, B => \176\, C => \176\, D => \176\, ENP => \176\, ENT => \176\, LOAD => \176\, CLR => \177\, CLK => \PLD1/CLOCK_A_25MHz\ );
	U148 : CNTR_4BIN_S_NI
		port map( QA => \PLD20/Q5\, QB => \PLD20/Q6\, QC => \PLD20/Q7\, QD => \PLD20/Q8\, RCO => \178\, A => \176\, B => \176\, C => \176\, D => \176\, ENP => \176\, ENT => \175\, LOAD => \176\, CLR => \177\, CLK => \PLD1/CLOCK_A_25MHz\ );
	U263 : CNTR_4BIN_S_NI
		port map( QA => \PLD20/Q9\, QB => \PLD20/Q10\, QC => open, QD => open, RCO => open, A => \176\, B => \176\, C => \176\, D => \176\, ENP => \176\, ENT => \179\, LOAD => \176\, CLR => \177\, CLK => \PLD1/CLOCK_A_25MHz\ );
	U264 : DIGITAL_HIGH_NI
		port map( Y => \176\ );
	U265 : BUF_INV_NI
		port map( Y => \177\, A => \PLD20/CLR\ );
	U266 : AND2_NI
		port map( A => \175\, B => \178\, Y => \179\ );
end behavioral;
