---------------------------------------------------
-- Sheet: lab3
-- RefDes: 
-- Part Number: XC7A35T
-- Generated By: Multisim
--
-- Author: Leo
-- Date: Tuesday, April 15 20:48:25, 2025
---------------------------------------------------

---------------------------------------------------
-- Use: This file contains definitions of components
-- Use with the exported top-level file
---------------------------------------------------
library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;

package Stage3_ywl_pkg is

	component AND2_NI
		port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component AND3_NI
		port (
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component AND4_NI
		port (
    D : in STD_LOGIC := 'X';
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component AUTO_IBUF
		port(
		I : in std_logic;
		O : out std_logic
	);
	end component;

	component AUTO_OBUF
		port(
		I : in std_logic;
		O : out std_logic
	);
	end component;

	component BUF_INV_NI
		port (
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component BUF_NI
		port (
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component CNTR_4BIN_ASCLR_NI
		port( 
  LOAD: in std_logic;
  CLR: in std_logic;
  ENP: in std_logic; 
  ENT: in std_logic;
  CLK: in std_logic;
  A:in STD_LOGIC;
  B:in STD_LOGIC;
  C:in STD_LOGIC;
  D:in STD_LOGIC;
  RCO: out STD_LOGIC;
  QA: out STD_LOGIC;
  QB: out STD_LOGIC;
  QC: out STD_LOGIC;
  QD: out STD_LOGIC
 );
	end component;

	component CNTR_4BIN_S_NI
		port( 
  LOAD: in STD_LOGIC;
  CLR: in STD_LOGIC;
  ENP: in STD_LOGIC; 
  ENT: in STD_LOGIC;
  CLK: in STD_LOGIC;
  A :in STD_LOGIC;
  B :in STD_LOGIC;
  C :in STD_LOGIC;
  D :in STD_LOGIC;
  RCO : out STD_LOGIC;
  QA : out STD_LOGIC;
  QB : out STD_LOGIC;
  QC : out STD_LOGIC;
  QD : out STD_LOGIC
 );
	end component;

	component CNTR_4BIN_SU_D_NI
		port( 
  LOAD: in STD_LOGIC;
  UD: in STD_LOGIC;
  CTEN: in STD_LOGIC; 
  CLK: in STD_LOGIC;
  A:in STD_LOGIC;
  B:in STD_LOGIC;
  C:in STD_LOGIC;
  D:in STD_LOGIC;
  RCO: out STD_LOGIC;
  MAXMIN: out STD_LOGIC;
  QA: out STD_LOGIC;
  QB: out STD_LOGIC;
  QC: out STD_LOGIC;
  QD: out STD_LOGIC
 );
	end component;

	component CNTR_BCD_S_NI
		port( 
  LOAD: in std_logic;
  CLR: in std_logic;
  ENP: in std_logic; 
  ENT: in std_logic;
  CLK: in std_logic;
  A:in STD_LOGIC;
  B:in STD_LOGIC;
  C:in STD_LOGIC;
  D:in STD_LOGIC;
  RCO: out STD_LOGIC;
  QA: out STD_LOGIC;
  QB: out STD_LOGIC;
  QC: out STD_LOGIC;
  QD: out STD_LOGIC
 );
	end component;

	component COMP_4_NI
		port (
   B3 : in STD_LOGIC := 'X';
   B2 : in STD_LOGIC := 'X';
   B1 : in STD_LOGIC := 'X';
   B0 : in STD_LOGIC := 'X';
   A3 : in STD_LOGIC := 'X';
   A2 : in STD_LOGIC := 'X';
   A1 : in STD_LOGIC := 'X';
   A0 : in STD_LOGIC := 'X';
   AGTB : in STD_LOGIC := 'X';
   AEQB : in STD_LOGIC := 'X';
   ALTB : in STD_LOGIC := 'X';
   OAGTB : out STD_LOGIC := 'U';
   OAEQB : out STD_LOGIC := 'U';
   OALTB : out STD_LOGIC := 'U'
    );
	end component;

	component DEC2_4_NI
		port (
 A : in STD_LOGIC;
 B : in STD_LOGIC;
 Y0 : out STD_LOGIC;
 Y1 : out STD_LOGIC;
 Y2 : out STD_LOGIC;
 Y3 : out STD_LOGIC;
 EN: in  STD_LOGIC
 );
	end component;

	component DEC_BCD_7_NI
		port (
  A : in STD_LOGIC;
  B : in STD_LOGIC;
  C : in STD_LOGIC;
  D : in STD_LOGIC;
  LT : in STD_LOGIC;
  RBI : in STD_LOGIC;
  BI : in STD_LOGIC;
  Y0 : out STD_LOGIC;
  Y1 : out STD_LOGIC;
  Y2 : out STD_LOGIC;
  Y3 : out STD_LOGIC;
  Y4 : out STD_LOGIC;
  Y5 : out STD_LOGIC;
  Y6 : out STD_LOGIC
 );
	end component;

	component DIGITAL_HIGH_NI
		Port ( 
  Y : out  STD_LOGIC:='1'
 );
	end component;

	component DIGITAL_LOW_NI
		Port ( 
  Y : out  STD_LOGIC:='0'
 );
	end component;

	component FF_D_CO_NI
		Port ( D : in  STD_LOGIC;
           CLK : in  STD_LOGIC;
           Q : out  STD_LOGIC;
           Qneg : out  STD_LOGIC);
	end component;

	component FF_JK_PSCLR_CO_NI
		port (
   J: in STD_LOGIC;
   K: in STD_LOGIC;
   CLK : in STD_LOGIC;  
   PR: in STD_LOGIC;
   CLR: in STD_LOGIC;
   Q : out STD_LOGIC;
   Qneg : out STD_LOGIC
);
	end component;

	component FF_T_CLR_CO_NI
		port (
    T: in STD_LOGIC;
    CLK : in STD_LOGIC;
    CLR : in STD_LOGIC;
     Q : out STD_LOGIC;
     Qneg : out STD_LOGIC
 );
	end component;

	component MUX4_1_NI
		port (
  Y : out STD_LOGIC;
  I0 : in STD_LOGIC;
  I1 : in STD_LOGIC;
  I2 : in STD_LOGIC;
  I3 : in STD_LOGIC;
  S0 : in STD_LOGIC;
  S1 : in STD_LOGIC;
  EN : in STD_LOGIC
 );
	end component;

	component NAND2_NI
		port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component OR2_NI
		port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component XOR2_NI
		port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

end Stage3_ywl_pkg;
package body Stage3_ywl_pkg is
end Stage3_ywl_pkg;


library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity AND2_NI is
  port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
end AND2_NI;

architecture BEHAVIORAL of AND2_NI is  

begin
  Y <= A and B;
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity AND3_NI is
  port (
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
end AND3_NI;

architecture BEHAVIORAL of AND3_NI is  

begin
  Y <= (A and B and C);
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity AND4_NI is
  port (
    D : in STD_LOGIC := 'X';
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
end AND4_NI;

architecture BEHAVIORAL of AND4_NI is  

begin
  Y <= (A and B and C and D);
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.all;

entity AUTO_IBUF is
	port(
		I : in std_logic;
		O : out std_logic
	);end AUTO_IBUF;

architecture AUTO_IBUF_ARCH of AUTO_IBUF is

begin
 O <= I;
end AUTO_IBUF_ARCH;


library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.all;

entity AUTO_OBUF is
	port(
		I : in std_logic;
		O : out std_logic
	);end AUTO_OBUF;

architecture AUTO_OBUF_ARCH of AUTO_OBUF is

begin
 O <= I;
end AUTO_OBUF_ARCH;


library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity BUF_INV_NI is
  port (
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
end BUF_INV_NI;

architecture BEHAVIORAL of BUF_INV_NI is  

begin
  Y <=not( A );
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity BUF_NI is
  port (
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
end BUF_NI;

architecture BEHAVIORAL of BUF_NI is  

begin
  Y <= A;
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;

entity CNTR_4BIN_ASCLR_NI is
 port( 
  LOAD: in std_logic;
  CLR: in std_logic;
  ENP: in std_logic; 
  ENT: in std_logic;
  CLK: in std_logic;
  A:in STD_LOGIC;
  B:in STD_LOGIC;
  C:in STD_LOGIC;
  D:in STD_LOGIC;
  RCO: out STD_LOGIC;
  QA: out STD_LOGIC;
  QB: out STD_LOGIC;
  QC: out STD_LOGIC;
  QD: out STD_LOGIC
 );
end CNTR_4BIN_ASCLR_NI;

architecture BEHAVIORAL of CNTR_4BIN_ASCLR_NI is
signal Q: STD_LOGIC_VECTOR(3 downto 0);

begin
 RCO<=Q(3) and Q(2) and Q(1) and Q(0) and ENT;
 process(CLR,CLK,LOAD,ENP,ENT,D,C,B,A)
 begin
 if CLR='0' then  Q<="0000";
 elsif rising_edge(CLK) then 
  if LOAD='0' then Q<=D&C&B&A;
  elsif (ENP and ENT)='1' then Q<=Q+"0001";
  end if;
 end if;
 end process;
 QD<=Q(3);
 QC<=Q(2);
 QB<=Q(1);
 QA<=Q(0);	
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;

entity CNTR_4BIN_S_NI is
 port( 
  LOAD: in STD_LOGIC;
  CLR: in STD_LOGIC;
  ENP: in STD_LOGIC; 
  ENT: in STD_LOGIC;
  CLK: in STD_LOGIC;
  A :in STD_LOGIC;
  B :in STD_LOGIC;
  C :in STD_LOGIC;
  D :in STD_LOGIC;
  RCO : out STD_LOGIC;
  QA : out STD_LOGIC;
  QB : out STD_LOGIC;
  QC : out STD_LOGIC;
  QD : out STD_LOGIC
 );
end CNTR_4BIN_S_NI;

architecture BEHAVIORAL of CNTR_4BIN_S_NI is
signal Q: STD_LOGIC_VECTOR(3 downto 0);

begin
 RCO<=Q(3) and Q(2) and Q(1) and Q(0) and ENT;
 process
 begin
   wait until CLK='1';
   if CLR = '0' then Q<="0000";
     elsif LOAD='0' then Q<=D&C&B&A;
     elsif (ENP and ENT)='1' then
     Q<=Q+"0001";
  end if;
 end process;
 QD<=Q(3);
 QC<=Q(2);
 QB<=Q(1);
 QA<=Q(0);
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;

entity CNTR_4BIN_SU_D_NI is
 port( 
  LOAD: in STD_LOGIC;
  UD: in STD_LOGIC;
  CTEN: in STD_LOGIC; 
  CLK: in STD_LOGIC;
  A:in STD_LOGIC;
  B:in STD_LOGIC;
  C:in STD_LOGIC;
  D:in STD_LOGIC;
  RCO: out STD_LOGIC;
  MAXMIN: out STD_LOGIC;
  QA: out STD_LOGIC;
  QB: out STD_LOGIC;
  QC: out STD_LOGIC;
  QD: out STD_LOGIC
 );
end CNTR_4BIN_SU_D_NI;

architecture BEHAVIORAL of CNTR_4BIN_SU_D_NI is
signal Q: STD_LOGIC_VECTOR(3 downto 0);

begin
 transition: process (CLK,LOAD,CTEN,UD,D,C,B,A)
 begin
 if LOAD='0' then Q<=D&C&B&A;
		MAXMIN<='0';
  elsif rising_edge(CLK) then
  if CTEN = '0' then
   if UD='0' then 
    if Q="1110" then MAXMIN<='1';
	        else MAXMIN<='0';
    end if;
	Q<=Q+"0001";
   elsif UD='1' then 
    if Q="0001" then MAXMIN<='1';
	       else MAXMIN<='0';
    end if;
	Q<=Q-"0001";
   end if;
  else  MAXMIN<='0';
  end if;
 end if;
 end process transition;
 rcodet: process (CLK,UD,CTEN)
 begin
 if LOAD='1' then
 if CTEN='0' then
  if UD='0' then 
   if Q="1111" then
    if CLK='0' then RCO<='0';
	    else RCO<='1';
    end if;
	    else RCO<='1';
   end if;
   else
   if Q="0000" then
    if CLK='0' then RCO<='0';
	    else RCO<='1';	
    end if;
	    else RCO<='1';
   end if;
  end if;
 else RCO<='1';
 end if;
 else RCO<='1';
 end if;
 end process rcodet;
 QD<=Q(3);
 QC<=Q(2);
 QB<=Q(1);
 QA<=Q(0);	
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;

entity CNTR_BCD_S_NI is
 port( 
  LOAD: in std_logic;
  CLR: in std_logic;
  ENP: in std_logic; 
  ENT: in std_logic;
  CLK: in std_logic;
  A:in STD_LOGIC;
  B:in STD_LOGIC;
  C:in STD_LOGIC;
  D:in STD_LOGIC;
  RCO: out STD_LOGIC;
  QA: out STD_LOGIC;
  QB: out STD_LOGIC;
  QC: out STD_LOGIC;
  QD: out STD_LOGIC
 );
end CNTR_BCD_S_NI;

architecture BEHAVIORAL of CNTR_BCD_S_NI is
signal Q: STD_LOGIC_VECTOR(3 downto 0);

begin
 process
 begin
 wait until CLK='1';
  if CLR = '0' then Q<="0000";
	             RCO<='0';
  elsif LOAD='0' then Q<=D&C&B&A;
		  RCO<='0';
  elsif (ENP and ENT)='1' then
   if Q="1000" then 
		RCO<='1';
		Q<=Q+"0001";
   elsif Q="1001" then 
		Q<="0000";
		RCO<='0';
   else
		Q<=Q+"0001";
		RCO<='0';
   end if;
  end if;
 end process;
 QD<=Q(3);
 QC<=Q(2);
 QB<=Q(1);
 QA<=Q(0);	
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_ARITH.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;

entity COMP_4_NI is
  port (
   B3 : in STD_LOGIC := 'X';
   B2 : in STD_LOGIC := 'X';
   B1 : in STD_LOGIC := 'X';
   B0 : in STD_LOGIC := 'X';
   A3 : in STD_LOGIC := 'X';
   A2 : in STD_LOGIC := 'X';
   A1 : in STD_LOGIC := 'X';
   A0 : in STD_LOGIC := 'X';
   AGTB : in STD_LOGIC := 'X';
   AEQB : in STD_LOGIC := 'X';
   ALTB : in STD_LOGIC := 'X';
   OAGTB : out STD_LOGIC := 'U';
   OAEQB : out STD_LOGIC := 'U';
   OALTB : out STD_LOGIC := 'U'
    );
end COMP_4_NI;

architecture BEHAVIORAL of COMP_4_NI is  
begin
PROCESS (A0, B0, A1, A2, A3, B1, B2, B3, AGTB, AEQB, ALTB)
     BEGIN
  if A3>B3 then OAGTB<='1';
                         OAEQB<='0';
	          OALTB<='0';
        elsif A3<B3 then OAGTB<='0';
                                   OAEQB<='0';
	                    OALTB<='1';	
          elsif A3=B3 then
            if A2>B2 then OAGTB<='1';
                                   OAEQB<='0';
		    OALTB<='0'; 
              elsif A2<B2 then OAGTB<='0';
                                         OAEQB<='0';
		          OALTB<='1';	
                elsif A2=B2 then
                  if A1>B1 then OAGTB<='1';
                                         OAEQB<='0';
		          OALTB<='0'; 
                    elsif A1<B1 then OAGTB<='0';
                                               OAEQB<='0';
			OALTB<='1';		
                      elsif A1=B1 then
                          if A0>B0 then OAGTB<='1';
                                                  OAEQB<='0';
			  OALTB<='0'; 
                            elsif A0<B0 then OAGTB<='0';
                                                       OAEQB<='0';
			        OALTB<='1';	
              		 elsif A0=B0 then
                                    if AGTB='1' and AEQB='0' and ALTB='0' then OAGTB<='1';
                                                                                                            OAEQB<='0';
				                                             OALTB<='0'; 
		          elsif ALTB='1' and AEQB='0' and AGTB='1' then OAGTB<='0';
			   				      OAEQB<='0';
							       OALTB<='0';	
                                              elsif AEQB='1' and AGTB='0' and ALTB='0' then OAGTB<='0';
							          OAEQB<='1';
							          OALTB<='0'; 
		                 elsif ALTB='1' and AEQB='0' and AGTB='0' then OAGTB<='0';
                                                                                                                             OAEQB<='0';
				                                                              OALTB<='1';   
                                               elsif AEQB='1' then 	OAGTB<='0';
					OAEQB<='1';
					OALTB<='0';  
                                                     elsif ALTB='0' and AEQB='0' and AGTB='0' then  OAGTB<='1';
                                                                                                                                  OAEQB<='0';
				                                                                   OALTB<='1';  	
										
						end if;
					end if;
				end if;
			end if;
end if;																							
END PROCESS;
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity DEC2_4_NI is
port (
 A : in STD_LOGIC;
 B : in STD_LOGIC;
 Y0 : out STD_LOGIC;
 Y1 : out STD_LOGIC;
 Y2 : out STD_LOGIC;
 Y3 : out STD_LOGIC;
 EN: in  STD_LOGIC
 );
end DEC2_4_NI;

architecture BEHAVIORAL of DEC2_4_NI is  
signal O : STD_LOGIC_VECTOR(3 DOWNTO 0);

begin
 process (EN,A,B)
 begin
   if EN='1' then O<="1111";
	elsif A='0' and B='0' then O<="1110";
	elsif A='1' and B='0' then O<="1101";
	elsif A='0' and B='1' then O<="1011";
	elsif A='1' and B='1' then O<="0111";
   end if;
 end process;
 Y3<=O(3);
 Y2<=O(2);
 Y1<=O(1);
 Y0<=O(0);
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity DEC_BCD_7_NI is
port (
  A : in STD_LOGIC;
  B : in STD_LOGIC;
  C : in STD_LOGIC;
  D : in STD_LOGIC;
  LT : in STD_LOGIC;
  RBI : in STD_LOGIC;
  BI : in STD_LOGIC;
  Y0 : out STD_LOGIC;
  Y1 : out STD_LOGIC;
  Y2 : out STD_LOGIC;
  Y3 : out STD_LOGIC;
  Y4 : out STD_LOGIC;
  Y5 : out STD_LOGIC;
  Y6 : out STD_LOGIC
 );
end DEC_BCD_7_NI;

architecture BEHAVIORAL of DEC_BCD_7_NI is  
signal O : STD_LOGIC_VECTOR(0 TO 6);

begin
 process (BI,LT,RBI,A,B,C,D)
 begin
   if BI='0' then O<="1111111";
	elsif LT='0' then O<="0000000";
	elsif (A='0' and B='0' and C='0' and D='0' and RBI='1') then O<="0000001";
	elsif (A='1' and B='0' and C='0' and D='0') then O<="1001111";
	elsif (A='0' and B='1' and C='0' and D='0') then O<="0010010";
	elsif (A='1' and B='1' and C='0' and D='0') then O<="0000110";
	elsif (A='0' and B='0' and C='1' and D='0') then O<="1001100";
	elsif (A='1' and B='0' and C='1' and D='0') then O<="0100100";
	elsif (A='0' and B='1' and C='1' and D='0') then O<="1100000";
	elsif (A='1' and B='1' and C='1' and D='0') then O<="0001111";
	elsif (A='0' and B='0' and C='0' and D='1') then O<="0000000";
	elsif (A='1' and B='0' and C='0' and D='1') then O<="0001100";
	elsif (A='0' and B='1' and C='0' and D='1') then O<="1110010";
	elsif (A='1' and B='1' and C='0' and D='1')then O<="1100110";
	elsif (A='0' and B='0' and C='1' and D='1') then O<="1011100";
	elsif (A='1' and B='0' and C='1' and D='1') then O<="0110100";
	elsif (A='0' and B='1' and C='1' and D='1') then O<="1110000";
	elsif (A='1' and B='1' and C='1' and D='1') then O<="1111111";
   end if;
end process;		
 Y6<=O(6);
 Y5<=O(5);
 Y4<=O(4);
 Y3<=O(3);
 Y2<=O(2);
 Y1<=O(1);
 Y0<=O(0);
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity DIGITAL_HIGH_NI is
 Port ( 
  Y : out  STD_LOGIC:='1'
 );
end DIGITAL_HIGH_NI;

architecture BEHAVIORAL of DIGITAL_HIGH_NI is
begin
 Y<='1';
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity DIGITAL_LOW_NI is
 Port ( 
  Y : out  STD_LOGIC:='0'
 );
end DIGITAL_LOW_NI;

architecture BEHAVIORAL of DIGITAL_LOW_NI is
begin
 Y<='0';
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity FF_D_CO_NI is
    Port ( D : in  STD_LOGIC;
           CLK : in  STD_LOGIC;
           Q : out  STD_LOGIC;
           Qneg : out  STD_LOGIC);
end FF_D_CO_NI;

architecture BEHAVIORAL of FF_D_CO_NI is

begin
 process (CLK,D)
 begin
  if rising_edge(CLK) then
    if D='1' then Q<='1';
	         Qneg<='0';
	else Q<='0';
	       Qneg<='1';           
    end if;
  end if;
 end process;		
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity FF_JK_PSCLR_CO_NI is
  port (
   J: in STD_LOGIC;
   K: in STD_LOGIC;
   CLK : in STD_LOGIC;  
   PR: in STD_LOGIC;
   CLR: in STD_LOGIC;
   Q : out STD_LOGIC;
   Qneg : out STD_LOGIC
);
end FF_JK_PSCLR_CO_NI;

architecture BEHAVIORAL of FF_JK_PSCLR_CO_NI is  
signal Qnot: STD_LOGIC:='0';
signal Qpos: STD_LOGIC:='1';

begin
  process (CLK,PR,CLR)
  begin
      if (PR='0' and CLR='1') then  Qpos<='1';
                                                       Qnot<='0';
          elsif (PR='1' and CLR='0') then Qpos<='0';
                                                              Qnot<='1'; 
          elsif (PR='0' and CLR='0') then Qpos<='1';
                                                               Qnot<='1';
          elsif (CLK'event and CLK='1') then
	    if (J='1' and K='1') then Qpos<=Qnot;
		                           Qnot<=Qpos;	
                    elsif (J='0' and K='1') then Qpos<='0';
		                               Qnot<='1';	
	    elsif (J='1' and K='0') then Qpos<='1';
			               Qnot<='0';							  
	    end if;
           end if;
 end process;		
 Qneg<=Qnot;
 Q<=Qpos;
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity FF_T_CLR_CO_NI is
 port (
    T: in STD_LOGIC;
    CLK : in STD_LOGIC;
    CLR : in STD_LOGIC;
     Q : out STD_LOGIC;
     Qneg : out STD_LOGIC
 );
end FF_T_CLR_CO_NI;

architecture BEHAVIORAL of FF_T_CLR_CO_NI is  
signal Qpos: STD_LOGIC:='1';
signal Qnot: STD_LOGIC:='0';

begin
 process (CLR,T,CLK)
 begin
  if CLR='0' then
	Qpos<='0';
	Qnot<='1';
  elsif (CLK'event and CLK='1') then
     if (T='1') then Qpos<=not Qpos;
	            Qnot<=not Qnot; 
     end if;
  end if;	
 end process;		
 Q<=Qpos;
 Qneg<=Qnot;
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity MUX4_1_NI is
port (
  Y : out STD_LOGIC;
  I0 : in STD_LOGIC;
  I1 : in STD_LOGIC;
  I2 : in STD_LOGIC;
  I3 : in STD_LOGIC;
  S0 : in STD_LOGIC;
  S1 : in STD_LOGIC;
  EN : in STD_LOGIC
 );
end MUX4_1_NI;

architecture BEHAVIORAL of MUX4_1_NI is  

begin
 process (I0, I1, I2, I3, S0, S1, EN)
 begin
       if EN='1' then Y<='0';
	elsif (S0='0' and S1='0' and I0='0') then Y<='0';
	elsif (S0='0' and S1='0' and I0='1') then Y<='1';
	elsif (S0='1' and S1='0' and I1='0') then Y<='0';
	elsif (S0='1' and S1='0' and I1='1') then Y<='1';
	elsif (S0='0' and S1='1' and I2='0') then Y<='0';
	elsif (S0='0' and S1='1' and I2='1') then Y<='1';
	elsif (S0='1' and S1='1' and I3='0') then Y<='0';
	elsif (S0='1' and S1='1' and I3='1') then Y<='1';
  end if;
 end process;
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity NAND2_NI is
  port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
end NAND2_NI;

architecture BEHAVIORAL of NAND2_NI is  

begin
  Y <= not(A and B);
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity OR2_NI is
  port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
end OR2_NI;

architecture BEHAVIORAL of OR2_NI is  

begin
  Y <= A or B;
end BEHAVIORAL;

library work;
use work.Stage3_ywl_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity XOR2_NI is
  port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
end XOR2_NI;

architecture BEHAVIORAL of XOR2_NI is  

begin
  Y <= A xor B;
end BEHAVIORAL;
