---------------------------------------------------
-- Sheet: lab3
-- RefDes: 
-- Part Number: XC7A35T
-- Generated By: Multisim
--
-- Author: Leo
-- Date: Tuesday, April 15 20:48:25, 2025
---------------------------------------------------

---------------------------------------------------
-- Use: This file defines the top-level of the design
-- Use with the exported package file
---------------------------------------------------
library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;

library work;
use work.Stage3_ywl_pkg.ALL;


entity lab3 is
	port (

		CLK : in std_logic;
		Hsync : out std_logic;
		Vsync : out std_logic;
		BTNC : in std_logic;
		BTND : in std_logic;
		BTNL : in std_logic;
		BTNR : in std_logic;
		BTNU : in std_logic;
		SW0 : in std_logic;
		SW1 : in std_logic;
		SW2 : in std_logic;
		SW3 : in std_logic;
		SW4 : in std_logic;
		SW5 : in std_logic;
		SW6 : in std_logic;
		SW7 : in std_logic;
		SW8 : in std_logic;
		SW9 : in std_logic;
		SW10 : in std_logic;
		SW11 : in std_logic;
		vgaBlue0 : out std_logic;
		vgaBlue1 : out std_logic;
		vgaBlue2 : out std_logic;
		vgaBlue3 : out std_logic;
		vgaGreen0 : out std_logic;
		vgaGreen1 : out std_logic;
		vgaGreen2 : out std_logic;
		vgaGreen3 : out std_logic;
		vgaRed0 : out std_logic;
		vgaRed1 : out std_logic;
		vgaRed2 : out std_logic;
		vgaRed3 : out std_logic;
		CA : out std_logic;
		CB : out std_logic;
		CC : out std_logic;
		CD : out std_logic;
		CE : out std_logic;
		CF : out std_logic;
		CG : out std_logic;
		AN1 : out std_logic;
		AN2 : out std_logic;
		AN3 : out std_logic;
		AN0 : out std_logic
	);
end lab3;


architecture behavioral of lab3 is


	component AND2_NI
		port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component AND3_NI
		port (
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component AND4_NI
		port (
    D : in STD_LOGIC := 'X';
    C : in STD_LOGIC := 'X';
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component AUTO_IBUF
		port(
		I : in std_logic;
		O : out std_logic
	);
	end component;

	component AUTO_OBUF
		port(
		I : in std_logic;
		O : out std_logic
	);
	end component;

	component BUF_INV_NI
		port (
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component BUF_NI
		port (
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component CNTR_4BIN_ASCLR_NI
		port( 
  LOAD: in std_logic;
  CLR: in std_logic;
  ENP: in std_logic; 
  ENT: in std_logic;
  CLK: in std_logic;
  A:in STD_LOGIC;
  B:in STD_LOGIC;
  C:in STD_LOGIC;
  D:in STD_LOGIC;
  RCO: out STD_LOGIC;
  QA: out STD_LOGIC;
  QB: out STD_LOGIC;
  QC: out STD_LOGIC;
  QD: out STD_LOGIC
 );
	end component;

	component CNTR_4BIN_S_NI
		port( 
  LOAD: in STD_LOGIC;
  CLR: in STD_LOGIC;
  ENP: in STD_LOGIC; 
  ENT: in STD_LOGIC;
  CLK: in STD_LOGIC;
  A :in STD_LOGIC;
  B :in STD_LOGIC;
  C :in STD_LOGIC;
  D :in STD_LOGIC;
  RCO : out STD_LOGIC;
  QA : out STD_LOGIC;
  QB : out STD_LOGIC;
  QC : out STD_LOGIC;
  QD : out STD_LOGIC
 );
	end component;

	component CNTR_4BIN_SU_D_NI
		port( 
  LOAD: in STD_LOGIC;
  UD: in STD_LOGIC;
  CTEN: in STD_LOGIC; 
  CLK: in STD_LOGIC;
  A:in STD_LOGIC;
  B:in STD_LOGIC;
  C:in STD_LOGIC;
  D:in STD_LOGIC;
  RCO: out STD_LOGIC;
  MAXMIN: out STD_LOGIC;
  QA: out STD_LOGIC;
  QB: out STD_LOGIC;
  QC: out STD_LOGIC;
  QD: out STD_LOGIC
 );
	end component;

	component CNTR_BCD_S_NI
		port( 
  LOAD: in std_logic;
  CLR: in std_logic;
  ENP: in std_logic; 
  ENT: in std_logic;
  CLK: in std_logic;
  A:in STD_LOGIC;
  B:in STD_LOGIC;
  C:in STD_LOGIC;
  D:in STD_LOGIC;
  RCO: out STD_LOGIC;
  QA: out STD_LOGIC;
  QB: out STD_LOGIC;
  QC: out STD_LOGIC;
  QD: out STD_LOGIC
 );
	end component;

	component COMP_4_NI
		port (
   B3 : in STD_LOGIC := 'X';
   B2 : in STD_LOGIC := 'X';
   B1 : in STD_LOGIC := 'X';
   B0 : in STD_LOGIC := 'X';
   A3 : in STD_LOGIC := 'X';
   A2 : in STD_LOGIC := 'X';
   A1 : in STD_LOGIC := 'X';
   A0 : in STD_LOGIC := 'X';
   AGTB : in STD_LOGIC := 'X';
   AEQB : in STD_LOGIC := 'X';
   ALTB : in STD_LOGIC := 'X';
   OAGTB : out STD_LOGIC := 'U';
   OAEQB : out STD_LOGIC := 'U';
   OALTB : out STD_LOGIC := 'U'
    );
	end component;

	component DEC2_4_NI
		port (
 A : in STD_LOGIC;
 B : in STD_LOGIC;
 Y0 : out STD_LOGIC;
 Y1 : out STD_LOGIC;
 Y2 : out STD_LOGIC;
 Y3 : out STD_LOGIC;
 EN: in  STD_LOGIC
 );
	end component;

	component DEC_BCD_7_NI
		port (
  A : in STD_LOGIC;
  B : in STD_LOGIC;
  C : in STD_LOGIC;
  D : in STD_LOGIC;
  LT : in STD_LOGIC;
  RBI : in STD_LOGIC;
  BI : in STD_LOGIC;
  Y0 : out STD_LOGIC;
  Y1 : out STD_LOGIC;
  Y2 : out STD_LOGIC;
  Y3 : out STD_LOGIC;
  Y4 : out STD_LOGIC;
  Y5 : out STD_LOGIC;
  Y6 : out STD_LOGIC
 );
	end component;

	component DIGITAL_HIGH_NI
		Port ( 
  Y : out  STD_LOGIC:='1'
 );
	end component;

	component DIGITAL_LOW_NI
		Port ( 
  Y : out  STD_LOGIC:='0'
 );
	end component;

	component FF_D_CO_NI
		Port ( D : in  STD_LOGIC;
           CLK : in  STD_LOGIC;
           Q : out  STD_LOGIC;
           Qneg : out  STD_LOGIC);
	end component;

	component FF_JK_PSCLR_CO_NI
		port (
   J: in STD_LOGIC;
   K: in STD_LOGIC;
   CLK : in STD_LOGIC;  
   PR: in STD_LOGIC;
   CLR: in STD_LOGIC;
   Q : out STD_LOGIC;
   Qneg : out STD_LOGIC
);
	end component;

	component FF_T_CLR_CO_NI
		port (
    T: in STD_LOGIC;
    CLK : in STD_LOGIC;
    CLR : in STD_LOGIC;
     Q : out STD_LOGIC;
     Qneg : out STD_LOGIC
 );
	end component;

	component MUX4_1_NI
		port (
  Y : out STD_LOGIC;
  I0 : in STD_LOGIC;
  I1 : in STD_LOGIC;
  I2 : in STD_LOGIC;
  I3 : in STD_LOGIC;
  S0 : in STD_LOGIC;
  S1 : in STD_LOGIC;
  EN : in STD_LOGIC
 );
	end component;

	component NAND2_NI
		port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component OR2_NI
		port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component XOR2_NI
		port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;
	signal \1\ : std_logic;
	signal \PLD35/AN1\ : std_logic;
	signal \PLD21/Read_9\ : std_logic;
	signal \PLD21/W_6\ : std_logic;
	signal \PLD34/Green4\ : std_logic;
	signal \PLD21/WCB_2\ : std_logic;
	signal \PLD21/Read_10\ : std_logic;
	signal \PLD35/SW2\ : std_logic;
	signal \PLD21/RCB_2\ : std_logic;
	signal \PLD21/W_3\ : std_logic;
	signal \PLD21/Read_1\ : std_logic;
	signal \PLD34/Q4\ : std_logic;
	signal \PLD21/Read_7\ : std_logic;
	signal \PLD34/Q5\ : std_logic;
	signal \PLD14/VC_2\ : std_logic;
	signal \PLD21/WRB_2\ : std_logic;
	signal \PLD14/HC_6\ : std_logic;
	signal \PLD21/W_9\ : std_logic;
	signal \PLD21/WCB_1\ : std_logic;
	signal \PLD21/Read_5\ : std_logic;
	signal \PLD21/Read_12\ : std_logic;
	signal \PLD35/AN0\ : std_logic;
	signal \PLD21/W_10\ : std_logic;
	signal \PLD21/WRB_1\ : std_logic;
	signal \PLD14/HBLANK\ : std_logic;
	signal \PLD34/Q12\ : std_logic;
	signal \PLD21/WC\ : std_logic;
	signal \PLD34/Q9\ : std_logic;
	signal \PLD21/W_2\ : std_logic;
	signal \PLD14/VBLANK\ : std_logic;
	signal \PLD35/CD\ : std_logic;
	signal \PLD21/W_7\ : std_logic;
	signal \PLD21/W_8\ : std_logic;
	signal \PLD21/Read_4\ : std_logic;
	signal \PLD21/RE\ : std_logic;
	signal \PLD14/Hsync\ : std_logic;
	signal \PLD20/Up\ : std_logic;
	signal \PLD35/AN3\ : std_logic;
	signal \PLD34/Q7\ : std_logic;
	signal \PLD14/Vsync\ : std_logic;
	signal \PLD14/VC_5\ : std_logic;
	signal \PLD35/CA\ : std_logic;
	signal \PLD34/Q11\ : std_logic;
	signal \PLD20/Right\ : std_logic;
	signal \PLD34/Flashing\ : std_logic;
	signal \PLD14/HC_8\ : std_logic;
	signal \PLD21/W_4\ : std_logic;
	signal \PLD35/CG\ : std_logic;
	signal \PLD20/Down\ : std_logic;
	signal \PLD35/CC\ : std_logic;
	signal \PLD21/Read_2\ : std_logic;
	signal \PLD14/HC_7\ : std_logic;
	signal \PLD14/HC_10\ : std_logic;
	signal \PLD21/W_5\ : std_logic;
	signal \PLD15/HCLOCK\ : std_logic;
	signal \PLD21/RRB_2\ : std_logic;
	signal \PLD35/CF\ : std_logic;
	signal \PLD34/Q3\ : std_logic;
	signal \PLD35/CB\ : std_logic;
	signal \PLD21/W_11\ : std_logic;
	signal \PLD21/W_1\ : std_logic;
	signal \PLD35/Row_Col_EN\ : std_logic;
	signal \PLD14/HC_9\ : std_logic;
	signal \PLD35/AN2\ : std_logic;
	signal \PLD21/Read_11\ : std_logic;
	signal \PLD34/Q1\ : std_logic;
	signal \PLD21/Read_6\ : std_logic;
	signal \PLD13/CLK\ : std_logic;
	signal \PLD13/JA1\ : std_logic;
	signal \PLD21/W_12\ : std_logic;
	signal \PLD34/Q10\ : std_logic;
	signal \PLD14/VC_8\ : std_logic;
	signal \PLD34/Q2\ : std_logic;
	signal \PLD21/Write_Read_Address_EQ\ : std_logic;
	signal \PLD20/Left\ : std_logic;
	signal \PLD21/RCB_1\ : std_logic;
	signal \PLD21/RRB_1\ : std_logic;
	signal \PLD21/Read_3\ : std_logic;
	signal \PLD35/CE\ : std_logic;
	signal \PLD34/Q8\ : std_logic;
	signal \PLD14/VC_9\ : std_logic;
	signal \PLD14/VC_1\ : std_logic;
	signal \PLD13/JA2\ : std_logic;
	signal \PLD14/HC_3\ : std_logic;
	signal \PLD34/Q6\ : std_logic;
	signal \PLD14/VC_4\ : std_logic;
	signal \PLD14/HC_1\ : std_logic;
	signal \PLD14/HC_2\ : std_logic;
	signal \PLD14/HC_5\ : std_logic;
	signal \PLD14/VC_6\ : std_logic;
	signal \PLD14/VC_7\ : std_logic;
	signal \PLD14/VC_3\ : std_logic;
	signal \PLD14/HC_4\ : std_logic;
	signal \PLD38/Clear\ : std_logic;
	signal \PLD17/Clear\ : std_logic;
	signal \PLD26/Write_EN_Row\ : std_logic;
	signal \PLD30/Read_6\ : std_logic;
	signal \PLD24/Read_1\ : std_logic;
	signal \PLD22/Read_12\ : std_logic;
	signal \PLD31/Read_7\ : std_logic;
	signal \PLD22/Read_1\ : std_logic;
	signal \PLD30/Write_EN_Row\ : std_logic;
	signal \PLD24/Read_EN_Col\ : std_logic;
	signal \PLD21/R1_6\ : std_logic;
	signal \PLD28/Read_12\ : std_logic;
	signal \PLD30/Read_1\ : std_logic;
	signal \PLD21/R2_8\ : std_logic;
	signal \PLD22/Previous_1\ : std_logic;
	signal \PLD32/Read_10\ : std_logic;
	signal \PLD27/Read_5\ : std_logic;
	signal \PLD26/Read_3\ : std_logic;
	signal \PLD30/Read_4\ : std_logic;
	signal \PLD23/Read_5\ : std_logic;
	signal \PLD31/Read_4\ : std_logic;
	signal \PLD32/Read_4\ : std_logic;
	signal \PLD31/Read_8\ : std_logic;
	signal \PLD25/Write_EN_Col\ : std_logic;
	signal \PLD32/Read_1\ : std_logic;
	signal \PLD27/Read_12\ : std_logic;
	signal \PLD21/R1_10\ : std_logic;
	signal \PLD30/Read_3\ : std_logic;
	signal \PLD21/R1_1\ : std_logic;
	signal \PLD21/R1_9\ : std_logic;
	signal \PLD21/R2_12\ : std_logic;
	signal \PLD21/R2_9\ : std_logic;
	signal \PLD30/Read_EN_Row\ : std_logic;
	signal \PLD21/R2_10\ : std_logic;
	signal \PLD21/R2_2\ : std_logic;
	signal \PLD22/Read_EN_Col\ : std_logic;
	signal \PLD22/Read_5\ : std_logic;
	signal \PLD21/R2_4\ : std_logic;
	signal \PLD24/Read_8\ : std_logic;
	signal \PLD30/Read_5\ : std_logic;
	signal \PLD21/R1_7\ : std_logic;
	signal \PLD32/Read_3\ : std_logic;
	signal \PLD30/Read_2\ : std_logic;
	signal \422\ : std_logic;
	signal \PLD21/R1_3\ : std_logic;
	signal \PLD31/Read_10\ : std_logic;
	signal \PLD24/Read_10\ : std_logic;
	signal \PLD26/Read_EN_Row\ : std_logic;
	signal \PLD22/Read_EN_Row\ : std_logic;
	signal \PLD23/Read_EN_Col\ : std_logic;
	signal \PLD22/Write_EN_Row\ : std_logic;
	signal \PLD21/R1_4\ : std_logic;
	signal \PLD27/Read_10\ : std_logic;
	signal \PLD31/Read_11\ : std_logic;
	signal \PLD26/Read_11\ : std_logic;
	signal \PLD21/R1_8\ : std_logic;
	signal \PLD28/Read_5\ : std_logic;
	signal \PLD32/Read_5\ : std_logic;
	signal \PLD23/Read_4\ : std_logic;
	signal \PLD27/Read_1\ : std_logic;
	signal \PLD21/R2_6\ : std_logic;
	signal \PLD30/Read_10\ : std_logic;
	signal \PLD32/Read_9\ : std_logic;
	signal \PLD22/Read_9\ : std_logic;
	signal \PLD26/Read_9\ : std_logic;
	signal \PLD24/Write_EN_Col\ : std_logic;
	signal \PLD23/Read_11\ : std_logic;
	signal \PLD24/Read_5\ : std_logic;
	signal \PLD23/Read_7\ : std_logic;
	signal \PLD23/Write_EN_Col\ : std_logic;
	signal \PLD22/Write_EN_Col\ : std_logic;
	signal \PLD25/Read_EN_Col\ : std_logic;
	signal \PLD21/R1_11\ : std_logic;
	signal \PLD24/Read_9\ : std_logic;
	signal \PLD26/Read_6\ : std_logic;
	signal \PLD21/R1_5\ : std_logic;
	signal \PLD21/R2_5\ : std_logic;
	signal \PLD21/R2_1\ : std_logic;
	signal \420\ : std_logic;
	signal \PLD21/R1_2\ : std_logic;
	signal \PLD27/Read_4\ : std_logic;
	signal \PLD30/Read_11\ : std_logic;
	signal \408\ : std_logic;
	signal \PLD21/R1_12\ : std_logic;
	signal \PLD28/Read_2\ : std_logic;
	signal \PLD23/Read_10\ : std_logic;
	signal \PLD23/Read_8\ : std_logic;
	signal \PLD22/Read_3\ : std_logic;
	signal \PLD28/Read_9\ : std_logic;
	signal \PLD24/Read_4\ : std_logic;
	signal \PLD27/Read_9\ : std_logic;
	signal \PLD30/Read_7\ : std_logic;
	signal \PLD31/Read_9\ : std_logic;
	signal \PLD22/Read_2\ : std_logic;
	signal \PLD28/Read_3\ : std_logic;
	signal \415\ : std_logic;
	signal \PLD26/Read_5\ : std_logic;
	signal \PLD28/Read_11\ : std_logic;
	signal \PLD27/Read_7\ : std_logic;
	signal \PLD23/Read_9\ : std_logic;
	signal \PLD31/Read_1\ : std_logic;
	signal \PLD21/R2_11\ : std_logic;
	signal \PLD27/Read_11\ : std_logic;
	signal \PLD28/Read_1\ : std_logic;
	signal \PLD32/Read_12\ : std_logic;
	signal \407\ : std_logic;
	signal \PLD31/Read_6\ : std_logic;
	signal \PLD24/Read_3\ : std_logic;
	signal \PLD24/Read_7\ : std_logic;
	signal \PLD27/Read_6\ : std_logic;
	signal \PLD21/R2_7\ : std_logic;
	signal \PLD27/Read_2\ : std_logic;
	signal \PLD26/Read_12\ : std_logic;
	signal \PLD26/Read_8\ : std_logic;
	signal \PLD32/Read_8\ : std_logic;
	signal \PLD30/Read_12\ : std_logic;
	signal \PLD32/Read_6\ : std_logic;
	signal \PLD21/R2_3\ : std_logic;
	signal \PLD22/Read_7\ : std_logic;
	signal \PLD22/Read_6\ : std_logic;
	signal \PLD23/Read_3\ : std_logic;
	signal \PLD22/Read_11\ : std_logic;
	signal \PLD24/Read_11\ : std_logic;
	signal \PLD23/Read_12\ : std_logic;
	signal \PLD26/Read_1\ : std_logic;
	signal \PLD28/Read_6\ : std_logic;
	signal \PLD22/Read_4\ : std_logic;
	signal \PLD26/Read_4\ : std_logic;
	signal \404\ : std_logic;
	signal \PLD27/Read_8\ : std_logic;
	signal \PLD27/Read_3\ : std_logic;
	signal \419\ : std_logic;
	signal \PLD32/Read_2\ : std_logic;
	signal \PLD23/Read_2\ : std_logic;
	signal \PLD23/Read_6\ : std_logic;
	signal \PLD31/Read_3\ : std_logic;
	signal \413\ : std_logic;
	signal \PLD26/Read_2\ : std_logic;
	signal \PLD24/Read_6\ : std_logic;
	signal \PLD26/Read_7\ : std_logic;
	signal \PLD28/Read_10\ : std_logic;
	signal \423\ : std_logic;
	signal \PLD26/Read_10\ : std_logic;
	signal \PLD30/Read_8\ : std_logic;
	signal \PLD22/Read_10\ : std_logic;
	signal \PLD24/Read_2\ : std_logic;
	signal \PLD28/Read_4\ : std_logic;
	signal \406\ : std_logic;
	signal \416\ : std_logic;
	signal \409\ : std_logic;
	signal \410\ : std_logic;
	signal \411\ : std_logic;
	signal \PLD32/Read_7\ : std_logic;
	signal \405\ : std_logic;
	signal \PLD31/Read_12\ : std_logic;
	signal \PLD31/Read_5\ : std_logic;
	signal \412\ : std_logic;
	signal \PLD23/Read_1\ : std_logic;
	signal \PLD30/Read_9\ : std_logic;
	signal \PLD32/Read_11\ : std_logic;
	signal \PLD31/Read_2\ : std_logic;
	signal \PLD28/Read_7\ : std_logic;
	signal \PLD22/Read_8\ : std_logic;
	signal \PLD28/Read_8\ : std_logic;
	signal \PLD24/Read_12\ : std_logic;
	signal \414\ : std_logic;
	signal \418\ : std_logic;
	signal \421\ : std_logic;
	signal \417\ : std_logic;
	signal \PLD22/W\ : std_logic;
	signal \111\ : std_logic;
	signal \41\ : std_logic;
	signal \112\ : std_logic;
	signal \PLD22/R\ : std_logic;
	signal \134\ : std_logic;
	signal \137\ : std_logic;
	signal \42\ : std_logic;
	signal \132\ : std_logic;
	signal \133\ : std_logic;
	signal \44\ : std_logic;
	signal \135\ : std_logic;
	signal \138\ : std_logic;
	signal \139\ : std_logic;
	signal \114\ : std_logic;
	signal \136\ : std_logic;
	signal \126\ : std_logic;
	signal \129\ : std_logic;
	signal \127\ : std_logic;
	signal \128\ : std_logic;
	signal \40\ : std_logic;
	signal \130\ : std_logic;
	signal \113\ : std_logic;
	signal \43\ : std_logic;
	signal \125\ : std_logic;
	signal \131\ : std_logic;
	signal \PLD27/W\ : std_logic;
	signal \241\ : std_logic;
	signal \237\ : std_logic;
	signal \242\ : std_logic;
	signal \PLD27/R\ : std_logic;
	signal \254\ : std_logic;
	signal \257\ : std_logic;
	signal \238\ : std_logic;
	signal \252\ : std_logic;
	signal \253\ : std_logic;
	signal \240\ : std_logic;
	signal \255\ : std_logic;
	signal \258\ : std_logic;
	signal \259\ : std_logic;
	signal \244\ : std_logic;
	signal \256\ : std_logic;
	signal \246\ : std_logic;
	signal \249\ : std_logic;
	signal \247\ : std_logic;
	signal \248\ : std_logic;
	signal \236\ : std_logic;
	signal \250\ : std_logic;
	signal \243\ : std_logic;
	signal \239\ : std_logic;
	signal \245\ : std_logic;
	signal \251\ : std_logic;
	signal \PLD33/W\ : std_logic;
	signal \385\ : std_logic;
	signal \381\ : std_logic;
	signal \386\ : std_logic;
	signal \PLD33/R\ : std_logic;
	signal \398\ : std_logic;
	signal \401\ : std_logic;
	signal \382\ : std_logic;
	signal \396\ : std_logic;
	signal \397\ : std_logic;
	signal \384\ : std_logic;
	signal \399\ : std_logic;
	signal \402\ : std_logic;
	signal \403\ : std_logic;
	signal \388\ : std_logic;
	signal \400\ : std_logic;
	signal \390\ : std_logic;
	signal \393\ : std_logic;
	signal \391\ : std_logic;
	signal \392\ : std_logic;
	signal \380\ : std_logic;
	signal \394\ : std_logic;
	signal \387\ : std_logic;
	signal \383\ : std_logic;
	signal \389\ : std_logic;
	signal \395\ : std_logic;
	signal \PLD30/W\ : std_logic;
	signal \313\ : std_logic;
	signal \309\ : std_logic;
	signal \314\ : std_logic;
	signal \PLD30/R\ : std_logic;
	signal \326\ : std_logic;
	signal \329\ : std_logic;
	signal \310\ : std_logic;
	signal \324\ : std_logic;
	signal \325\ : std_logic;
	signal \312\ : std_logic;
	signal \327\ : std_logic;
	signal \330\ : std_logic;
	signal \331\ : std_logic;
	signal \316\ : std_logic;
	signal \328\ : std_logic;
	signal \318\ : std_logic;
	signal \321\ : std_logic;
	signal \319\ : std_logic;
	signal \320\ : std_logic;
	signal \308\ : std_logic;
	signal \322\ : std_logic;
	signal \315\ : std_logic;
	signal \311\ : std_logic;
	signal \317\ : std_logic;
	signal \323\ : std_logic;
	signal \PLD24/W\ : std_logic;
	signal \169\ : std_logic;
	signal \165\ : std_logic;
	signal \170\ : std_logic;
	signal \PLD24/R\ : std_logic;
	signal \182\ : std_logic;
	signal \185\ : std_logic;
	signal \166\ : std_logic;
	signal \180\ : std_logic;
	signal \181\ : std_logic;
	signal \168\ : std_logic;
	signal \183\ : std_logic;
	signal \186\ : std_logic;
	signal \187\ : std_logic;
	signal \172\ : std_logic;
	signal \184\ : std_logic;
	signal \174\ : std_logic;
	signal \177\ : std_logic;
	signal \175\ : std_logic;
	signal \176\ : std_logic;
	signal \164\ : std_logic;
	signal \178\ : std_logic;
	signal \171\ : std_logic;
	signal \167\ : std_logic;
	signal \173\ : std_logic;
	signal \179\ : std_logic;
	signal \PLD31/W\ : std_logic;
	signal \337\ : std_logic;
	signal \333\ : std_logic;
	signal \338\ : std_logic;
	signal \PLD31/R\ : std_logic;
	signal \350\ : std_logic;
	signal \353\ : std_logic;
	signal \334\ : std_logic;
	signal \348\ : std_logic;
	signal \349\ : std_logic;
	signal \336\ : std_logic;
	signal \351\ : std_logic;
	signal \354\ : std_logic;
	signal \355\ : std_logic;
	signal \340\ : std_logic;
	signal \352\ : std_logic;
	signal \342\ : std_logic;
	signal \345\ : std_logic;
	signal \343\ : std_logic;
	signal \344\ : std_logic;
	signal \332\ : std_logic;
	signal \346\ : std_logic;
	signal \339\ : std_logic;
	signal \335\ : std_logic;
	signal \341\ : std_logic;
	signal \347\ : std_logic;
	signal \PLD25/W\ : std_logic;
	signal \193\ : std_logic;
	signal \189\ : std_logic;
	signal \194\ : std_logic;
	signal \PLD25/R\ : std_logic;
	signal \206\ : std_logic;
	signal \209\ : std_logic;
	signal \190\ : std_logic;
	signal \204\ : std_logic;
	signal \205\ : std_logic;
	signal \192\ : std_logic;
	signal \207\ : std_logic;
	signal \210\ : std_logic;
	signal \211\ : std_logic;
	signal \196\ : std_logic;
	signal \208\ : std_logic;
	signal \198\ : std_logic;
	signal \201\ : std_logic;
	signal \199\ : std_logic;
	signal \200\ : std_logic;
	signal \188\ : std_logic;
	signal \202\ : std_logic;
	signal \195\ : std_logic;
	signal \191\ : std_logic;
	signal \197\ : std_logic;
	signal \203\ : std_logic;
	signal \PLD32/W\ : std_logic;
	signal \361\ : std_logic;
	signal \357\ : std_logic;
	signal \362\ : std_logic;
	signal \PLD32/R\ : std_logic;
	signal \374\ : std_logic;
	signal \377\ : std_logic;
	signal \358\ : std_logic;
	signal \372\ : std_logic;
	signal \373\ : std_logic;
	signal \360\ : std_logic;
	signal \375\ : std_logic;
	signal \378\ : std_logic;
	signal \379\ : std_logic;
	signal \364\ : std_logic;
	signal \376\ : std_logic;
	signal \366\ : std_logic;
	signal \369\ : std_logic;
	signal \367\ : std_logic;
	signal \368\ : std_logic;
	signal \356\ : std_logic;
	signal \370\ : std_logic;
	signal \363\ : std_logic;
	signal \359\ : std_logic;
	signal \365\ : std_logic;
	signal \371\ : std_logic;
	signal \PLD28/W\ : std_logic;
	signal \265\ : std_logic;
	signal \261\ : std_logic;
	signal \266\ : std_logic;
	signal \PLD28/R\ : std_logic;
	signal \278\ : std_logic;
	signal \281\ : std_logic;
	signal \262\ : std_logic;
	signal \276\ : std_logic;
	signal \277\ : std_logic;
	signal \264\ : std_logic;
	signal \279\ : std_logic;
	signal \282\ : std_logic;
	signal \283\ : std_logic;
	signal \268\ : std_logic;
	signal \280\ : std_logic;
	signal \270\ : std_logic;
	signal \273\ : std_logic;
	signal \271\ : std_logic;
	signal \272\ : std_logic;
	signal \260\ : std_logic;
	signal \274\ : std_logic;
	signal \267\ : std_logic;
	signal \263\ : std_logic;
	signal \269\ : std_logic;
	signal \275\ : std_logic;
	signal \PLD23/W\ : std_logic;
	signal \145\ : std_logic;
	signal \141\ : std_logic;
	signal \146\ : std_logic;
	signal \PLD23/R\ : std_logic;
	signal \158\ : std_logic;
	signal \161\ : std_logic;
	signal \142\ : std_logic;
	signal \156\ : std_logic;
	signal \157\ : std_logic;
	signal \144\ : std_logic;
	signal \159\ : std_logic;
	signal \162\ : std_logic;
	signal \163\ : std_logic;
	signal \148\ : std_logic;
	signal \160\ : std_logic;
	signal \150\ : std_logic;
	signal \153\ : std_logic;
	signal \151\ : std_logic;
	signal \152\ : std_logic;
	signal \140\ : std_logic;
	signal \154\ : std_logic;
	signal \147\ : std_logic;
	signal \143\ : std_logic;
	signal \149\ : std_logic;
	signal \155\ : std_logic;
	signal \PLD26/W\ : std_logic;
	signal \217\ : std_logic;
	signal \213\ : std_logic;
	signal \218\ : std_logic;
	signal \PLD26/R\ : std_logic;
	signal \230\ : std_logic;
	signal \233\ : std_logic;
	signal \214\ : std_logic;
	signal \228\ : std_logic;
	signal \229\ : std_logic;
	signal \216\ : std_logic;
	signal \231\ : std_logic;
	signal \234\ : std_logic;
	signal \235\ : std_logic;
	signal \220\ : std_logic;
	signal \232\ : std_logic;
	signal \222\ : std_logic;
	signal \225\ : std_logic;
	signal \223\ : std_logic;
	signal \224\ : std_logic;
	signal \212\ : std_logic;
	signal \226\ : std_logic;
	signal \219\ : std_logic;
	signal \215\ : std_logic;
	signal \221\ : std_logic;
	signal \227\ : std_logic;
	signal \PLD29/W\ : std_logic;
	signal \289\ : std_logic;
	signal \285\ : std_logic;
	signal \290\ : std_logic;
	signal \PLD29/R\ : std_logic;
	signal \302\ : std_logic;
	signal \305\ : std_logic;
	signal \286\ : std_logic;
	signal \300\ : std_logic;
	signal \301\ : std_logic;
	signal \288\ : std_logic;
	signal \303\ : std_logic;
	signal \306\ : std_logic;
	signal \307\ : std_logic;
	signal \292\ : std_logic;
	signal \304\ : std_logic;
	signal \294\ : std_logic;
	signal \297\ : std_logic;
	signal \295\ : std_logic;
	signal \296\ : std_logic;
	signal \284\ : std_logic;
	signal \298\ : std_logic;
	signal \291\ : std_logic;
	signal \287\ : std_logic;
	signal \293\ : std_logic;
	signal \299\ : std_logic;
	signal \37\ : std_logic;
	signal \34\ : std_logic;
	signal \39\ : std_logic;
	signal \36\ : std_logic;
	signal \35\ : std_logic;
	signal \38\ : std_logic;
	signal \424\ : std_logic;
	signal \8\ : std_logic;
	signal \24\ : std_logic;
	signal \20\ : std_logic;
	signal \23\ : std_logic;
	signal \12\ : std_logic;
	signal \25\ : std_logic;
	signal \3\ : std_logic;
	signal \2\ : std_logic;
	signal \22\ : std_logic;
	signal \6\ : std_logic;
	signal \14\ : std_logic;
	signal \10\ : std_logic;
	signal \19\ : std_logic;
	signal \5\ : std_logic;
	signal \11\ : std_logic;
	signal \17\ : std_logic;
	signal \15\ : std_logic;
	signal \4\ : std_logic;
	signal \13\ : std_logic;
	signal \16\ : std_logic;
	signal \9\ : std_logic;
	signal \18\ : std_logic;
	signal \7\ : std_logic;
	signal \21\ : std_logic;
	signal \PLD37/IO22\ : std_logic;
	signal \PLD37/IO21\ : std_logic;
	signal \452\ : std_logic;
	signal \451\ : std_logic;
	signal \PLD36/QE\ : std_logic;
	signal \453\ : std_logic;
	signal \PLD37/SS0\ : std_logic;
	signal \PLD36/QA\ : std_logic;
	signal \PLD37/SS1\ : std_logic;
	signal \PLD36/QG\ : std_logic;
	signal \PLD37/IO19\ : std_logic;
	signal \PLD36/QF\ : std_logic;
	signal \PLD36/QB\ : std_logic;
	signal \PLD36/QC\ : std_logic;
	signal \PLD36/QD\ : std_logic;
	signal \PLD37/IO20\ : std_logic;
	signal \450\ : std_logic;
	signal \425\ : std_logic;
	signal \427\ : std_logic;
	signal \433\ : std_logic;
	signal \428\ : std_logic;
	signal \432\ : std_logic;
	signal \426\ : std_logic;
	signal \431\ : std_logic;
	signal \429\ : std_logic;
	signal \435\ : std_logic;
	signal \434\ : std_logic;
	signal \430\ : std_logic;
	signal \PLD4/B4\ : std_logic;
	signal \PLD5/B10\ : std_logic;
	signal \PLD2/Q2\ : std_logic;
	signal \PLD3/B7\ : std_logic;
	signal \PLD7/B6\ : std_logic;
	signal \PLD4/OAGTB\ : std_logic;
	signal \PLD5/ALTB\ : std_logic;
	signal \PLD2/Q9\ : std_logic;
	signal \PLD2/Q5\ : std_logic;
	signal \PLD2/Q10\ : std_logic;
	signal \PLD2/Q1\ : std_logic;
	signal \PLD7/B5\ : std_logic;
	signal \PLD4/B5\ : std_logic;
	signal \PLD2/Q8\ : std_logic;
	signal \PLD2/Q7\ : std_logic;
	signal \PLD2/Q4\ : std_logic;
	signal \PLD2/clr\ : std_logic;
	signal \PLD2/Q6\ : std_logic;
	signal \PLD2/Q3\ : std_logic;
	signal \PLD3/B8\ : std_logic;
	signal \PLD5/OAGTB\ : std_logic;
	signal \PLD3/OAEQB\ : std_logic;
	signal \PLD7/OAEQB\ : std_logic;
	signal \PLD7/OALTB\ : std_logic;
	signal \PLD4/OAEQB\ : std_logic;
	signal \PLD3/OAGTB\ : std_logic;
	signal \PLD5/OAEQB\ : std_logic;
	signal \PLD4/OALTB\ : std_logic;
	signal \PLD5/OALTB\ : std_logic;
	signal \PLD3/OALTB\ : std_logic;
	signal \PLD7/OAGTB\ : std_logic;
	signal \PLD12/B9\ : std_logic;
	signal \PLD8/Q3\ : std_logic;
	signal \PLD10/B1\ : std_logic;
	signal \PLD8/Q2\ : std_logic;
	signal \PLD9/B5\ : std_logic;
	signal \PLD8/Q6\ : std_logic;
	signal \PLD11/B3\ : std_logic;
	signal \PLD10/OAEQB\ : std_logic;
	signal \PLD10/B2\ : std_logic;
	signal \PLD11/B1\ : std_logic;
	signal \PLD8/Q7\ : std_logic;
	signal \PLD8/Q4\ : std_logic;
	signal \PLD8/Q5\ : std_logic;
	signal \PLD12/AEQB\ : std_logic;
	signal \PLD9/B6\ : std_logic;
	signal \PLD8/Q8\ : std_logic;
	signal \PLD8/Q10\ : std_logic;
	signal \PLD8/Q9\ : std_logic;
	signal \PLD10/OALTB\ : std_logic;
	signal \PLD9/OALTB\ : std_logic;
	signal \PLD8/Q1\ : std_logic;
	signal \PLD11/OALTB\ : std_logic;
	signal \PLD11/OAGTB\ : std_logic;
	signal \PLD12/OALTB\ : std_logic;
	signal \PLD12/OAEQB\ : std_logic;
	signal \PLD9/OAGTB\ : std_logic;
	signal \PLD12/OAGTB\ : std_logic;
	signal \PLD10/OAGTB\ : std_logic;
	signal \PLD9/OAEQB\ : std_logic;
	signal \PLD11/OAEQB\ : std_logic;
	signal \PLD8/clr\ : std_logic;
	signal \79\ : std_logic;
	signal \80\ : std_logic;
	signal \82\ : std_logic;
	signal \78\ : std_logic;
	signal \81\ : std_logic;
	signal \46\ : std_logic;
	signal \47\ : std_logic;
	signal \49\ : std_logic;
	signal \45\ : std_logic;
	signal \48\ : std_logic;
	signal \103\ : std_logic;
	signal \100\ : std_logic;
	signal \102\ : std_logic;
	signal \98\ : std_logic;
	signal \101\ : std_logic;
	signal \99\ : std_logic;
	signal \97\ : std_logic;
	signal \89\ : std_logic;
	signal \86\ : std_logic;
	signal \88\ : std_logic;
	signal \84\ : std_logic;
	signal \87\ : std_logic;
	signal \85\ : std_logic;
	signal \83\ : std_logic;
	signal \96\ : std_logic;
	signal \93\ : std_logic;
	signal \95\ : std_logic;
	signal \91\ : std_logic;
	signal \94\ : std_logic;
	signal \92\ : std_logic;
	signal \90\ : std_logic;
	signal \110\ : std_logic;
	signal \107\ : std_logic;
	signal \109\ : std_logic;
	signal \105\ : std_logic;
	signal \108\ : std_logic;
	signal \106\ : std_logic;
	signal \104\ : std_logic;
	signal \63\ : std_logic;
	signal \60\ : std_logic;
	signal \62\ : std_logic;
	signal \58\ : std_logic;
	signal \61\ : std_logic;
	signal \59\ : std_logic;
	signal \57\ : std_logic;
	signal \56\ : std_logic;
	signal \53\ : std_logic;
	signal \55\ : std_logic;
	signal \51\ : std_logic;
	signal \54\ : std_logic;
	signal \52\ : std_logic;
	signal \50\ : std_logic;
	signal \77\ : std_logic;
	signal \74\ : std_logic;
	signal \76\ : std_logic;
	signal \72\ : std_logic;
	signal \75\ : std_logic;
	signal \73\ : std_logic;
	signal \71\ : std_logic;
	signal \70\ : std_logic;
	signal \67\ : std_logic;
	signal \69\ : std_logic;
	signal \65\ : std_logic;
	signal \68\ : std_logic;
	signal \66\ : std_logic;
	signal \64\ : std_logic;
	signal \PLD39/Q8\ : std_logic;
	signal \PLD39/Q9\ : std_logic;
	signal \PLD39/Q6\ : std_logic;
	signal \PLD39/Q10\ : std_logic;
	signal \436\ : std_logic;
	signal \438\ : std_logic;
	signal \439\ : std_logic;
	signal \PLD39/Q1\ : std_logic;
	signal \PLD39/Q5\ : std_logic;
	signal \PLD39/Q4\ : std_logic;
	signal \PLD39/clr\ : std_logic;
	signal \PLD39/Q2\ : std_logic;
	signal \437\ : std_logic;
	signal \PLD39/Q7\ : std_logic;
	signal \PLD39/Q3\ : std_logic;
	signal \473\ : std_logic;
	signal \474\ : std_logic;
	signal \476\ : std_logic;
	signal \472\ : std_logic;
	signal \475\ : std_logic;
	signal \PLD16/Q8\ : std_logic;
	signal \PLD16/Q9\ : std_logic;
	signal \PLD16/Q6\ : std_logic;
	signal \PLD16/Q10\ : std_logic;
	signal \121\ : std_logic;
	signal \123\ : std_logic;
	signal \124\ : std_logic;
	signal \PLD16/Q1\ : std_logic;
	signal \PLD16/Q5\ : std_logic;
	signal \PLD16/Q4\ : std_logic;
	signal \PLD16/clr\ : std_logic;
	signal \PLD16/Q2\ : std_logic;
	signal \122\ : std_logic;
	signal \PLD16/Q7\ : std_logic;
	signal \PLD16/Q3\ : std_logic;
	signal \456\ : std_logic;
	signal \457\ : std_logic;
	signal \459\ : std_logic;
	signal \455\ : std_logic;
	signal \458\ : std_logic;
begin
	CLK_AUTOBUF : AUTO_IBUF
		port map( I => CLK, O => \PLD13/CLK\ );
	Hsync_AUTOBUF : AUTO_OBUF
		port map( I => \PLD14/Hsync\, O => Hsync );
	Vsync_AUTOBUF : AUTO_OBUF
		port map( I => \PLD14/Vsync\, O => Vsync );
	BTNC_AUTOBUF : AUTO_IBUF
		port map( I => BTNC, O => \PLD21/WC\ );
	BTND_AUTOBUF : AUTO_IBUF
		port map( I => BTND, O => \PLD20/Up\ );
	BTNL_AUTOBUF : AUTO_IBUF
		port map( I => BTNL, O => \PLD20/Left\ );
	BTNR_AUTOBUF : AUTO_IBUF
		port map( I => BTNR, O => \PLD20/Right\ );
	BTNU_AUTOBUF : AUTO_IBUF
		port map( I => BTNU, O => \PLD20/Down\ );
	SW0_AUTOBUF : AUTO_IBUF
		port map( I => SW0, O => \PLD21/W_1\ );
	SW1_AUTOBUF : AUTO_IBUF
		port map( I => SW1, O => \PLD21/W_2\ );
	SW2_AUTOBUF : AUTO_IBUF
		port map( I => SW2, O => \PLD21/W_3\ );
	SW3_AUTOBUF : AUTO_IBUF
		port map( I => SW3, O => \PLD21/W_4\ );
	SW4_AUTOBUF : AUTO_IBUF
		port map( I => SW4, O => \PLD21/W_5\ );
	SW5_AUTOBUF : AUTO_IBUF
		port map( I => SW5, O => \PLD21/W_6\ );
	SW6_AUTOBUF : AUTO_IBUF
		port map( I => SW6, O => \PLD21/W_7\ );
	SW7_AUTOBUF : AUTO_IBUF
		port map( I => SW7, O => \PLD21/W_8\ );
	SW8_AUTOBUF : AUTO_IBUF
		port map( I => SW8, O => \PLD21/W_9\ );
	SW9_AUTOBUF : AUTO_IBUF
		port map( I => SW9, O => \PLD21/W_10\ );
	SW10_AUTOBUF : AUTO_IBUF
		port map( I => SW10, O => \PLD21/W_11\ );
	SW11_AUTOBUF : AUTO_IBUF
		port map( I => SW11, O => \PLD21/W_12\ );
	vgaBlue0_AUTOBUF : AUTO_OBUF
		port map( I => \PLD34/Q1\, O => vgaBlue0 );
	vgaBlue1_AUTOBUF : AUTO_OBUF
		port map( I => \PLD34/Q2\, O => vgaBlue1 );
	vgaBlue2_AUTOBUF : AUTO_OBUF
		port map( I => \PLD34/Q3\, O => vgaBlue2 );
	vgaBlue3_AUTOBUF : AUTO_OBUF
		port map( I => \PLD34/Q4\, O => vgaBlue3 );
	vgaGreen0_AUTOBUF : AUTO_OBUF
		port map( I => \PLD34/Q5\, O => vgaGreen0 );
	vgaGreen1_AUTOBUF : AUTO_OBUF
		port map( I => \PLD34/Q6\, O => vgaGreen1 );
	vgaGreen2_AUTOBUF : AUTO_OBUF
		port map( I => \PLD34/Q7\, O => vgaGreen2 );
	vgaGreen3_AUTOBUF : AUTO_OBUF
		port map( I => \PLD34/Q8\, O => vgaGreen3 );
	vgaRed0_AUTOBUF : AUTO_OBUF
		port map( I => \PLD34/Q9\, O => vgaRed0 );
	vgaRed1_AUTOBUF : AUTO_OBUF
		port map( I => \PLD34/Q10\, O => vgaRed1 );
	vgaRed2_AUTOBUF : AUTO_OBUF
		port map( I => \PLD34/Q11\, O => vgaRed2 );
	vgaRed3_AUTOBUF : AUTO_OBUF
		port map( I => \PLD34/Q12\, O => vgaRed3 );
	CA_AUTOBUF : AUTO_OBUF
		port map( I => \PLD35/CA\, O => CA );
	CB_AUTOBUF : AUTO_OBUF
		port map( I => \PLD35/CB\, O => CB );
	CC_AUTOBUF : AUTO_OBUF
		port map( I => \PLD35/CC\, O => CC );
	CD_AUTOBUF : AUTO_OBUF
		port map( I => \PLD35/CD\, O => CD );
	CE_AUTOBUF : AUTO_OBUF
		port map( I => \PLD35/CE\, O => CE );
	CF_AUTOBUF : AUTO_OBUF
		port map( I => \PLD35/CF\, O => CF );
	CG_AUTOBUF : AUTO_OBUF
		port map( I => \PLD35/CG\, O => CG );
	AN1_AUTOBUF : AUTO_OBUF
		port map( I => \PLD35/AN1\, O => AN1 );
	AN2_AUTOBUF : AUTO_OBUF
		port map( I => \PLD35/AN2\, O => AN2 );
	AN3_AUTOBUF : AUTO_OBUF
		port map( I => \PLD35/AN3\, O => AN3 );
	AN0_AUTOBUF : AUTO_OBUF
		port map( I => \PLD35/AN0\, O => AN0 );
	U68 : AND2_NI
		port map( A => \PLD14/HBLANK\, B => \PLD14/VBLANK\, Y => \PLD21/RE\ );
	U631 : AND2_NI
		port map( A => \PLD21/Write_Read_Address_EQ\, B => \PLD13/JA2\, Y => \PLD34/Flashing\ );
	U684 : DIGITAL_LOW_NI
		port map( Y => \PLD35/SW2\ );
	U663 : DIGITAL_HIGH_NI
		port map( Y => \PLD35/Row_Col_EN\ );
	U89 : CNTR_4BIN_S_NI
		port map( QA => open, QB => \PLD15/HCLOCK\, QC => open, QD => open, RCO => open, A => \1\, B => \1\, C => \1\, D => \1\, ENP => \2\, ENT => \2\, LOAD => \2\, CLR => \2\, CLK => \PLD13/CLK\ );
	U90 : DIGITAL_HIGH_NI
		port map( Y => \2\ );
	U92 : DIGITAL_HIGH_NI
		port map( Y => \3\ );
	U103 : CNTR_BCD_S_NI
		port map( QA => open, QB => open, QC => open, QD => open, RCO => \4\, A => \5\, B => \5\, C => \5\, D => \5\, ENP => \3\, ENT => \3\, LOAD => \3\, CLR => \3\, CLK => \PLD13/CLK\ );
	U104 : DIGITAL_HIGH_NI
		port map( Y => \6\ );
	U105 : CNTR_BCD_S_NI
		port map( QA => open, QB => open, QC => open, QD => open, RCO => \7\, A => \8\, B => \8\, C => \8\, D => \8\, ENP => \6\, ENT => \6\, LOAD => \6\, CLR => \6\, CLK => \4\ );
	U106 : CNTR_BCD_S_NI
		port map( QA => open, QB => open, QC => open, QD => open, RCO => \9\, A => \10\, B => \10\, C => \10\, D => \10\, ENP => \11\, ENT => \11\, LOAD => \11\, CLR => \11\, CLK => \7\ );
	U107 : DIGITAL_HIGH_NI
		port map( Y => \12\ );
	U108 : CNTR_BCD_S_NI
		port map( QA => open, QB => open, QC => open, QD => open, RCO => \13\, A => \14\, B => \14\, C => \14\, D => \14\, ENP => \12\, ENT => \12\, LOAD => \12\, CLR => \12\, CLK => \15\ );
	U109 : DIGITAL_HIGH_NI
		port map( Y => \16\ );
	U110 : FF_T_CLR_CO_NI
		port map( T => \12\, Q => \PLD13/JA1\, Qneg => open, CLR => \12\, CLK => \13\ );
	U111 : CNTR_BCD_S_NI
		port map( QA => open, QB => open, QC => open, QD => open, RCO => \15\, A => \17\, B => \17\, C => \17\, D => \17\, ENP => \16\, ENT => \16\, LOAD => \16\, CLR => \16\, CLK => \9\ );
	U112 : DIGITAL_LOW_NI
		port map( Y => \1\ );
	U113 : DIGITAL_LOW_NI
		port map( Y => \5\ );
	U114 : DIGITAL_LOW_NI
		port map( Y => \8\ );
	U115 : DIGITAL_LOW_NI
		port map( Y => \17\ );
	U116 : DIGITAL_LOW_NI
		port map( Y => \14\ );
	U117 : DIGITAL_HIGH_NI
		port map( Y => \11\ );
	U118 : DIGITAL_LOW_NI
		port map( Y => \10\ );
	U119 : CNTR_BCD_S_NI
		port map( QA => open, QB => open, QC => open, QD => open, RCO => \18\, A => \19\, B => \19\, C => \19\, D => \19\, ENP => \20\, ENT => \20\, LOAD => \20\, CLR => \20\, CLK => \PLD13/JA1\ );
	U120 : CNTR_BCD_S_NI
		port map( QA => open, QB => open, QC => open, QD => open, RCO => \21\, A => \22\, B => \22\, C => \22\, D => \22\, ENP => \23\, ENT => \23\, LOAD => \23\, CLR => \23\, CLK => \18\ );
	U121 : CNTR_BCD_S_NI
		port map( QA => open, QB => open, QC => open, QD => open, RCO => \PLD13/JA2\, A => \24\, B => \24\, C => \24\, D => \24\, ENP => \25\, ENT => \25\, LOAD => \25\, CLR => \25\, CLK => \21\ );
	U122 : DIGITAL_HIGH_NI
		port map( Y => \20\ );
	U123 : DIGITAL_LOW_NI
		port map( Y => \19\ );
	U124 : DIGITAL_LOW_NI
		port map( Y => \22\ );
	U125 : DIGITAL_HIGH_NI
		port map( Y => \23\ );
	U126 : DIGITAL_HIGH_NI
		port map( Y => \25\ );
	U127 : DIGITAL_LOW_NI
		port map( Y => \24\ );
	U139 : BUF_INV_NI
		port map( Y => \PLD38/Clear\, A => \PLD14/HBLANK\ );
	U140 : BUF_INV_NI
		port map( Y => \PLD17/Clear\, A => \PLD14/VBLANK\ );
	U605 : DIGITAL_LOW_NI
		port map( Y => \PLD22/Previous_1\ );
	U606 : DEC2_4_NI
		port map( Y0 => \407\, Y1 => \409\, Y2 => \411\, Y3 => \413\, A => \PLD21/WCB_1\, B => \PLD21/WCB_2\, EN => \404\ );
	U607 : DEC2_4_NI
		port map( Y0 => \406\, Y1 => \408\, Y2 => \410\, Y3 => \412\, A => \PLD21/RCB_1\, B => \PLD21/RCB_2\, EN => \405\ );
	U608 : DIGITAL_LOW_NI
		port map( Y => \404\ );
	U609 : DIGITAL_LOW_NI
		port map( Y => \405\ );
	U610 : DEC2_4_NI
		port map( Y0 => \416\, Y1 => \418\, Y2 => \420\, Y3 => open, A => \PLD21/WRB_1\, B => \PLD21/WRB_2\, EN => \414\ );
	U611 : DEC2_4_NI
		port map( Y0 => \417\, Y1 => \419\, Y2 => \421\, Y3 => open, A => \PLD21/RRB_1\, B => \PLD21/RRB_2\, EN => \415\ );
	U612 : BUF_INV_NI
		port map( Y => \PLD22/Read_EN_Col\, A => \406\ );
	U613 : BUF_INV_NI
		port map( Y => \PLD22/Write_EN_Col\, A => \407\ );
	U614 : BUF_INV_NI
		port map( Y => \PLD23/Read_EN_Col\, A => \408\ );
	U615 : BUF_INV_NI
		port map( Y => \PLD23/Write_EN_Col\, A => \409\ );
	U616 : BUF_INV_NI
		port map( Y => \PLD24/Read_EN_Col\, A => \410\ );
	U617 : BUF_INV_NI
		port map( Y => \PLD24/Write_EN_Col\, A => \411\ );
	U618 : BUF_INV_NI
		port map( Y => \PLD25/Read_EN_Col\, A => \412\ );
	U619 : BUF_INV_NI
		port map( Y => \PLD25/Write_EN_Col\, A => \413\ );
	U620 : BUF_INV_NI
		port map( Y => \PLD22/Read_EN_Row\, A => \417\ );
	U621 : BUF_INV_NI
		port map( Y => \PLD22/Write_EN_Row\, A => \416\ );
	U622 : BUF_INV_NI
		port map( Y => \PLD26/Write_EN_Row\, A => \418\ );
	U623 : BUF_INV_NI
		port map( Y => \PLD26/Read_EN_Row\, A => \419\ );
	U624 : BUF_INV_NI
		port map( Y => \PLD30/Write_EN_Row\, A => \420\ );
	U625 : BUF_INV_NI
		port map( Y => \PLD30/Read_EN_Row\, A => \421\ );
	U628 : DIGITAL_LOW_NI
		port map( Y => \414\ );
	U629 : DIGITAL_LOW_NI
		port map( Y => \415\ );
	U626 : COMP_4_NI
		port map( A2 => \PLD21/WCB_2\, B2 => \PLD21/RCB_2\, A1 => \PLD21/WRB_1\, B1 => \PLD21/RRB_1\, OAGTB => open, A0 => \PLD21/WRB_2\, B0 => \PLD21/RRB_2\, A3 => \PLD21/WCB_1\, B3 => \PLD21/RCB_1\, OAEQB => \PLD21/Write_Read_Address_EQ\, OALTB => open, AEQB => \423\, ALTB => \422\, AGTB => \422\ );
	U627 : DIGITAL_LOW_NI
		port map( Y => \422\ );
	U630 : DIGITAL_HIGH_NI
		port map( Y => \423\ );
	U141 : CNTR_4BIN_SU_D_NI
		port map( A => \34\, B => \34\, C => \34\, D => \34\, UD => \PLD20/Left\, QA => \PLD21/WCB_1\, QB => \PLD21/WCB_2\, QC => open, QD => open, CTEN => \35\, LOAD => \34\, RCO => open, MAXMIN => open, CLK => \36\ );
	U142 : CNTR_4BIN_SU_D_NI
		port map( A => \37\, B => \PLD20/Down\, C => \37\, D => \37\, UD => \PLD20/Down\, QA => \PLD21/WRB_1\, QB => \PLD21/WRB_2\, QC => open, QD => open, CTEN => \37\, LOAD => \38\, RCO => open, MAXMIN => open, CLK => \39\ );
	U143 : OR2_NI
		port map( A => \PLD20/Down\, B => \PLD20/Up\, Y => \39\ );
	U144 : OR2_NI
		port map( A => \PLD20/Left\, B => \PLD20/Right\, Y => \36\ );
	U145 : DIGITAL_HIGH_NI
		port map( Y => \34\ );
	U146 : DIGITAL_LOW_NI
		port map( Y => \37\ );
	U147 : DIGITAL_LOW_NI
		port map( Y => \35\ );
	U148 : NAND2_NI
		port map( A => \PLD21/WRB_1\, B => \PLD21/WRB_2\, Y => \38\ );
	U632 : AND2_NI
		port map( A => \PLD21/RE\, B => \PLD34/Flashing\, Y => \424\ );
	U633 : XOR2_NI
		port map( A => \PLD21/Read_12\, B => \424\, Y => \PLD34/Q12\ );
	U634 : XOR2_NI
		port map( A => \PLD21/Read_11\, B => \424\, Y => \PLD34/Q11\ );
	U635 : XOR2_NI
		port map( A => \PLD21/Read_10\, B => \424\, Y => \PLD34/Q10\ );
	U636 : XOR2_NI
		port map( A => \PLD21/Read_9\, B => \424\, Y => \PLD34/Q9\ );
	U637 : XOR2_NI
		port map( A => \PLD34/Green4\, B => \424\, Y => \PLD34/Q8\ );
	U638 : XOR2_NI
		port map( A => \PLD21/Read_7\, B => \424\, Y => \PLD34/Q7\ );
	U639 : XOR2_NI
		port map( A => \PLD21/Read_6\, B => \424\, Y => \PLD34/Q6\ );
	U640 : XOR2_NI
		port map( A => \PLD21/Read_5\, B => \424\, Y => \PLD34/Q5\ );
	U641 : XOR2_NI
		port map( A => \PLD21/Read_4\, B => \424\, Y => \PLD34/Q4\ );
	U642 : XOR2_NI
		port map( A => \PLD21/Read_3\, B => \424\, Y => \PLD34/Q3\ );
	U643 : XOR2_NI
		port map( A => \PLD21/Read_2\, B => \424\, Y => \PLD34/Q2\ );
	U644 : XOR2_NI
		port map( A => \PLD21/Read_1\, B => \424\, Y => \PLD34/Q1\ );
	U673 : DEC_BCD_7_NI
		port map( A => \PLD37/IO19\, B => \PLD37/IO20\, C => \PLD37/IO21\, D => \PLD37/IO22\, Y0 => \PLD36/QA\, Y3 => \PLD36/QD\, Y4 => \PLD36/QE\, Y5 => \PLD36/QF\, Y2 => \PLD36/QC\, Y1 => \PLD36/QB\, Y6 => \PLD36/QG\, LT => \453\, RBI => \453\, BI => \453\ );
	U679 : DIGITAL_LOW_NI
		port map( Y => \451\ );
	U680 : DIGITAL_HIGH_NI
		port map( Y => \452\ );
	U681 : CNTR_4BIN_S_NI
		port map( QA => \PLD37/SS0\, QB => \PLD37/SS1\, QC => open, QD => open, RCO => open, A => \451\, B => \451\, C => \451\, D => \451\, ENP => \452\, ENT => \452\, LOAD => \452\, CLR => \452\, CLK => \PLD13/JA1\ );
	U682 : DEC2_4_NI
		port map( Y0 => \PLD35/AN0\, Y1 => \PLD35/AN1\, Y2 => \PLD35/AN2\, Y3 => \PLD35/AN3\, A => \PLD37/SS0\, B => \PLD37/SS1\, EN => \451\ );
	U683 : DIGITAL_HIGH_NI
		port map( Y => \453\ );
	U11 : DIGITAL_LOW_NI
		port map( Y => \PLD3/B7\ );
	U12 : DIGITAL_HIGH_NI
		port map( Y => \PLD3/B8\ );
	U13 : DIGITAL_HIGH_NI
		port map( Y => \PLD4/B5\ );
	U14 : DIGITAL_LOW_NI
		port map( Y => \PLD4/B4\ );
	U15 : DIGITAL_HIGH_NI
		port map( Y => \PLD5/B10\ );
	U16 : DIGITAL_LOW_NI
		port map( Y => \PLD5/ALTB\ );
	U21 : BUF_NI
		port map( Y => \PLD14/HC_1\, A => \PLD2/Q1\ );
	U22 : BUF_NI
		port map( Y => \PLD14/HC_2\, A => \PLD2/Q2\ );
	U23 : BUF_NI
		port map( Y => \PLD14/HC_3\, A => \PLD2/Q3\ );
	U24 : BUF_NI
		port map( Y => \PLD14/HC_4\, A => \PLD2/Q4\ );
	U29 : BUF_NI
		port map( Y => \PLD14/HC_5\, A => \PLD2/Q5\ );
	U30 : BUF_NI
		port map( Y => \PLD14/HC_6\, A => \PLD2/Q6\ );
	U31 : BUF_NI
		port map( Y => \PLD14/HC_7\, A => \PLD2/Q7\ );
	U32 : BUF_NI
		port map( Y => \PLD14/HC_8\, A => \PLD2/Q8\ );
	U33 : BUF_NI
		port map( Y => \PLD14/HC_9\, A => \PLD2/Q9\ );
	U34 : BUF_NI
		port map( Y => \PLD14/HC_10\, A => \PLD2/Q10\ );
	U35 : DIGITAL_HIGH_NI
		port map( Y => \PLD7/B6\ );
	U36 : DIGITAL_LOW_NI
		port map( Y => \PLD7/B5\ );
	U37 : FF_JK_PSCLR_CO_NI
		port map( J => \PLD5/OAEQB\, Q => \PLD14/Hsync\, Qneg => open, K => \PLD4/OAEQB\, CLR => \PLD7/B6\, CLK => \PLD15/HCLOCK\, PR => \PLD7/B6\ );
	U38 : FF_JK_PSCLR_CO_NI
		port map( J => \PLD7/OAEQB\, Q => \PLD14/HBLANK\, Qneg => open, K => \PLD3/OAEQB\, CLR => \PLD7/B6\, CLK => \PLD15/HCLOCK\, PR => \PLD7/B6\ );
	U1 : AND4_NI
		port map( A => \PLD2/Q10\, B => \PLD2/Q9\, C => \PLD2/Q6\, D => \PLD2/Q1\, Y => \PLD2/clr\ );
	U2 : DIGITAL_LOW_NI
		port map( Y => \PLD9/B5\ );
	U3 : DIGITAL_HIGH_NI
		port map( Y => \PLD9/B6\ );
	U4 : FF_JK_PSCLR_CO_NI
		port map( J => \PLD11/OAEQB\, Q => \PLD14/Vsync\, Qneg => open, K => \PLD10/OAEQB\, CLR => \PLD12/AEQB\, CLK => \PLD14/Hsync\, PR => \PLD12/AEQB\ );
	U39 : DIGITAL_LOW_NI
		port map( Y => \PLD10/B1\ );
	U40 : DIGITAL_HIGH_NI
		port map( Y => \PLD10/B2\ );
	U41 : DIGITAL_LOW_NI
		port map( Y => \PLD11/B1\ );
	U42 : DIGITAL_HIGH_NI
		port map( Y => \PLD11/B3\ );
	U43 : DIGITAL_LOW_NI
		port map( Y => \PLD12/B9\ );
	U44 : DIGITAL_HIGH_NI
		port map( Y => \PLD12/AEQB\ );
	U45 : BUF_NI
		port map( Y => \PLD14/VC_1\, A => \PLD8/Q1\ );
	U46 : BUF_NI
		port map( Y => \PLD14/VC_2\, A => \PLD8/Q2\ );
	U47 : BUF_NI
		port map( Y => \PLD14/VC_3\, A => \PLD8/Q3\ );
	U48 : BUF_NI
		port map( Y => \PLD14/VC_4\, A => \PLD8/Q4\ );
	U49 : BUF_NI
		port map( Y => \PLD14/VC_5\, A => \PLD8/Q5\ );
	U50 : BUF_NI
		port map( Y => \PLD14/VC_6\, A => \PLD8/Q6\ );
	U51 : BUF_NI
		port map( Y => \PLD14/VC_7\, A => \PLD8/Q7\ );
	U56 : BUF_NI
		port map( Y => \PLD14/VC_8\, A => \PLD8/Q8\ );
	U17 : BUF_NI
		port map( Y => \PLD14/VC_9\, A => \PLD8/Q9\ );
	U18 : FF_JK_PSCLR_CO_NI
		port map( J => \PLD12/OAEQB\, Q => \PLD14/VBLANK\, Qneg => open, K => \PLD9/OAEQB\, CLR => \PLD12/AEQB\, CLK => \PLD14/Hsync\, PR => \PLD12/AEQB\ );
	U70 : AND3_NI
		port map( A => \PLD8/Q10\, B => \PLD8/Q4\, C => \PLD8/Q2\, Y => \PLD8/clr\ );
	U670 : CNTR_4BIN_ASCLR_NI
		port map( QA => \PLD21/RCB_1\, QB => \PLD21/RCB_2\, QC => open, QD => open, RCO => open, A => \436\, B => \436\, C => \436\, D => \436\, ENP => \436\, ENT => \436\, LOAD => \436\, CLR => \437\, CLK => \438\ );
	U672 : AND2_NI
		port map( A => \PLD39/Q1\, B => \438\, Y => \439\ );
	U685 : OR2_NI
		port map( A => \439\, B => \PLD38/Clear\, Y => \PLD39/clr\ );
	U686 : DIGITAL_HIGH_NI
		port map( Y => \436\ );
	U687 : BUF_INV_NI
		port map( Y => \437\, A => \PLD38/Clear\ );
	U128 : AND2_NI
		port map( A => \PLD39/Q6\, B => \PLD39/Q8\, Y => \438\ );
	U69 : CNTR_4BIN_ASCLR_NI
		port map( QA => \PLD21/RRB_1\, QB => \PLD21/RRB_2\, QC => open, QD => open, RCO => open, A => \121\, B => \121\, C => \121\, D => \121\, ENP => \121\, ENT => \121\, LOAD => \121\, CLR => \122\, CLK => \123\ );
	U72 : AND2_NI
		port map( A => \PLD16/Q1\, B => \123\, Y => \124\ );
	U73 : OR2_NI
		port map( A => \124\, B => \PLD17/Clear\, Y => \PLD16/clr\ );
	U74 : DIGITAL_HIGH_NI
		port map( Y => \121\ );
	U75 : BUF_INV_NI
		port map( Y => \122\, A => \PLD17/Clear\ );
	U129 : AND2_NI
		port map( A => \PLD16/Q6\, B => \PLD16/Q8\, Y => \123\ );
	U149 : FF_D_CO_NI
		port map( D => \PLD21/W_1\, Q => \40\, CLK => \PLD22/W\, Qneg => open );
	U150 : FF_D_CO_NI
		port map( D => \PLD21/W_2\, Q => \41\, CLK => \PLD22/W\, Qneg => open );
	U151 : FF_D_CO_NI
		port map( D => \PLD21/W_3\, Q => \42\, CLK => \PLD22/W\, Qneg => open );
	U152 : FF_D_CO_NI
		port map( D => \PLD21/W_4\, Q => \43\, CLK => \PLD22/W\, Qneg => open );
	U153 : FF_D_CO_NI
		port map( D => \PLD21/W_5\, Q => \44\, CLK => \PLD22/W\, Qneg => open );
	U154 : FF_D_CO_NI
		port map( D => \PLD21/W_6\, Q => \111\, CLK => \PLD22/W\, Qneg => open );
	U155 : FF_D_CO_NI
		port map( D => \PLD21/W_7\, Q => \112\, CLK => \PLD22/W\, Qneg => open );
	U156 : FF_D_CO_NI
		port map( D => \PLD21/W_8\, Q => \113\, CLK => \PLD22/W\, Qneg => open );
	U157 : FF_D_CO_NI
		port map( D => \PLD21/W_9\, Q => \114\, CLK => \PLD22/W\, Qneg => open );
	U158 : FF_D_CO_NI
		port map( D => \PLD21/W_10\, Q => \125\, CLK => \PLD22/W\, Qneg => open );
	U159 : FF_D_CO_NI
		port map( D => \PLD21/W_11\, Q => \126\, CLK => \PLD22/W\, Qneg => open );
	U160 : FF_D_CO_NI
		port map( D => \PLD21/W_12\, Q => \127\, CLK => \PLD22/W\, Qneg => open );
	U161 : AND3_NI
		port map( A => \PLD21/RE\, B => \PLD22/Read_EN_Col\, C => \PLD22/Read_EN_Row\, Y => \PLD22/R\ );
	U162 : AND3_NI
		port map( A => \PLD21/WC\, B => \PLD22/Write_EN_Col\, C => \PLD22/Write_EN_Row\, Y => \PLD22/W\ );
	U163 : AND2_NI
		port map( A => \PLD22/R\, B => \40\, Y => \128\ );
	U164 : AND2_NI
		port map( A => \PLD22/R\, B => \41\, Y => \129\ );
	U165 : OR2_NI
		port map( A => \PLD22/Previous_1\, B => \128\, Y => \PLD22/Read_1\ );
	U166 : OR2_NI
		port map( A => \PLD22/Previous_1\, B => \129\, Y => \PLD22/Read_2\ );
	U167 : AND2_NI
		port map( A => \PLD22/R\, B => \42\, Y => \130\ );
	U168 : OR2_NI
		port map( A => \PLD22/Previous_1\, B => \130\, Y => \PLD22/Read_3\ );
	U169 : AND2_NI
		port map( A => \PLD22/R\, B => \43\, Y => \131\ );
	U170 : OR2_NI
		port map( A => \PLD22/Previous_1\, B => \131\, Y => \PLD22/Read_4\ );
	U171 : AND2_NI
		port map( A => \PLD22/R\, B => \44\, Y => \132\ );
	U172 : OR2_NI
		port map( A => \PLD22/Previous_1\, B => \132\, Y => \PLD22/Read_5\ );
	U173 : AND2_NI
		port map( A => \PLD22/R\, B => \111\, Y => \133\ );
	U174 : AND2_NI
		port map( A => \PLD22/R\, B => \112\, Y => \134\ );
	U175 : AND2_NI
		port map( A => \PLD22/R\, B => \113\, Y => \135\ );
	U176 : AND2_NI
		port map( A => \PLD22/R\, B => \114\, Y => \136\ );
	U177 : AND2_NI
		port map( A => \PLD22/R\, B => \125\, Y => \137\ );
	U178 : AND2_NI
		port map( A => \PLD22/R\, B => \126\, Y => \138\ );
	U179 : AND2_NI
		port map( A => \PLD22/R\, B => \127\, Y => \139\ );
	U180 : OR2_NI
		port map( A => \PLD22/Previous_1\, B => \133\, Y => \PLD22/Read_6\ );
	U181 : OR2_NI
		port map( A => \PLD22/Previous_1\, B => \134\, Y => \PLD22/Read_7\ );
	U182 : OR2_NI
		port map( A => \PLD22/Previous_1\, B => \135\, Y => \PLD22/Read_8\ );
	U183 : OR2_NI
		port map( A => \PLD22/Previous_1\, B => \136\, Y => \PLD22/Read_9\ );
	U184 : OR2_NI
		port map( A => \PLD22/Previous_1\, B => \137\, Y => \PLD22/Read_10\ );
	U185 : OR2_NI
		port map( A => \PLD22/Previous_1\, B => \138\, Y => \PLD22/Read_11\ );
	U186 : OR2_NI
		port map( A => \PLD22/Previous_1\, B => \139\, Y => \PLD22/Read_12\ );
	U187 : FF_D_CO_NI
		port map( D => \PLD21/W_1\, Q => \140\, CLK => \PLD23/W\, Qneg => open );
	U188 : FF_D_CO_NI
		port map( D => \PLD21/W_2\, Q => \141\, CLK => \PLD23/W\, Qneg => open );
	U189 : FF_D_CO_NI
		port map( D => \PLD21/W_3\, Q => \142\, CLK => \PLD23/W\, Qneg => open );
	U190 : FF_D_CO_NI
		port map( D => \PLD21/W_4\, Q => \143\, CLK => \PLD23/W\, Qneg => open );
	U191 : FF_D_CO_NI
		port map( D => \PLD21/W_5\, Q => \144\, CLK => \PLD23/W\, Qneg => open );
	U192 : FF_D_CO_NI
		port map( D => \PLD21/W_6\, Q => \145\, CLK => \PLD23/W\, Qneg => open );
	U193 : FF_D_CO_NI
		port map( D => \PLD21/W_7\, Q => \146\, CLK => \PLD23/W\, Qneg => open );
	U194 : FF_D_CO_NI
		port map( D => \PLD21/W_8\, Q => \147\, CLK => \PLD23/W\, Qneg => open );
	U195 : FF_D_CO_NI
		port map( D => \PLD21/W_9\, Q => \148\, CLK => \PLD23/W\, Qneg => open );
	U196 : FF_D_CO_NI
		port map( D => \PLD21/W_10\, Q => \149\, CLK => \PLD23/W\, Qneg => open );
	U197 : FF_D_CO_NI
		port map( D => \PLD21/W_11\, Q => \150\, CLK => \PLD23/W\, Qneg => open );
	U198 : FF_D_CO_NI
		port map( D => \PLD21/W_12\, Q => \151\, CLK => \PLD23/W\, Qneg => open );
	U199 : AND3_NI
		port map( A => \PLD21/RE\, B => \PLD23/Read_EN_Col\, C => \PLD22/Read_EN_Row\, Y => \PLD23/R\ );
	U200 : AND3_NI
		port map( A => \PLD21/WC\, B => \PLD23/Write_EN_Col\, C => \PLD22/Write_EN_Row\, Y => \PLD23/W\ );
	U201 : AND2_NI
		port map( A => \PLD23/R\, B => \140\, Y => \152\ );
	U202 : AND2_NI
		port map( A => \PLD23/R\, B => \141\, Y => \153\ );
	U203 : OR2_NI
		port map( A => \PLD22/Read_1\, B => \152\, Y => \PLD23/Read_1\ );
	U204 : OR2_NI
		port map( A => \PLD22/Read_2\, B => \153\, Y => \PLD23/Read_2\ );
	U205 : AND2_NI
		port map( A => \PLD23/R\, B => \142\, Y => \154\ );
	U206 : OR2_NI
		port map( A => \PLD22/Read_3\, B => \154\, Y => \PLD23/Read_3\ );
	U207 : AND2_NI
		port map( A => \PLD23/R\, B => \143\, Y => \155\ );
	U208 : OR2_NI
		port map( A => \PLD22/Read_4\, B => \155\, Y => \PLD23/Read_4\ );
	U209 : AND2_NI
		port map( A => \PLD23/R\, B => \144\, Y => \156\ );
	U210 : OR2_NI
		port map( A => \PLD22/Read_5\, B => \156\, Y => \PLD23/Read_5\ );
	U211 : AND2_NI
		port map( A => \PLD23/R\, B => \145\, Y => \157\ );
	U212 : AND2_NI
		port map( A => \PLD23/R\, B => \146\, Y => \158\ );
	U213 : AND2_NI
		port map( A => \PLD23/R\, B => \147\, Y => \159\ );
	U214 : AND2_NI
		port map( A => \PLD23/R\, B => \148\, Y => \160\ );
	U215 : AND2_NI
		port map( A => \PLD23/R\, B => \149\, Y => \161\ );
	U216 : AND2_NI
		port map( A => \PLD23/R\, B => \150\, Y => \162\ );
	U217 : AND2_NI
		port map( A => \PLD23/R\, B => \151\, Y => \163\ );
	U218 : OR2_NI
		port map( A => \PLD22/Read_6\, B => \157\, Y => \PLD23/Read_6\ );
	U219 : OR2_NI
		port map( A => \PLD22/Read_7\, B => \158\, Y => \PLD23/Read_7\ );
	U220 : OR2_NI
		port map( A => \PLD22/Read_8\, B => \159\, Y => \PLD23/Read_8\ );
	U221 : OR2_NI
		port map( A => \PLD22/Read_9\, B => \160\, Y => \PLD23/Read_9\ );
	U222 : OR2_NI
		port map( A => \PLD22/Read_10\, B => \161\, Y => \PLD23/Read_10\ );
	U223 : OR2_NI
		port map( A => \PLD22/Read_11\, B => \162\, Y => \PLD23/Read_11\ );
	U224 : OR2_NI
		port map( A => \PLD22/Read_12\, B => \163\, Y => \PLD23/Read_12\ );
	U225 : FF_D_CO_NI
		port map( D => \PLD21/W_1\, Q => \164\, CLK => \PLD24/W\, Qneg => open );
	U226 : FF_D_CO_NI
		port map( D => \PLD21/W_2\, Q => \165\, CLK => \PLD24/W\, Qneg => open );
	U227 : FF_D_CO_NI
		port map( D => \PLD21/W_3\, Q => \166\, CLK => \PLD24/W\, Qneg => open );
	U228 : FF_D_CO_NI
		port map( D => \PLD21/W_4\, Q => \167\, CLK => \PLD24/W\, Qneg => open );
	U229 : FF_D_CO_NI
		port map( D => \PLD21/W_5\, Q => \168\, CLK => \PLD24/W\, Qneg => open );
	U230 : FF_D_CO_NI
		port map( D => \PLD21/W_6\, Q => \169\, CLK => \PLD24/W\, Qneg => open );
	U231 : FF_D_CO_NI
		port map( D => \PLD21/W_7\, Q => \170\, CLK => \PLD24/W\, Qneg => open );
	U232 : FF_D_CO_NI
		port map( D => \PLD21/W_8\, Q => \171\, CLK => \PLD24/W\, Qneg => open );
	U233 : FF_D_CO_NI
		port map( D => \PLD21/W_9\, Q => \172\, CLK => \PLD24/W\, Qneg => open );
	U234 : FF_D_CO_NI
		port map( D => \PLD21/W_10\, Q => \173\, CLK => \PLD24/W\, Qneg => open );
	U235 : FF_D_CO_NI
		port map( D => \PLD21/W_11\, Q => \174\, CLK => \PLD24/W\, Qneg => open );
	U236 : FF_D_CO_NI
		port map( D => \PLD21/W_12\, Q => \175\, CLK => \PLD24/W\, Qneg => open );
	U237 : AND3_NI
		port map( A => \PLD21/RE\, B => \PLD24/Read_EN_Col\, C => \PLD22/Read_EN_Row\, Y => \PLD24/R\ );
	U238 : AND3_NI
		port map( A => \PLD21/WC\, B => \PLD24/Write_EN_Col\, C => \PLD22/Write_EN_Row\, Y => \PLD24/W\ );
	U239 : AND2_NI
		port map( A => \PLD24/R\, B => \164\, Y => \176\ );
	U240 : AND2_NI
		port map( A => \PLD24/R\, B => \165\, Y => \177\ );
	U241 : OR2_NI
		port map( A => \PLD23/Read_1\, B => \176\, Y => \PLD24/Read_1\ );
	U242 : OR2_NI
		port map( A => \PLD23/Read_2\, B => \177\, Y => \PLD24/Read_2\ );
	U243 : AND2_NI
		port map( A => \PLD24/R\, B => \166\, Y => \178\ );
	U244 : OR2_NI
		port map( A => \PLD23/Read_3\, B => \178\, Y => \PLD24/Read_3\ );
	U245 : AND2_NI
		port map( A => \PLD24/R\, B => \167\, Y => \179\ );
	U246 : OR2_NI
		port map( A => \PLD23/Read_4\, B => \179\, Y => \PLD24/Read_4\ );
	U247 : AND2_NI
		port map( A => \PLD24/R\, B => \168\, Y => \180\ );
	U248 : OR2_NI
		port map( A => \PLD23/Read_5\, B => \180\, Y => \PLD24/Read_5\ );
	U249 : AND2_NI
		port map( A => \PLD24/R\, B => \169\, Y => \181\ );
	U250 : AND2_NI
		port map( A => \PLD24/R\, B => \170\, Y => \182\ );
	U251 : AND2_NI
		port map( A => \PLD24/R\, B => \171\, Y => \183\ );
	U252 : AND2_NI
		port map( A => \PLD24/R\, B => \172\, Y => \184\ );
	U253 : AND2_NI
		port map( A => \PLD24/R\, B => \173\, Y => \185\ );
	U254 : AND2_NI
		port map( A => \PLD24/R\, B => \174\, Y => \186\ );
	U255 : AND2_NI
		port map( A => \PLD24/R\, B => \175\, Y => \187\ );
	U256 : OR2_NI
		port map( A => \PLD23/Read_6\, B => \181\, Y => \PLD24/Read_6\ );
	U257 : OR2_NI
		port map( A => \PLD23/Read_7\, B => \182\, Y => \PLD24/Read_7\ );
	U258 : OR2_NI
		port map( A => \PLD23/Read_8\, B => \183\, Y => \PLD24/Read_8\ );
	U259 : OR2_NI
		port map( A => \PLD23/Read_9\, B => \184\, Y => \PLD24/Read_9\ );
	U260 : OR2_NI
		port map( A => \PLD23/Read_10\, B => \185\, Y => \PLD24/Read_10\ );
	U261 : OR2_NI
		port map( A => \PLD23/Read_11\, B => \186\, Y => \PLD24/Read_11\ );
	U262 : OR2_NI
		port map( A => \PLD23/Read_12\, B => \187\, Y => \PLD24/Read_12\ );
	U263 : FF_D_CO_NI
		port map( D => \PLD21/W_1\, Q => \188\, CLK => \PLD25/W\, Qneg => open );
	U264 : FF_D_CO_NI
		port map( D => \PLD21/W_2\, Q => \189\, CLK => \PLD25/W\, Qneg => open );
	U265 : FF_D_CO_NI
		port map( D => \PLD21/W_3\, Q => \190\, CLK => \PLD25/W\, Qneg => open );
	U266 : FF_D_CO_NI
		port map( D => \PLD21/W_4\, Q => \191\, CLK => \PLD25/W\, Qneg => open );
	U267 : FF_D_CO_NI
		port map( D => \PLD21/W_5\, Q => \192\, CLK => \PLD25/W\, Qneg => open );
	U268 : FF_D_CO_NI
		port map( D => \PLD21/W_6\, Q => \193\, CLK => \PLD25/W\, Qneg => open );
	U269 : FF_D_CO_NI
		port map( D => \PLD21/W_7\, Q => \194\, CLK => \PLD25/W\, Qneg => open );
	U270 : FF_D_CO_NI
		port map( D => \PLD21/W_8\, Q => \195\, CLK => \PLD25/W\, Qneg => open );
	U271 : FF_D_CO_NI
		port map( D => \PLD21/W_9\, Q => \196\, CLK => \PLD25/W\, Qneg => open );
	U272 : FF_D_CO_NI
		port map( D => \PLD21/W_10\, Q => \197\, CLK => \PLD25/W\, Qneg => open );
	U273 : FF_D_CO_NI
		port map( D => \PLD21/W_11\, Q => \198\, CLK => \PLD25/W\, Qneg => open );
	U274 : FF_D_CO_NI
		port map( D => \PLD21/W_12\, Q => \199\, CLK => \PLD25/W\, Qneg => open );
	U275 : AND3_NI
		port map( A => \PLD21/RE\, B => \PLD25/Read_EN_Col\, C => \PLD22/Read_EN_Row\, Y => \PLD25/R\ );
	U276 : AND3_NI
		port map( A => \PLD21/WC\, B => \PLD25/Write_EN_Col\, C => \PLD22/Write_EN_Row\, Y => \PLD25/W\ );
	U277 : AND2_NI
		port map( A => \PLD25/R\, B => \188\, Y => \200\ );
	U278 : AND2_NI
		port map( A => \PLD25/R\, B => \189\, Y => \201\ );
	U279 : OR2_NI
		port map( A => \PLD24/Read_1\, B => \200\, Y => \PLD21/R1_1\ );
	U280 : OR2_NI
		port map( A => \PLD24/Read_2\, B => \201\, Y => \PLD21/R1_2\ );
	U281 : AND2_NI
		port map( A => \PLD25/R\, B => \190\, Y => \202\ );
	U282 : OR2_NI
		port map( A => \PLD24/Read_3\, B => \202\, Y => \PLD21/R1_3\ );
	U283 : AND2_NI
		port map( A => \PLD25/R\, B => \191\, Y => \203\ );
	U284 : OR2_NI
		port map( A => \PLD24/Read_4\, B => \203\, Y => \PLD21/R1_4\ );
	U285 : AND2_NI
		port map( A => \PLD25/R\, B => \192\, Y => \204\ );
	U286 : OR2_NI
		port map( A => \PLD24/Read_5\, B => \204\, Y => \PLD21/R1_5\ );
	U287 : AND2_NI
		port map( A => \PLD25/R\, B => \193\, Y => \205\ );
	U288 : AND2_NI
		port map( A => \PLD25/R\, B => \194\, Y => \206\ );
	U289 : AND2_NI
		port map( A => \PLD25/R\, B => \195\, Y => \207\ );
	U290 : AND2_NI
		port map( A => \PLD25/R\, B => \196\, Y => \208\ );
	U291 : AND2_NI
		port map( A => \PLD25/R\, B => \197\, Y => \209\ );
	U292 : AND2_NI
		port map( A => \PLD25/R\, B => \198\, Y => \210\ );
	U293 : AND2_NI
		port map( A => \PLD25/R\, B => \199\, Y => \211\ );
	U294 : OR2_NI
		port map( A => \PLD24/Read_6\, B => \205\, Y => \PLD21/R1_6\ );
	U295 : OR2_NI
		port map( A => \PLD24/Read_7\, B => \206\, Y => \PLD21/R1_7\ );
	U296 : OR2_NI
		port map( A => \PLD24/Read_8\, B => \207\, Y => \PLD21/R1_8\ );
	U297 : OR2_NI
		port map( A => \PLD24/Read_9\, B => \208\, Y => \PLD21/R1_9\ );
	U298 : OR2_NI
		port map( A => \PLD24/Read_10\, B => \209\, Y => \PLD21/R1_10\ );
	U299 : OR2_NI
		port map( A => \PLD24/Read_11\, B => \210\, Y => \PLD21/R1_11\ );
	U300 : OR2_NI
		port map( A => \PLD24/Read_12\, B => \211\, Y => \PLD21/R1_12\ );
	U301 : FF_D_CO_NI
		port map( D => \PLD21/W_1\, Q => \212\, CLK => \PLD26/W\, Qneg => open );
	U302 : FF_D_CO_NI
		port map( D => \PLD21/W_2\, Q => \213\, CLK => \PLD26/W\, Qneg => open );
	U303 : FF_D_CO_NI
		port map( D => \PLD21/W_3\, Q => \214\, CLK => \PLD26/W\, Qneg => open );
	U304 : FF_D_CO_NI
		port map( D => \PLD21/W_4\, Q => \215\, CLK => \PLD26/W\, Qneg => open );
	U305 : FF_D_CO_NI
		port map( D => \PLD21/W_5\, Q => \216\, CLK => \PLD26/W\, Qneg => open );
	U306 : FF_D_CO_NI
		port map( D => \PLD21/W_6\, Q => \217\, CLK => \PLD26/W\, Qneg => open );
	U307 : FF_D_CO_NI
		port map( D => \PLD21/W_7\, Q => \218\, CLK => \PLD26/W\, Qneg => open );
	U308 : FF_D_CO_NI
		port map( D => \PLD21/W_8\, Q => \219\, CLK => \PLD26/W\, Qneg => open );
	U309 : FF_D_CO_NI
		port map( D => \PLD21/W_9\, Q => \220\, CLK => \PLD26/W\, Qneg => open );
	U310 : FF_D_CO_NI
		port map( D => \PLD21/W_10\, Q => \221\, CLK => \PLD26/W\, Qneg => open );
	U311 : FF_D_CO_NI
		port map( D => \PLD21/W_11\, Q => \222\, CLK => \PLD26/W\, Qneg => open );
	U312 : FF_D_CO_NI
		port map( D => \PLD21/W_12\, Q => \223\, CLK => \PLD26/W\, Qneg => open );
	U313 : AND3_NI
		port map( A => \PLD21/RE\, B => \PLD22/Read_EN_Col\, C => \PLD26/Read_EN_Row\, Y => \PLD26/R\ );
	U314 : AND3_NI
		port map( A => \PLD21/WC\, B => \PLD22/Write_EN_Col\, C => \PLD26/Write_EN_Row\, Y => \PLD26/W\ );
	U315 : AND2_NI
		port map( A => \PLD26/R\, B => \212\, Y => \224\ );
	U316 : AND2_NI
		port map( A => \PLD26/R\, B => \213\, Y => \225\ );
	U317 : OR2_NI
		port map( A => \PLD21/R1_1\, B => \224\, Y => \PLD26/Read_1\ );
	U318 : OR2_NI
		port map( A => \PLD21/R1_2\, B => \225\, Y => \PLD26/Read_2\ );
	U319 : AND2_NI
		port map( A => \PLD26/R\, B => \214\, Y => \226\ );
	U320 : OR2_NI
		port map( A => \PLD21/R1_3\, B => \226\, Y => \PLD26/Read_3\ );
	U321 : AND2_NI
		port map( A => \PLD26/R\, B => \215\, Y => \227\ );
	U322 : OR2_NI
		port map( A => \PLD21/R1_4\, B => \227\, Y => \PLD26/Read_4\ );
	U323 : AND2_NI
		port map( A => \PLD26/R\, B => \216\, Y => \228\ );
	U324 : OR2_NI
		port map( A => \PLD21/R1_5\, B => \228\, Y => \PLD26/Read_5\ );
	U325 : AND2_NI
		port map( A => \PLD26/R\, B => \217\, Y => \229\ );
	U326 : AND2_NI
		port map( A => \PLD26/R\, B => \218\, Y => \230\ );
	U327 : AND2_NI
		port map( A => \PLD26/R\, B => \219\, Y => \231\ );
	U328 : AND2_NI
		port map( A => \PLD26/R\, B => \220\, Y => \232\ );
	U329 : AND2_NI
		port map( A => \PLD26/R\, B => \221\, Y => \233\ );
	U330 : AND2_NI
		port map( A => \PLD26/R\, B => \222\, Y => \234\ );
	U331 : AND2_NI
		port map( A => \PLD26/R\, B => \223\, Y => \235\ );
	U332 : OR2_NI
		port map( A => \PLD21/R1_6\, B => \229\, Y => \PLD26/Read_6\ );
	U333 : OR2_NI
		port map( A => \PLD21/R1_7\, B => \230\, Y => \PLD26/Read_7\ );
	U334 : OR2_NI
		port map( A => \PLD21/R1_8\, B => \231\, Y => \PLD26/Read_8\ );
	U335 : OR2_NI
		port map( A => \PLD21/R1_9\, B => \232\, Y => \PLD26/Read_9\ );
	U336 : OR2_NI
		port map( A => \PLD21/R1_10\, B => \233\, Y => \PLD26/Read_10\ );
	U337 : OR2_NI
		port map( A => \PLD21/R1_11\, B => \234\, Y => \PLD26/Read_11\ );
	U338 : OR2_NI
		port map( A => \PLD21/R1_12\, B => \235\, Y => \PLD26/Read_12\ );
	U339 : FF_D_CO_NI
		port map( D => \PLD21/W_1\, Q => \236\, CLK => \PLD27/W\, Qneg => open );
	U340 : FF_D_CO_NI
		port map( D => \PLD21/W_2\, Q => \237\, CLK => \PLD27/W\, Qneg => open );
	U341 : FF_D_CO_NI
		port map( D => \PLD21/W_3\, Q => \238\, CLK => \PLD27/W\, Qneg => open );
	U342 : FF_D_CO_NI
		port map( D => \PLD21/W_4\, Q => \239\, CLK => \PLD27/W\, Qneg => open );
	U343 : FF_D_CO_NI
		port map( D => \PLD21/W_5\, Q => \240\, CLK => \PLD27/W\, Qneg => open );
	U344 : FF_D_CO_NI
		port map( D => \PLD21/W_6\, Q => \241\, CLK => \PLD27/W\, Qneg => open );
	U345 : FF_D_CO_NI
		port map( D => \PLD21/W_7\, Q => \242\, CLK => \PLD27/W\, Qneg => open );
	U346 : FF_D_CO_NI
		port map( D => \PLD21/W_8\, Q => \243\, CLK => \PLD27/W\, Qneg => open );
	U347 : FF_D_CO_NI
		port map( D => \PLD21/W_9\, Q => \244\, CLK => \PLD27/W\, Qneg => open );
	U348 : FF_D_CO_NI
		port map( D => \PLD21/W_10\, Q => \245\, CLK => \PLD27/W\, Qneg => open );
	U349 : FF_D_CO_NI
		port map( D => \PLD21/W_11\, Q => \246\, CLK => \PLD27/W\, Qneg => open );
	U350 : FF_D_CO_NI
		port map( D => \PLD21/W_12\, Q => \247\, CLK => \PLD27/W\, Qneg => open );
	U351 : AND3_NI
		port map( A => \PLD21/RE\, B => \PLD23/Read_EN_Col\, C => \PLD26/Read_EN_Row\, Y => \PLD27/R\ );
	U352 : AND3_NI
		port map( A => \PLD21/WC\, B => \PLD23/Write_EN_Col\, C => \PLD26/Write_EN_Row\, Y => \PLD27/W\ );
	U353 : AND2_NI
		port map( A => \PLD27/R\, B => \236\, Y => \248\ );
	U354 : AND2_NI
		port map( A => \PLD27/R\, B => \237\, Y => \249\ );
	U355 : OR2_NI
		port map( A => \PLD26/Read_1\, B => \248\, Y => \PLD27/Read_1\ );
	U356 : OR2_NI
		port map( A => \PLD26/Read_2\, B => \249\, Y => \PLD27/Read_2\ );
	U357 : AND2_NI
		port map( A => \PLD27/R\, B => \238\, Y => \250\ );
	U358 : OR2_NI
		port map( A => \PLD26/Read_3\, B => \250\, Y => \PLD27/Read_3\ );
	U359 : AND2_NI
		port map( A => \PLD27/R\, B => \239\, Y => \251\ );
	U360 : OR2_NI
		port map( A => \PLD26/Read_4\, B => \251\, Y => \PLD27/Read_4\ );
	U361 : AND2_NI
		port map( A => \PLD27/R\, B => \240\, Y => \252\ );
	U362 : OR2_NI
		port map( A => \PLD26/Read_5\, B => \252\, Y => \PLD27/Read_5\ );
	U363 : AND2_NI
		port map( A => \PLD27/R\, B => \241\, Y => \253\ );
	U364 : AND2_NI
		port map( A => \PLD27/R\, B => \242\, Y => \254\ );
	U365 : AND2_NI
		port map( A => \PLD27/R\, B => \243\, Y => \255\ );
	U366 : AND2_NI
		port map( A => \PLD27/R\, B => \244\, Y => \256\ );
	U367 : AND2_NI
		port map( A => \PLD27/R\, B => \245\, Y => \257\ );
	U368 : AND2_NI
		port map( A => \PLD27/R\, B => \246\, Y => \258\ );
	U369 : AND2_NI
		port map( A => \PLD27/R\, B => \247\, Y => \259\ );
	U370 : OR2_NI
		port map( A => \PLD26/Read_6\, B => \253\, Y => \PLD27/Read_6\ );
	U371 : OR2_NI
		port map( A => \PLD26/Read_7\, B => \254\, Y => \PLD27/Read_7\ );
	U372 : OR2_NI
		port map( A => \PLD26/Read_8\, B => \255\, Y => \PLD27/Read_8\ );
	U373 : OR2_NI
		port map( A => \PLD26/Read_9\, B => \256\, Y => \PLD27/Read_9\ );
	U374 : OR2_NI
		port map( A => \PLD26/Read_10\, B => \257\, Y => \PLD27/Read_10\ );
	U375 : OR2_NI
		port map( A => \PLD26/Read_11\, B => \258\, Y => \PLD27/Read_11\ );
	U376 : OR2_NI
		port map( A => \PLD26/Read_12\, B => \259\, Y => \PLD27/Read_12\ );
	U377 : FF_D_CO_NI
		port map( D => \PLD21/W_1\, Q => \260\, CLK => \PLD28/W\, Qneg => open );
	U378 : FF_D_CO_NI
		port map( D => \PLD21/W_2\, Q => \261\, CLK => \PLD28/W\, Qneg => open );
	U379 : FF_D_CO_NI
		port map( D => \PLD21/W_3\, Q => \262\, CLK => \PLD28/W\, Qneg => open );
	U380 : FF_D_CO_NI
		port map( D => \PLD21/W_4\, Q => \263\, CLK => \PLD28/W\, Qneg => open );
	U381 : FF_D_CO_NI
		port map( D => \PLD21/W_5\, Q => \264\, CLK => \PLD28/W\, Qneg => open );
	U382 : FF_D_CO_NI
		port map( D => \PLD21/W_6\, Q => \265\, CLK => \PLD28/W\, Qneg => open );
	U383 : FF_D_CO_NI
		port map( D => \PLD21/W_7\, Q => \266\, CLK => \PLD28/W\, Qneg => open );
	U384 : FF_D_CO_NI
		port map( D => \PLD21/W_8\, Q => \267\, CLK => \PLD28/W\, Qneg => open );
	U385 : FF_D_CO_NI
		port map( D => \PLD21/W_9\, Q => \268\, CLK => \PLD28/W\, Qneg => open );
	U386 : FF_D_CO_NI
		port map( D => \PLD21/W_10\, Q => \269\, CLK => \PLD28/W\, Qneg => open );
	U387 : FF_D_CO_NI
		port map( D => \PLD21/W_11\, Q => \270\, CLK => \PLD28/W\, Qneg => open );
	U388 : FF_D_CO_NI
		port map( D => \PLD21/W_12\, Q => \271\, CLK => \PLD28/W\, Qneg => open );
	U389 : AND3_NI
		port map( A => \PLD21/RE\, B => \PLD24/Read_EN_Col\, C => \PLD26/Read_EN_Row\, Y => \PLD28/R\ );
	U390 : AND3_NI
		port map( A => \PLD21/WC\, B => \PLD24/Write_EN_Col\, C => \PLD26/Write_EN_Row\, Y => \PLD28/W\ );
	U391 : AND2_NI
		port map( A => \PLD28/R\, B => \260\, Y => \272\ );
	U392 : AND2_NI
		port map( A => \PLD28/R\, B => \261\, Y => \273\ );
	U393 : OR2_NI
		port map( A => \PLD27/Read_1\, B => \272\, Y => \PLD28/Read_1\ );
	U394 : OR2_NI
		port map( A => \PLD27/Read_2\, B => \273\, Y => \PLD28/Read_2\ );
	U395 : AND2_NI
		port map( A => \PLD28/R\, B => \262\, Y => \274\ );
	U396 : OR2_NI
		port map( A => \PLD27/Read_3\, B => \274\, Y => \PLD28/Read_3\ );
	U397 : AND2_NI
		port map( A => \PLD28/R\, B => \263\, Y => \275\ );
	U398 : OR2_NI
		port map( A => \PLD27/Read_4\, B => \275\, Y => \PLD28/Read_4\ );
	U399 : AND2_NI
		port map( A => \PLD28/R\, B => \264\, Y => \276\ );
	U400 : OR2_NI
		port map( A => \PLD27/Read_5\, B => \276\, Y => \PLD28/Read_5\ );
	U401 : AND2_NI
		port map( A => \PLD28/R\, B => \265\, Y => \277\ );
	U402 : AND2_NI
		port map( A => \PLD28/R\, B => \266\, Y => \278\ );
	U403 : AND2_NI
		port map( A => \PLD28/R\, B => \267\, Y => \279\ );
	U404 : AND2_NI
		port map( A => \PLD28/R\, B => \268\, Y => \280\ );
	U405 : AND2_NI
		port map( A => \PLD28/R\, B => \269\, Y => \281\ );
	U406 : AND2_NI
		port map( A => \PLD28/R\, B => \270\, Y => \282\ );
	U407 : AND2_NI
		port map( A => \PLD28/R\, B => \271\, Y => \283\ );
	U408 : OR2_NI
		port map( A => \PLD27/Read_6\, B => \277\, Y => \PLD28/Read_6\ );
	U409 : OR2_NI
		port map( A => \PLD27/Read_7\, B => \278\, Y => \PLD28/Read_7\ );
	U410 : OR2_NI
		port map( A => \PLD27/Read_8\, B => \279\, Y => \PLD28/Read_8\ );
	U411 : OR2_NI
		port map( A => \PLD27/Read_9\, B => \280\, Y => \PLD28/Read_9\ );
	U412 : OR2_NI
		port map( A => \PLD27/Read_10\, B => \281\, Y => \PLD28/Read_10\ );
	U413 : OR2_NI
		port map( A => \PLD27/Read_11\, B => \282\, Y => \PLD28/Read_11\ );
	U414 : OR2_NI
		port map( A => \PLD27/Read_12\, B => \283\, Y => \PLD28/Read_12\ );
	U415 : FF_D_CO_NI
		port map( D => \PLD21/W_1\, Q => \284\, CLK => \PLD29/W\, Qneg => open );
	U416 : FF_D_CO_NI
		port map( D => \PLD21/W_2\, Q => \285\, CLK => \PLD29/W\, Qneg => open );
	U417 : FF_D_CO_NI
		port map( D => \PLD21/W_3\, Q => \286\, CLK => \PLD29/W\, Qneg => open );
	U418 : FF_D_CO_NI
		port map( D => \PLD21/W_4\, Q => \287\, CLK => \PLD29/W\, Qneg => open );
	U419 : FF_D_CO_NI
		port map( D => \PLD21/W_5\, Q => \288\, CLK => \PLD29/W\, Qneg => open );
	U420 : FF_D_CO_NI
		port map( D => \PLD21/W_6\, Q => \289\, CLK => \PLD29/W\, Qneg => open );
	U421 : FF_D_CO_NI
		port map( D => \PLD21/W_7\, Q => \290\, CLK => \PLD29/W\, Qneg => open );
	U422 : FF_D_CO_NI
		port map( D => \PLD21/W_8\, Q => \291\, CLK => \PLD29/W\, Qneg => open );
	U423 : FF_D_CO_NI
		port map( D => \PLD21/W_9\, Q => \292\, CLK => \PLD29/W\, Qneg => open );
	U424 : FF_D_CO_NI
		port map( D => \PLD21/W_10\, Q => \293\, CLK => \PLD29/W\, Qneg => open );
	U425 : FF_D_CO_NI
		port map( D => \PLD21/W_11\, Q => \294\, CLK => \PLD29/W\, Qneg => open );
	U426 : FF_D_CO_NI
		port map( D => \PLD21/W_12\, Q => \295\, CLK => \PLD29/W\, Qneg => open );
	U427 : AND3_NI
		port map( A => \PLD21/RE\, B => \PLD25/Read_EN_Col\, C => \PLD26/Read_EN_Row\, Y => \PLD29/R\ );
	U428 : AND3_NI
		port map( A => \PLD21/WC\, B => \PLD25/Write_EN_Col\, C => \PLD26/Write_EN_Row\, Y => \PLD29/W\ );
	U429 : AND2_NI
		port map( A => \PLD29/R\, B => \284\, Y => \296\ );
	U430 : AND2_NI
		port map( A => \PLD29/R\, B => \285\, Y => \297\ );
	U431 : OR2_NI
		port map( A => \PLD28/Read_1\, B => \296\, Y => \PLD21/R2_1\ );
	U432 : OR2_NI
		port map( A => \PLD28/Read_2\, B => \297\, Y => \PLD21/R2_2\ );
	U433 : AND2_NI
		port map( A => \PLD29/R\, B => \286\, Y => \298\ );
	U434 : OR2_NI
		port map( A => \PLD28/Read_3\, B => \298\, Y => \PLD21/R2_3\ );
	U435 : AND2_NI
		port map( A => \PLD29/R\, B => \287\, Y => \299\ );
	U436 : OR2_NI
		port map( A => \PLD28/Read_4\, B => \299\, Y => \PLD21/R2_4\ );
	U437 : AND2_NI
		port map( A => \PLD29/R\, B => \288\, Y => \300\ );
	U438 : OR2_NI
		port map( A => \PLD28/Read_5\, B => \300\, Y => \PLD21/R2_5\ );
	U439 : AND2_NI
		port map( A => \PLD29/R\, B => \289\, Y => \301\ );
	U440 : AND2_NI
		port map( A => \PLD29/R\, B => \290\, Y => \302\ );
	U441 : AND2_NI
		port map( A => \PLD29/R\, B => \291\, Y => \303\ );
	U442 : AND2_NI
		port map( A => \PLD29/R\, B => \292\, Y => \304\ );
	U443 : AND2_NI
		port map( A => \PLD29/R\, B => \293\, Y => \305\ );
	U444 : AND2_NI
		port map( A => \PLD29/R\, B => \294\, Y => \306\ );
	U445 : AND2_NI
		port map( A => \PLD29/R\, B => \295\, Y => \307\ );
	U446 : OR2_NI
		port map( A => \PLD28/Read_6\, B => \301\, Y => \PLD21/R2_6\ );
	U447 : OR2_NI
		port map( A => \PLD28/Read_7\, B => \302\, Y => \PLD21/R2_7\ );
	U448 : OR2_NI
		port map( A => \PLD28/Read_8\, B => \303\, Y => \PLD21/R2_8\ );
	U449 : OR2_NI
		port map( A => \PLD28/Read_9\, B => \304\, Y => \PLD21/R2_9\ );
	U450 : OR2_NI
		port map( A => \PLD28/Read_10\, B => \305\, Y => \PLD21/R2_10\ );
	U451 : OR2_NI
		port map( A => \PLD28/Read_11\, B => \306\, Y => \PLD21/R2_11\ );
	U452 : OR2_NI
		port map( A => \PLD28/Read_12\, B => \307\, Y => \PLD21/R2_12\ );
	U453 : FF_D_CO_NI
		port map( D => \PLD21/W_1\, Q => \308\, CLK => \PLD30/W\, Qneg => open );
	U454 : FF_D_CO_NI
		port map( D => \PLD21/W_2\, Q => \309\, CLK => \PLD30/W\, Qneg => open );
	U455 : FF_D_CO_NI
		port map( D => \PLD21/W_3\, Q => \310\, CLK => \PLD30/W\, Qneg => open );
	U456 : FF_D_CO_NI
		port map( D => \PLD21/W_4\, Q => \311\, CLK => \PLD30/W\, Qneg => open );
	U457 : FF_D_CO_NI
		port map( D => \PLD21/W_5\, Q => \312\, CLK => \PLD30/W\, Qneg => open );
	U458 : FF_D_CO_NI
		port map( D => \PLD21/W_6\, Q => \313\, CLK => \PLD30/W\, Qneg => open );
	U459 : FF_D_CO_NI
		port map( D => \PLD21/W_7\, Q => \314\, CLK => \PLD30/W\, Qneg => open );
	U460 : FF_D_CO_NI
		port map( D => \PLD21/W_8\, Q => \315\, CLK => \PLD30/W\, Qneg => open );
	U461 : FF_D_CO_NI
		port map( D => \PLD21/W_9\, Q => \316\, CLK => \PLD30/W\, Qneg => open );
	U462 : FF_D_CO_NI
		port map( D => \PLD21/W_10\, Q => \317\, CLK => \PLD30/W\, Qneg => open );
	U463 : FF_D_CO_NI
		port map( D => \PLD21/W_11\, Q => \318\, CLK => \PLD30/W\, Qneg => open );
	U464 : FF_D_CO_NI
		port map( D => \PLD21/W_12\, Q => \319\, CLK => \PLD30/W\, Qneg => open );
	U465 : AND3_NI
		port map( A => \PLD21/RE\, B => \PLD22/Read_EN_Col\, C => \PLD30/Read_EN_Row\, Y => \PLD30/R\ );
	U466 : AND3_NI
		port map( A => \PLD21/WC\, B => \PLD22/Write_EN_Col\, C => \PLD30/Write_EN_Row\, Y => \PLD30/W\ );
	U467 : AND2_NI
		port map( A => \PLD30/R\, B => \308\, Y => \320\ );
	U468 : AND2_NI
		port map( A => \PLD30/R\, B => \309\, Y => \321\ );
	U469 : OR2_NI
		port map( A => \PLD21/R2_1\, B => \320\, Y => \PLD30/Read_1\ );
	U470 : OR2_NI
		port map( A => \PLD21/R2_2\, B => \321\, Y => \PLD30/Read_2\ );
	U471 : AND2_NI
		port map( A => \PLD30/R\, B => \310\, Y => \322\ );
	U472 : OR2_NI
		port map( A => \PLD21/R2_3\, B => \322\, Y => \PLD30/Read_3\ );
	U473 : AND2_NI
		port map( A => \PLD30/R\, B => \311\, Y => \323\ );
	U474 : OR2_NI
		port map( A => \PLD21/R2_4\, B => \323\, Y => \PLD30/Read_4\ );
	U475 : AND2_NI
		port map( A => \PLD30/R\, B => \312\, Y => \324\ );
	U476 : OR2_NI
		port map( A => \PLD21/R2_5\, B => \324\, Y => \PLD30/Read_5\ );
	U477 : AND2_NI
		port map( A => \PLD30/R\, B => \313\, Y => \325\ );
	U478 : AND2_NI
		port map( A => \PLD30/R\, B => \314\, Y => \326\ );
	U479 : AND2_NI
		port map( A => \PLD30/R\, B => \315\, Y => \327\ );
	U480 : AND2_NI
		port map( A => \PLD30/R\, B => \316\, Y => \328\ );
	U481 : AND2_NI
		port map( A => \PLD30/R\, B => \317\, Y => \329\ );
	U482 : AND2_NI
		port map( A => \PLD30/R\, B => \318\, Y => \330\ );
	U483 : AND2_NI
		port map( A => \PLD30/R\, B => \319\, Y => \331\ );
	U484 : OR2_NI
		port map( A => \PLD21/R2_6\, B => \325\, Y => \PLD30/Read_6\ );
	U485 : OR2_NI
		port map( A => \PLD21/R2_7\, B => \326\, Y => \PLD30/Read_7\ );
	U486 : OR2_NI
		port map( A => \PLD21/R2_8\, B => \327\, Y => \PLD30/Read_8\ );
	U487 : OR2_NI
		port map( A => \PLD21/R2_9\, B => \328\, Y => \PLD30/Read_9\ );
	U488 : OR2_NI
		port map( A => \PLD21/R2_10\, B => \329\, Y => \PLD30/Read_10\ );
	U489 : OR2_NI
		port map( A => \PLD21/R2_11\, B => \330\, Y => \PLD30/Read_11\ );
	U490 : OR2_NI
		port map( A => \PLD21/R2_12\, B => \331\, Y => \PLD30/Read_12\ );
	U491 : FF_D_CO_NI
		port map( D => \PLD21/W_1\, Q => \332\, CLK => \PLD31/W\, Qneg => open );
	U492 : FF_D_CO_NI
		port map( D => \PLD21/W_2\, Q => \333\, CLK => \PLD31/W\, Qneg => open );
	U493 : FF_D_CO_NI
		port map( D => \PLD21/W_3\, Q => \334\, CLK => \PLD31/W\, Qneg => open );
	U494 : FF_D_CO_NI
		port map( D => \PLD21/W_4\, Q => \335\, CLK => \PLD31/W\, Qneg => open );
	U495 : FF_D_CO_NI
		port map( D => \PLD21/W_5\, Q => \336\, CLK => \PLD31/W\, Qneg => open );
	U496 : FF_D_CO_NI
		port map( D => \PLD21/W_6\, Q => \337\, CLK => \PLD31/W\, Qneg => open );
	U497 : FF_D_CO_NI
		port map( D => \PLD21/W_7\, Q => \338\, CLK => \PLD31/W\, Qneg => open );
	U498 : FF_D_CO_NI
		port map( D => \PLD21/W_8\, Q => \339\, CLK => \PLD31/W\, Qneg => open );
	U499 : FF_D_CO_NI
		port map( D => \PLD21/W_9\, Q => \340\, CLK => \PLD31/W\, Qneg => open );
	U500 : FF_D_CO_NI
		port map( D => \PLD21/W_10\, Q => \341\, CLK => \PLD31/W\, Qneg => open );
	U501 : FF_D_CO_NI
		port map( D => \PLD21/W_11\, Q => \342\, CLK => \PLD31/W\, Qneg => open );
	U502 : FF_D_CO_NI
		port map( D => \PLD21/W_12\, Q => \343\, CLK => \PLD31/W\, Qneg => open );
	U503 : AND3_NI
		port map( A => \PLD21/RE\, B => \PLD23/Read_EN_Col\, C => \PLD30/Read_EN_Row\, Y => \PLD31/R\ );
	U504 : AND3_NI
		port map( A => \PLD21/WC\, B => \PLD23/Write_EN_Col\, C => \PLD30/Write_EN_Row\, Y => \PLD31/W\ );
	U505 : AND2_NI
		port map( A => \PLD31/R\, B => \332\, Y => \344\ );
	U506 : AND2_NI
		port map( A => \PLD31/R\, B => \333\, Y => \345\ );
	U507 : OR2_NI
		port map( A => \PLD30/Read_1\, B => \344\, Y => \PLD31/Read_1\ );
	U508 : OR2_NI
		port map( A => \PLD30/Read_2\, B => \345\, Y => \PLD31/Read_2\ );
	U509 : AND2_NI
		port map( A => \PLD31/R\, B => \334\, Y => \346\ );
	U510 : OR2_NI
		port map( A => \PLD30/Read_3\, B => \346\, Y => \PLD31/Read_3\ );
	U511 : AND2_NI
		port map( A => \PLD31/R\, B => \335\, Y => \347\ );
	U512 : OR2_NI
		port map( A => \PLD30/Read_4\, B => \347\, Y => \PLD31/Read_4\ );
	U513 : AND2_NI
		port map( A => \PLD31/R\, B => \336\, Y => \348\ );
	U514 : OR2_NI
		port map( A => \PLD30/Read_5\, B => \348\, Y => \PLD31/Read_5\ );
	U515 : AND2_NI
		port map( A => \PLD31/R\, B => \337\, Y => \349\ );
	U516 : AND2_NI
		port map( A => \PLD31/R\, B => \338\, Y => \350\ );
	U517 : AND2_NI
		port map( A => \PLD31/R\, B => \339\, Y => \351\ );
	U518 : AND2_NI
		port map( A => \PLD31/R\, B => \340\, Y => \352\ );
	U519 : AND2_NI
		port map( A => \PLD31/R\, B => \341\, Y => \353\ );
	U520 : AND2_NI
		port map( A => \PLD31/R\, B => \342\, Y => \354\ );
	U521 : AND2_NI
		port map( A => \PLD31/R\, B => \343\, Y => \355\ );
	U522 : OR2_NI
		port map( A => \PLD30/Read_6\, B => \349\, Y => \PLD31/Read_6\ );
	U523 : OR2_NI
		port map( A => \PLD30/Read_7\, B => \350\, Y => \PLD31/Read_7\ );
	U524 : OR2_NI
		port map( A => \PLD30/Read_8\, B => \351\, Y => \PLD31/Read_8\ );
	U525 : OR2_NI
		port map( A => \PLD30/Read_9\, B => \352\, Y => \PLD31/Read_9\ );
	U526 : OR2_NI
		port map( A => \PLD30/Read_10\, B => \353\, Y => \PLD31/Read_10\ );
	U527 : OR2_NI
		port map( A => \PLD30/Read_11\, B => \354\, Y => \PLD31/Read_11\ );
	U528 : OR2_NI
		port map( A => \PLD30/Read_12\, B => \355\, Y => \PLD31/Read_12\ );
	U529 : FF_D_CO_NI
		port map( D => \PLD21/W_1\, Q => \356\, CLK => \PLD32/W\, Qneg => open );
	U530 : FF_D_CO_NI
		port map( D => \PLD21/W_2\, Q => \357\, CLK => \PLD32/W\, Qneg => open );
	U531 : FF_D_CO_NI
		port map( D => \PLD21/W_3\, Q => \358\, CLK => \PLD32/W\, Qneg => open );
	U532 : FF_D_CO_NI
		port map( D => \PLD21/W_4\, Q => \359\, CLK => \PLD32/W\, Qneg => open );
	U533 : FF_D_CO_NI
		port map( D => \PLD21/W_5\, Q => \360\, CLK => \PLD32/W\, Qneg => open );
	U534 : FF_D_CO_NI
		port map( D => \PLD21/W_6\, Q => \361\, CLK => \PLD32/W\, Qneg => open );
	U535 : FF_D_CO_NI
		port map( D => \PLD21/W_7\, Q => \362\, CLK => \PLD32/W\, Qneg => open );
	U536 : FF_D_CO_NI
		port map( D => \PLD21/W_8\, Q => \363\, CLK => \PLD32/W\, Qneg => open );
	U537 : FF_D_CO_NI
		port map( D => \PLD21/W_9\, Q => \364\, CLK => \PLD32/W\, Qneg => open );
	U538 : FF_D_CO_NI
		port map( D => \PLD21/W_10\, Q => \365\, CLK => \PLD32/W\, Qneg => open );
	U539 : FF_D_CO_NI
		port map( D => \PLD21/W_11\, Q => \366\, CLK => \PLD32/W\, Qneg => open );
	U540 : FF_D_CO_NI
		port map( D => \PLD21/W_12\, Q => \367\, CLK => \PLD32/W\, Qneg => open );
	U541 : AND3_NI
		port map( A => \PLD21/RE\, B => \PLD24/Read_EN_Col\, C => \PLD30/Read_EN_Row\, Y => \PLD32/R\ );
	U542 : AND3_NI
		port map( A => \PLD21/WC\, B => \PLD24/Write_EN_Col\, C => \PLD30/Write_EN_Row\, Y => \PLD32/W\ );
	U543 : AND2_NI
		port map( A => \PLD32/R\, B => \356\, Y => \368\ );
	U544 : AND2_NI
		port map( A => \PLD32/R\, B => \357\, Y => \369\ );
	U545 : OR2_NI
		port map( A => \PLD31/Read_1\, B => \368\, Y => \PLD32/Read_1\ );
	U546 : OR2_NI
		port map( A => \PLD31/Read_2\, B => \369\, Y => \PLD32/Read_2\ );
	U547 : AND2_NI
		port map( A => \PLD32/R\, B => \358\, Y => \370\ );
	U548 : OR2_NI
		port map( A => \PLD31/Read_3\, B => \370\, Y => \PLD32/Read_3\ );
	U549 : AND2_NI
		port map( A => \PLD32/R\, B => \359\, Y => \371\ );
	U550 : OR2_NI
		port map( A => \PLD31/Read_4\, B => \371\, Y => \PLD32/Read_4\ );
	U551 : AND2_NI
		port map( A => \PLD32/R\, B => \360\, Y => \372\ );
	U552 : OR2_NI
		port map( A => \PLD31/Read_5\, B => \372\, Y => \PLD32/Read_5\ );
	U553 : AND2_NI
		port map( A => \PLD32/R\, B => \361\, Y => \373\ );
	U554 : AND2_NI
		port map( A => \PLD32/R\, B => \362\, Y => \374\ );
	U555 : AND2_NI
		port map( A => \PLD32/R\, B => \363\, Y => \375\ );
	U556 : AND2_NI
		port map( A => \PLD32/R\, B => \364\, Y => \376\ );
	U557 : AND2_NI
		port map( A => \PLD32/R\, B => \365\, Y => \377\ );
	U558 : AND2_NI
		port map( A => \PLD32/R\, B => \366\, Y => \378\ );
	U559 : AND2_NI
		port map( A => \PLD32/R\, B => \367\, Y => \379\ );
	U560 : OR2_NI
		port map( A => \PLD31/Read_6\, B => \373\, Y => \PLD32/Read_6\ );
	U561 : OR2_NI
		port map( A => \PLD31/Read_7\, B => \374\, Y => \PLD32/Read_7\ );
	U562 : OR2_NI
		port map( A => \PLD31/Read_8\, B => \375\, Y => \PLD32/Read_8\ );
	U563 : OR2_NI
		port map( A => \PLD31/Read_9\, B => \376\, Y => \PLD32/Read_9\ );
	U564 : OR2_NI
		port map( A => \PLD31/Read_10\, B => \377\, Y => \PLD32/Read_10\ );
	U565 : OR2_NI
		port map( A => \PLD31/Read_11\, B => \378\, Y => \PLD32/Read_11\ );
	U566 : OR2_NI
		port map( A => \PLD31/Read_12\, B => \379\, Y => \PLD32/Read_12\ );
	U567 : FF_D_CO_NI
		port map( D => \PLD21/W_1\, Q => \380\, CLK => \PLD33/W\, Qneg => open );
	U568 : FF_D_CO_NI
		port map( D => \PLD21/W_2\, Q => \381\, CLK => \PLD33/W\, Qneg => open );
	U569 : FF_D_CO_NI
		port map( D => \PLD21/W_3\, Q => \382\, CLK => \PLD33/W\, Qneg => open );
	U570 : FF_D_CO_NI
		port map( D => \PLD21/W_4\, Q => \383\, CLK => \PLD33/W\, Qneg => open );
	U571 : FF_D_CO_NI
		port map( D => \PLD21/W_5\, Q => \384\, CLK => \PLD33/W\, Qneg => open );
	U572 : FF_D_CO_NI
		port map( D => \PLD21/W_6\, Q => \385\, CLK => \PLD33/W\, Qneg => open );
	U573 : FF_D_CO_NI
		port map( D => \PLD21/W_7\, Q => \386\, CLK => \PLD33/W\, Qneg => open );
	U574 : FF_D_CO_NI
		port map( D => \PLD21/W_8\, Q => \387\, CLK => \PLD33/W\, Qneg => open );
	U575 : FF_D_CO_NI
		port map( D => \PLD21/W_9\, Q => \388\, CLK => \PLD33/W\, Qneg => open );
	U576 : FF_D_CO_NI
		port map( D => \PLD21/W_10\, Q => \389\, CLK => \PLD33/W\, Qneg => open );
	U577 : FF_D_CO_NI
		port map( D => \PLD21/W_11\, Q => \390\, CLK => \PLD33/W\, Qneg => open );
	U578 : FF_D_CO_NI
		port map( D => \PLD21/W_12\, Q => \391\, CLK => \PLD33/W\, Qneg => open );
	U579 : AND3_NI
		port map( A => \PLD21/RE\, B => \PLD25/Read_EN_Col\, C => \PLD30/Read_EN_Row\, Y => \PLD33/R\ );
	U580 : AND3_NI
		port map( A => \PLD21/WC\, B => \PLD25/Write_EN_Col\, C => \PLD30/Write_EN_Row\, Y => \PLD33/W\ );
	U581 : AND2_NI
		port map( A => \PLD33/R\, B => \380\, Y => \392\ );
	U582 : AND2_NI
		port map( A => \PLD33/R\, B => \381\, Y => \393\ );
	U583 : OR2_NI
		port map( A => \PLD32/Read_1\, B => \392\, Y => \PLD21/Read_1\ );
	U584 : OR2_NI
		port map( A => \PLD32/Read_2\, B => \393\, Y => \PLD21/Read_2\ );
	U585 : AND2_NI
		port map( A => \PLD33/R\, B => \382\, Y => \394\ );
	U586 : OR2_NI
		port map( A => \PLD32/Read_3\, B => \394\, Y => \PLD21/Read_3\ );
	U587 : AND2_NI
		port map( A => \PLD33/R\, B => \383\, Y => \395\ );
	U588 : OR2_NI
		port map( A => \PLD32/Read_4\, B => \395\, Y => \PLD21/Read_4\ );
	U589 : AND2_NI
		port map( A => \PLD33/R\, B => \384\, Y => \396\ );
	U590 : OR2_NI
		port map( A => \PLD32/Read_5\, B => \396\, Y => \PLD21/Read_5\ );
	U591 : AND2_NI
		port map( A => \PLD33/R\, B => \385\, Y => \397\ );
	U592 : AND2_NI
		port map( A => \PLD33/R\, B => \386\, Y => \398\ );
	U593 : AND2_NI
		port map( A => \PLD33/R\, B => \387\, Y => \399\ );
	U594 : AND2_NI
		port map( A => \PLD33/R\, B => \388\, Y => \400\ );
	U595 : AND2_NI
		port map( A => \PLD33/R\, B => \389\, Y => \401\ );
	U596 : AND2_NI
		port map( A => \PLD33/R\, B => \390\, Y => \402\ );
	U597 : AND2_NI
		port map( A => \PLD33/R\, B => \391\, Y => \403\ );
	U598 : OR2_NI
		port map( A => \PLD32/Read_6\, B => \397\, Y => \PLD21/Read_6\ );
	U599 : OR2_NI
		port map( A => \PLD32/Read_7\, B => \398\, Y => \PLD21/Read_7\ );
	U600 : OR2_NI
		port map( A => \PLD32/Read_8\, B => \399\, Y => \PLD34/Green4\ );
	U601 : OR2_NI
		port map( A => \PLD32/Read_9\, B => \400\, Y => \PLD21/Read_9\ );
	U602 : OR2_NI
		port map( A => \PLD32/Read_10\, B => \401\, Y => \PLD21/Read_10\ );
	U603 : OR2_NI
		port map( A => \PLD32/Read_11\, B => \402\, Y => \PLD21/Read_11\ );
	U604 : OR2_NI
		port map( A => \PLD32/Read_12\, B => \403\, Y => \PLD21/Read_12\ );
	U674 : MUX4_1_NI
		port map( S0 => \PLD37/SS0\, S1 => \PLD37/SS1\, EN => \450\, Y => \PLD37/IO19\, I0 => \PLD21/WCB_1\, I1 => \PLD35/SW2\, I2 => \PLD21/WRB_1\, I3 => \PLD35/SW2\ );
	U675 : MUX4_1_NI
		port map( S0 => \PLD37/SS0\, S1 => \PLD37/SS1\, EN => \450\, Y => \PLD37/IO20\, I0 => \PLD21/WCB_2\, I1 => \PLD35/SW2\, I2 => \PLD21/WRB_2\, I3 => \PLD35/SW2\ );
	U676 : MUX4_1_NI
		port map( S0 => \PLD37/SS0\, S1 => \PLD37/SS1\, EN => \450\, Y => \PLD37/IO21\, I0 => \PLD35/SW2\, I1 => \PLD35/SW2\, I2 => \PLD35/SW2\, I3 => \PLD35/SW2\ );
	U677 : MUX4_1_NI
		port map( S0 => \PLD37/SS0\, S1 => \PLD37/SS1\, EN => \450\, Y => \PLD37/IO22\, I0 => \PLD35/SW2\, I1 => \PLD35/SW2\, I2 => \PLD35/SW2\, I3 => \PLD35/SW2\ );
	U678 : DIGITAL_LOW_NI
		port map( Y => \450\ );
	U645 : OR2_NI
		port map( A => \PLD36/QG\, B => \425\, Y => \432\ );
	U646 : OR2_NI
		port map( A => \PLD36/QF\, B => \425\, Y => \PLD35/CF\ );
	U647 : OR2_NI
		port map( A => \PLD36/QE\, B => \425\, Y => \430\ );
	U648 : OR2_NI
		port map( A => \PLD36/QD\, B => \425\, Y => \429\ );
	U649 : OR2_NI
		port map( A => \PLD36/QC\, B => \425\, Y => \PLD35/CC\ );
	U650 : OR2_NI
		port map( A => \PLD36/QB\, B => \425\, Y => \PLD35/CB\ );
	U651 : OR2_NI
		port map( A => \PLD36/QA\, B => \425\, Y => \PLD35/CA\ );
	U652 : OR2_NI
		port map( A => \428\, B => \427\, Y => \426\ );
	U653 : AND2_NI
		port map( A => \PLD35/Row_Col_EN\, B => \426\, Y => \425\ );
	U654 : AND2_NI
		port map( A => \434\, B => \433\, Y => \PLD35/CE\ );
	U655 : AND2_NI
		port map( A => \435\, B => \433\, Y => \PLD35/CG\ );
	U656 : AND2_NI
		port map( A => \429\, B => \433\, Y => \PLD35/CD\ );
	U657 : AND2_NI
		port map( A => \432\, B => \431\, Y => \435\ );
	U658 : AND2_NI
		port map( A => \430\, B => \431\, Y => \434\ );
	U661 : BUF_INV_NI
		port map( Y => \427\, A => \PLD35/AN3\ );
	U662 : BUF_INV_NI
		port map( Y => \428\, A => \PLD35/AN1\ );
	U659 : NAND2_NI
		port map( A => \PLD35/Row_Col_EN\, B => \427\, Y => \431\ );
	U660 : NAND2_NI
		port map( A => \PLD35/Row_Col_EN\, B => \428\, Y => \433\ );
	U5 : CNTR_4BIN_S_NI
		port map( QA => \PLD2/Q1\, QB => \PLD2/Q2\, QC => \PLD2/Q3\, QD => \PLD2/Q4\, RCO => \45\, A => \46\, B => \46\, C => \46\, D => \46\, ENP => \46\, ENT => \46\, LOAD => \46\, CLR => \47\, CLK => \PLD15/HCLOCK\ );
	U6 : CNTR_4BIN_S_NI
		port map( QA => \PLD2/Q5\, QB => \PLD2/Q6\, QC => \PLD2/Q7\, QD => \PLD2/Q8\, RCO => \48\, A => \46\, B => \46\, C => \46\, D => \46\, ENP => \46\, ENT => \45\, LOAD => \46\, CLR => \47\, CLK => \PLD15/HCLOCK\ );
	U7 : CNTR_4BIN_S_NI
		port map( QA => \PLD2/Q9\, QB => \PLD2/Q10\, QC => open, QD => open, RCO => open, A => \46\, B => \46\, C => \46\, D => \46\, ENP => \46\, ENT => \49\, LOAD => \46\, CLR => \47\, CLK => \PLD15/HCLOCK\ );
	U8 : DIGITAL_HIGH_NI
		port map( Y => \46\ );
	U9 : BUF_INV_NI
		port map( Y => \47\, A => \PLD2/clr\ );
	U20 : AND2_NI
		port map( A => \45\, B => \48\, Y => \49\ );
	U10 : COMP_4_NI
		port map( A2 => \PLD2/Q3\, B2 => \PLD3/B7\, A1 => \PLD2/Q2\, B1 => \PLD3/B7\, OAGTB => \50\, A0 => \PLD2/Q1\, B0 => \PLD3/B7\, A3 => \PLD2/Q4\, B3 => \PLD3/B7\, OAEQB => \51\, OALTB => \52\, AEQB => \PLD3/B8\, ALTB => \PLD3/B7\, AGTB => \PLD3/B7\ );
	U19 : COMP_4_NI
		port map( A2 => \PLD2/Q7\, B2 => \PLD3/B7\, A1 => \PLD2/Q6\, B1 => \PLD3/B7\, OAGTB => \53\, A0 => \PLD2/Q5\, B0 => \PLD3/B7\, A3 => \PLD2/Q8\, B3 => \PLD3/B8\, OAEQB => \54\, OALTB => \55\, AEQB => \51\, ALTB => \52\, AGTB => \50\ );
	U25 : COMP_4_NI
		port map( A2 => \56\, B2 => \56\, A1 => \PLD2/Q10\, B1 => \PLD3/B8\, OAGTB => \PLD3/OAGTB\, A0 => \PLD2/Q9\, B0 => \PLD3/B7\, A3 => \56\, B3 => \56\, OAEQB => \PLD3/OAEQB\, OALTB => \PLD3/OALTB\, AEQB => \54\, ALTB => \55\, AGTB => \53\ );
	U26 : DIGITAL_LOW_NI
		port map( Y => \56\ );
	U27 : COMP_4_NI
		port map( A2 => \PLD2/Q3\, B2 => \PLD4/B4\, A1 => \PLD2/Q2\, B1 => \PLD4/B4\, OAGTB => \57\, A0 => \PLD2/Q1\, B0 => \PLD4/B4\, A3 => \PLD2/Q4\, B3 => \PLD4/B4\, OAEQB => \58\, OALTB => \59\, AEQB => \PLD4/B5\, ALTB => \PLD4/B4\, AGTB => \PLD4/B4\ );
	U28 : COMP_4_NI
		port map( A2 => \PLD2/Q7\, B2 => \PLD4/B4\, A1 => \PLD2/Q6\, B1 => \PLD4/B4\, OAGTB => \60\, A0 => \PLD2/Q5\, B0 => \PLD4/B5\, A3 => \PLD2/Q8\, B3 => \PLD4/B5\, OAEQB => \61\, OALTB => \62\, AEQB => \58\, ALTB => \59\, AGTB => \57\ );
	U52 : COMP_4_NI
		port map( A2 => \63\, B2 => \63\, A1 => \PLD2/Q10\, B1 => \PLD4/B5\, OAGTB => \PLD4/OAGTB\, A0 => \PLD2/Q9\, B0 => \PLD4/B4\, A3 => \63\, B3 => \63\, OAEQB => \PLD4/OAEQB\, OALTB => \PLD4/OALTB\, AEQB => \61\, ALTB => \62\, AGTB => \60\ );
	U53 : DIGITAL_LOW_NI
		port map( Y => \63\ );
	U54 : COMP_4_NI
		port map( A2 => \PLD2/Q3\, B2 => \PLD5/ALTB\, A1 => \PLD2/Q2\, B1 => \PLD5/ALTB\, OAGTB => \64\, A0 => \PLD2/Q1\, B0 => \PLD5/ALTB\, A3 => \PLD2/Q4\, B3 => \PLD5/ALTB\, OAEQB => \65\, OALTB => \66\, AEQB => \PLD5/B10\, ALTB => \PLD5/ALTB\, AGTB => \PLD5/ALTB\ );
	U55 : COMP_4_NI
		port map( A2 => \PLD2/Q7\, B2 => \PLD5/B10\, A1 => \PLD2/Q6\, B1 => \PLD5/B10\, OAGTB => \67\, A0 => \PLD2/Q5\, B0 => \PLD5/B10\, A3 => \PLD2/Q8\, B3 => \PLD5/B10\, OAEQB => \68\, OALTB => \69\, AEQB => \65\, ALTB => \66\, AGTB => \64\ );
	U57 : COMP_4_NI
		port map( A2 => \70\, B2 => \70\, A1 => \PLD2/Q10\, B1 => \PLD5/B10\, OAGTB => \PLD5/OAGTB\, A0 => \PLD2/Q9\, B0 => \PLD5/ALTB\, A3 => \70\, B3 => \70\, OAEQB => \PLD5/OAEQB\, OALTB => \PLD5/OALTB\, AEQB => \68\, ALTB => \69\, AGTB => \67\ );
	U58 : DIGITAL_LOW_NI
		port map( Y => \70\ );
	U59 : COMP_4_NI
		port map( A2 => \PLD2/Q3\, B2 => \PLD7/B5\, A1 => \PLD2/Q2\, B1 => \PLD7/B5\, OAGTB => \71\, A0 => \PLD2/Q1\, B0 => \PLD7/B5\, A3 => \PLD2/Q4\, B3 => \PLD7/B5\, OAEQB => \72\, OALTB => \73\, AEQB => \PLD7/B6\, ALTB => \PLD7/B5\, AGTB => \PLD7/B5\ );
	U60 : COMP_4_NI
		port map( A2 => \PLD2/Q7\, B2 => \PLD7/B5\, A1 => \PLD2/Q6\, B1 => \PLD7/B6\, OAGTB => \74\, A0 => \PLD2/Q5\, B0 => \PLD7/B5\, A3 => \PLD2/Q8\, B3 => \PLD7/B5\, OAEQB => \75\, OALTB => \76\, AEQB => \72\, ALTB => \73\, AGTB => \71\ );
	U61 : COMP_4_NI
		port map( A2 => \77\, B2 => \77\, A1 => \PLD2/Q10\, B1 => \PLD7/B6\, OAGTB => \PLD7/OAGTB\, A0 => \PLD2/Q9\, B0 => \PLD7/B6\, A3 => \77\, B3 => \77\, OAEQB => \PLD7/OAEQB\, OALTB => \PLD7/OALTB\, AEQB => \75\, ALTB => \76\, AGTB => \74\ );
	U62 : DIGITAL_LOW_NI
		port map( Y => \77\ );
	U63 : CNTR_4BIN_S_NI
		port map( QA => \PLD8/Q1\, QB => \PLD8/Q2\, QC => \PLD8/Q3\, QD => \PLD8/Q4\, RCO => \78\, A => \79\, B => \79\, C => \79\, D => \79\, ENP => \79\, ENT => \79\, LOAD => \79\, CLR => \80\, CLK => \PLD14/Hsync\ );
	U64 : CNTR_4BIN_S_NI
		port map( QA => \PLD8/Q5\, QB => \PLD8/Q6\, QC => \PLD8/Q7\, QD => \PLD8/Q8\, RCO => \81\, A => \79\, B => \79\, C => \79\, D => \79\, ENP => \79\, ENT => \78\, LOAD => \79\, CLR => \80\, CLK => \PLD14/Hsync\ );
	U65 : CNTR_4BIN_S_NI
		port map( QA => \PLD8/Q9\, QB => \PLD8/Q10\, QC => open, QD => open, RCO => open, A => \79\, B => \79\, C => \79\, D => \79\, ENP => \79\, ENT => \82\, LOAD => \79\, CLR => \80\, CLK => \PLD14/Hsync\ );
	U66 : DIGITAL_HIGH_NI
		port map( Y => \79\ );
	U67 : BUF_INV_NI
		port map( Y => \80\, A => \PLD8/clr\ );
	U82 : AND2_NI
		port map( A => \78\, B => \81\, Y => \82\ );
	U83 : COMP_4_NI
		port map( A2 => \PLD8/Q3\, B2 => \PLD9/B5\, A1 => \PLD8/Q2\, B1 => \PLD9/B5\, OAGTB => \83\, A0 => \PLD8/Q1\, B0 => \PLD9/B5\, A3 => \PLD8/Q4\, B3 => \PLD9/B5\, OAEQB => \84\, OALTB => \85\, AEQB => \PLD9/B6\, ALTB => \PLD9/B5\, AGTB => \PLD9/B5\ );
	U84 : COMP_4_NI
		port map( A2 => \PLD8/Q7\, B2 => \PLD9/B6\, A1 => \PLD8/Q6\, B1 => \PLD9/B6\, OAGTB => \86\, A0 => \PLD8/Q5\, B0 => \PLD9/B5\, A3 => \PLD8/Q8\, B3 => \PLD9/B6\, OAEQB => \87\, OALTB => \88\, AEQB => \84\, ALTB => \85\, AGTB => \83\ );
	U86 : COMP_4_NI
		port map( A2 => \89\, B2 => \89\, A1 => \PLD8/Q10\, B1 => \PLD9/B5\, OAGTB => \PLD9/OAGTB\, A0 => \PLD8/Q9\, B0 => \PLD9/B6\, A3 => \89\, B3 => \89\, OAEQB => \PLD9/OAEQB\, OALTB => \PLD9/OALTB\, AEQB => \87\, ALTB => \88\, AGTB => \86\ );
	U87 : DIGITAL_LOW_NI
		port map( Y => \89\ );
	U88 : COMP_4_NI
		port map( A2 => \PLD8/Q3\, B2 => \PLD10/B1\, A1 => \PLD8/Q2\, B1 => \PLD10/B2\, OAGTB => \90\, A0 => \PLD8/Q1\, B0 => \PLD10/B1\, A3 => \PLD8/Q4\, B3 => \PLD10/B2\, OAEQB => \91\, OALTB => \92\, AEQB => \PLD10/B2\, ALTB => \PLD10/B1\, AGTB => \PLD10/B1\ );
	U91 : COMP_4_NI
		port map( A2 => \PLD8/Q7\, B2 => \PLD10/B2\, A1 => \PLD8/Q6\, B1 => \PLD10/B2\, OAGTB => \93\, A0 => \PLD8/Q5\, B0 => \PLD10/B1\, A3 => \PLD8/Q8\, B3 => \PLD10/B2\, OAEQB => \94\, OALTB => \95\, AEQB => \91\, ALTB => \92\, AGTB => \90\ );
	U93 : COMP_4_NI
		port map( A2 => \96\, B2 => \96\, A1 => \PLD8/Q10\, B1 => \PLD10/B1\, OAGTB => \PLD10/OAGTB\, A0 => \PLD8/Q9\, B0 => \PLD10/B2\, A3 => \96\, B3 => \96\, OAEQB => \PLD10/OAEQB\, OALTB => \PLD10/OALTB\, AEQB => \94\, ALTB => \95\, AGTB => \93\ );
	U94 : DIGITAL_LOW_NI
		port map( Y => \96\ );
	U95 : COMP_4_NI
		port map( A2 => \PLD8/Q3\, B2 => \PLD11/B3\, A1 => \PLD8/Q2\, B1 => \PLD11/B1\, OAGTB => \97\, A0 => \PLD8/Q1\, B0 => \PLD11/B1\, A3 => \PLD8/Q4\, B3 => \PLD11/B3\, OAEQB => \98\, OALTB => \99\, AEQB => \PLD11/B3\, ALTB => \PLD11/B1\, AGTB => \PLD11/B1\ );
	U96 : COMP_4_NI
		port map( A2 => \PLD8/Q7\, B2 => \PLD11/B3\, A1 => \PLD8/Q6\, B1 => \PLD11/B3\, OAGTB => \100\, A0 => \PLD8/Q5\, B0 => \PLD11/B1\, A3 => \PLD8/Q8\, B3 => \PLD11/B3\, OAEQB => \101\, OALTB => \102\, AEQB => \98\, ALTB => \99\, AGTB => \97\ );
	U97 : COMP_4_NI
		port map( A2 => \103\, B2 => \103\, A1 => \PLD8/Q10\, B1 => \PLD11/B1\, OAGTB => \PLD11/OAGTB\, A0 => \PLD8/Q9\, B0 => \PLD11/B3\, A3 => \103\, B3 => \103\, OAEQB => \PLD11/OAEQB\, OALTB => \PLD11/OALTB\, AEQB => \101\, ALTB => \102\, AGTB => \100\ );
	U98 : DIGITAL_LOW_NI
		port map( Y => \103\ );
	U99 : COMP_4_NI
		port map( A2 => \PLD8/Q3\, B2 => \PLD12/B9\, A1 => \PLD8/Q2\, B1 => \PLD12/B9\, OAGTB => \104\, A0 => \PLD8/Q1\, B0 => \PLD12/AEQB\, A3 => \PLD8/Q4\, B3 => \PLD12/AEQB\, OAEQB => \105\, OALTB => \106\, AEQB => \PLD12/AEQB\, ALTB => \PLD12/B9\, AGTB => \PLD12/B9\ );
	U100 : COMP_4_NI
		port map( A2 => \PLD8/Q7\, B2 => \PLD12/B9\, A1 => \PLD8/Q6\, B1 => \PLD12/B9\, OAGTB => \107\, A0 => \PLD8/Q5\, B0 => \PLD12/B9\, A3 => \PLD8/Q8\, B3 => \PLD12/B9\, OAEQB => \108\, OALTB => \109\, AEQB => \105\, ALTB => \106\, AGTB => \104\ );
	U101 : COMP_4_NI
		port map( A2 => \110\, B2 => \110\, A1 => \PLD8/Q10\, B1 => \PLD12/AEQB\, OAGTB => \PLD12/OAGTB\, A0 => \PLD8/Q9\, B0 => \PLD12/B9\, A3 => \110\, B3 => \110\, OAEQB => \PLD12/OAEQB\, OALTB => \PLD12/OALTB\, AEQB => \108\, ALTB => \109\, AGTB => \107\ );
	U102 : DIGITAL_LOW_NI
		port map( Y => \110\ );
	U664 : CNTR_4BIN_S_NI
		port map( QA => \PLD39/Q1\, QB => \PLD39/Q2\, QC => \PLD39/Q3\, QD => \PLD39/Q4\, RCO => \472\, A => \473\, B => \473\, C => \473\, D => \473\, ENP => \473\, ENT => \473\, LOAD => \473\, CLR => \474\, CLK => \PLD15/HCLOCK\ );
	U665 : CNTR_4BIN_S_NI
		port map( QA => \PLD39/Q5\, QB => \PLD39/Q6\, QC => \PLD39/Q7\, QD => \PLD39/Q8\, RCO => \475\, A => \473\, B => \473\, C => \473\, D => \473\, ENP => \473\, ENT => \472\, LOAD => \473\, CLR => \474\, CLK => \PLD15/HCLOCK\ );
	U666 : CNTR_4BIN_S_NI
		port map( QA => \PLD39/Q9\, QB => \PLD39/Q10\, QC => open, QD => open, RCO => open, A => \473\, B => \473\, C => \473\, D => \473\, ENP => \473\, ENT => \476\, LOAD => \473\, CLR => \474\, CLK => \PLD15/HCLOCK\ );
	U667 : DIGITAL_HIGH_NI
		port map( Y => \473\ );
	U668 : BUF_INV_NI
		port map( Y => \474\, A => \PLD39/clr\ );
	U669 : AND2_NI
		port map( A => \472\, B => \475\, Y => \476\ );
	U76 : CNTR_4BIN_S_NI
		port map( QA => \PLD16/Q1\, QB => \PLD16/Q2\, QC => \PLD16/Q3\, QD => \PLD16/Q4\, RCO => \455\, A => \456\, B => \456\, C => \456\, D => \456\, ENP => \456\, ENT => \456\, LOAD => \456\, CLR => \457\, CLK => \PLD14/Hsync\ );
	U77 : CNTR_4BIN_S_NI
		port map( QA => \PLD16/Q5\, QB => \PLD16/Q6\, QC => \PLD16/Q7\, QD => \PLD16/Q8\, RCO => \458\, A => \456\, B => \456\, C => \456\, D => \456\, ENP => \456\, ENT => \455\, LOAD => \456\, CLR => \457\, CLK => \PLD14/Hsync\ );
	U78 : CNTR_4BIN_S_NI
		port map( QA => \PLD16/Q9\, QB => \PLD16/Q10\, QC => open, QD => open, RCO => open, A => \456\, B => \456\, C => \456\, D => \456\, ENP => \456\, ENT => \459\, LOAD => \456\, CLR => \457\, CLK => \PLD14/Hsync\ );
	U79 : DIGITAL_HIGH_NI
		port map( Y => \456\ );
	U80 : BUF_INV_NI
		port map( Y => \457\, A => \PLD16/clr\ );
	U81 : AND2_NI
		port map( A => \455\, B => \458\, Y => \459\ );
end behavioral;
